// Auto-generated by Clef Clef Bind — mcp target
// Concept: GroupSpec
// Do not edit manually; regenerate with: clef interface generate

export const groupSpecTools = [
  {
    "type": "tool",
    "name": "group_spec_create",
    "description": "Create groupspec — Register a new named group spec with its serialized GroupingConfig and \n AggregationDef array . The spec is immediately available for evaluation \n and retrieval .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "grouping": {
          "type": "string"
        },
        "aggregations": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "grouping",
        "aggregations"
      ]
    }
  },
  {
    "type": "resource",
    "name": "group_spec_get",
    "uri": "urn:clef://group-specs/{name}",
    "description": "Get groupspec — Return the group spec identifier , its serialized GroupingConfig , \n AggregationDef array , and optional HAVING filter for the given name ."
  },
  {
    "type": "tool",
    "name": "group_spec_evaluate",
    "description": "Evaluate groupspec — Apply the named group spec s GroupingConfig to the JSON serialized row \n array , compute each AggregationDef per bucket , and apply the optional \n HAVING filter to prune groups . The result is a JSON array where each \n entry contains the group key , the matching rows , and the computed \n aggregates : [ { key , rows , aggregates } ] .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "rows": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "rows"
      ]
    }
  },
  {
    "type": "resource-template",
    "name": "group_spec_list",
    "uriTemplate": "urn:clef://group-specs",
    "description": "List groupspec — Return a JSON serialized array of all registered group spec names ."
  }
];
