// Auto-generated by COPF Interface Kit — cli target
// Concept: BuildCache
// Do not edit manually; regenerate with: copf interface generate

import { Command } from 'commander';

export const buildCacheCommand = new Command('build-cache')
  .description('Manage incremental build cache for generation pipeline.');

buildCacheCommand
  .command('check')
  .description('Check if a generation step is cached')
  .requiredOption('-k, --step-key <stepKey>', 'Unique step identifier (generator:concept)')
  .requiredOption('--input-hash <inputHash>', 'Hash of current input')
  .option('--deterministic <deterministic>', 'Whether generator is deterministic')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'check', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

buildCacheCommand
  .command('record')
  .description('Record a generation result in the cache')
  .requiredOption('--step-key <stepKey>', 'Step Key')
  .requiredOption('--input-hash <inputHash>', 'Input Hash')
  .requiredOption('--output-hash <outputHash>', 'Output Hash')
  .requiredOption('--output-ref <outputRef>', 'Output Ref')
  .requiredOption('--source-locator <sourceLocator>', 'Source Locator')
  .requiredOption('--deterministic <deterministic>', 'Deterministic')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'record', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

buildCacheCommand
  .command('invalidate')
  .description('Invalidate a single cache entry')
  .requiredOption('-k, --step-key <stepKey>', 'Step key to invalidate')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'invalidate', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

buildCacheCommand
  .command('invalidate-by-source')
  .description('Invalidate all steps that used a source file')
  .argument('<sourceLocator>', 'Source Locator')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf build-cache invalidate-by-source specs/app/article.concept  # Invalidate after concept change')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'invalidateBySource', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

buildCacheCommand
  .command('invalidate-by-kind')
  .description('Invalidate all steps producing a given IR kind')
  .argument('<kindName>', 'Kind Name')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf build-cache invalidate-by-kind TypeScriptFiles  # Invalidate all TypeScript generation')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'invalidateByKind', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

buildCacheCommand
  .command('invalidate-all')
  .description('Clear the entire build cache')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf build-cache invalidate-all  # Full cache reset')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'invalidateAll', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

buildCacheCommand
  .command('status')
  .description('Show all cache entries with staleness indicators')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf build-cache status  # View cache status')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'status', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

buildCacheCommand
  .command('stale-steps')
  .description('List step keys that need regeneration')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf build-cache stale-steps  # Find stale entries')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'staleSteps', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const buildCacheCommandTree = {
  group: 'build-cache',
  description: 'Manage incremental build cache for generation pipeline.',
  commands: [{ action: 'check', command: 'check' }, { action: 'record', command: 'record' }, { action: 'invalidate', command: 'invalidate' }, { action: 'invalidateBySource', command: 'invalidate-by-source' }, { action: 'invalidateByKind', command: 'invalidate-by-kind' }, { action: 'invalidateAll', command: 'invalidate-all' }, { action: 'status', command: 'status' }, { action: 'staleSteps', command: 'stale-steps' }],
};
