// Auto-generated by Clef Clef Bind — cli target
// Concept: QueryProgram
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const queryProgramCommand = new Command('query-program')
  .description('Build sequences of query instructions as inspectable , composable data . A QueryProgram describes what a view intends to fetch and transform without executing side effects . Programs capture scan , filter , sort , group , project , limit , and pure termination steps as an ordered instruction list . Programs can be analyzed for the fields they read , composed via monadic bind , and handed to an interpreter or optimizer');

queryProgramCommand
  .command('create')
  .description('Initialize an empty query program ready to receive instructions . The program begins with an empty instruction list , no bindings , and terminated set to false .')
  .requiredOption('--program <program>', 'Program')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'create', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('scan')
  .description('Append a Scan instruction that reads all records from the named source relation . The resulting record set is bound to bindAs for use by subsequent instructions .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'scan', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('filter')
  .description('Append a Filter instruction that applies a serialized FilterNode predicate to the current record set . Only records satisfying the predicate are kept . The filtered set is bound to bindAs .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--node <node>', 'Node')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'filter', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('sort')
  .description('Append a Sort instruction that orders the current record set by the given JSON serialized SortKey array . An empty key array preserves the existing order .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--keys <keys>', 'Keys')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'sort', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('group')
  .description('Append a Group instruction that partitions the current record set by the given key fields . The config string is a JSON object specifying aggregation options ( e . g . count , sum , list ) . The grouped result is bound to bindAs .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--keys <keys>', 'Keys')
  .requiredOption('--config <config>', 'Config')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'group', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('project')
  .description('Append a Project instruction that selects a subset of fields from each record . The fields parameter is a JSON array of field names to retain . All other fields are dropped from the output . The projected set is bound to bindAs .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--fields <fields>', 'Fields')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'project', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('limit')
  .description('Append a Limit instruction that truncates the current record set to at most count records . A count of zero returns an empty set . The truncated set is bound to output .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--count <count>', 'Count')
  .requiredOption('--output <output>', 'Output')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'limit', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('pure')
  .description('Terminate the program with a return value consisting of a variant tag and output binding . No further instructions may be appended after pure . The program s terminated flag is set to true .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--variant <variant>', 'Variant')
  .requiredOption('--output <output>', 'Output')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'pure', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('join')
  .description('Append a Join instruction that enriches the current record set by joining against a second relation . For each record in the current set , finds matching records in source where localField equals foreignField , and attaches the matched data under bindAs . Used for schema membership joins : join membership relation where entity_id matches node , attaching schemas array to each record .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--local-field <localField>', 'Local Field')
  .requiredOption('--foreign-field <foreignField>', 'Foreign Field')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'join', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryProgramCommand
  .command('compose')
  .description('Monadic bind : create a new program that runs first , binds its terminal output value to bindAs , then continues with second . The composed program inherits the union of both programs readFields .')
  .requiredOption('--first <first>', 'First')
  .requiredOption('--second <second>', 'Second')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryProgram', 'compose', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const queryProgramCommandTree = {
  group: 'query-program',
  description: 'Build sequences of query instructions as inspectable , composable data . A QueryProgram describes what a view intends to fetch and transform without executing side effects . Programs capture scan , filter , sort , group , project , limit , and pure termination steps as an ordered instruction list . Programs can be analyzed for the fields they read , composed via monadic bind , and handed to an interpreter or optimizer',
  commands: [{ action: 'create', command: 'create' }, { action: 'scan', command: 'scan' }, { action: 'filter', command: 'filter' }, { action: 'sort', command: 'sort' }, { action: 'group', command: 'group' }, { action: 'project', command: 'project' }, { action: 'limit', command: 'limit' }, { action: 'pure', command: 'pure' }, { action: 'join', command: 'join' }, { action: 'compose', command: 'compose' }],
};
