// Auto-generated by Clef Clef Bind — cli target
// Concept: SyncScaffoldGen
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const syncScaffoldGenCommand = new Command('sync-scaffold-gen')
  .description('Generate synchronization rule ( . sync ) file scaffolds from provided configuration including trigger patterns , guard conditions , and effect actions');

syncScaffoldGenCommand
  .command('generate')
  .description('Generate a well formed . sync file with when where then clauses from the provided trigger and effect configurations . Supports condition types : bind , query , any , not , compare , filter ( filter by expression ) , and guard ( boolean guard ) . Supports multiple then blocks for grouping effects ( no ordering implied ) .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--trigger <trigger>', 'Trigger')
  .requiredOption('--conditions <conditions>', 'Conditions')
  .requiredOption('--effects <effects>', 'Effects')
  .requiredOption('--then-blocks <thenBlocks>', 'Then Blocks')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SyncScaffoldGen', 'generate', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

syncScaffoldGenCommand
  .command('preview')
  .description('Dry run : compute output files without writing . Uses Emitter content addressing to classify each file as new , changed , or unchanged .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--trigger <trigger>', 'Trigger')
  .requiredOption('--conditions <conditions>', 'Conditions')
  .requiredOption('--effects <effects>', 'Effects')
  .requiredOption('--then-blocks <thenBlocks>', 'Then Blocks')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SyncScaffoldGen', 'preview', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

syncScaffoldGenCommand
  .command('register')
  .description('Return static metadata for PluginRegistry . name : SyncScaffoldGen inputKind : SyncConfig outputKind : SyncSpec capabilities : [ sync-spec , when-clause , where-clause , then-clause , filter-condition , guard-condition , multi-then ]')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SyncScaffoldGen', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const syncScaffoldGenCommandTree = {
  group: 'sync-scaffold-gen',
  description: 'Generate synchronization rule ( . sync ) file scaffolds from provided configuration including trigger patterns , guard conditions , and effect actions',
  commands: [{ action: 'generate', command: 'generate' }, { action: 'preview', command: 'preview' }, { action: 'register', command: 'register' }],
};
