// Auto-generated by Clef Clef Bind — cli target
// Concept: StorageProgram
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const storageProgramCommand = new Command('storage-program')
  .description('Build sequences of storage instructions as inspectable , composable data . A StorageProgram describes what a handler intends to do without executing side effects . Programs can be logged , diffed , serialized , composed , and handed to an interpreter or analyzer');

storageProgramCommand
  .command('create')
  .description('Initialize an empty program ready to receive instructions .')
  .requiredOption('--program <program>', 'Program')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'create', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('get')
  .description('Append a Get instruction that reads a single record by key . The fetched value will be bound to the bindAs name during interpretation .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--relation <relation>', 'Relation')
  .requiredOption('--key <key>', 'Key')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('find')
  .description('Append a Find instruction that queries records matching the criteria filter . Results are bound to bindAs during interpretation .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--relation <relation>', 'Relation')
  .requiredOption('--criteria <criteria>', 'Criteria')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'find', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('put')
  .description('Append a Put instruction that writes a record to the given relation at the given key .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--relation <relation>', 'Relation')
  .requiredOption('--key <key>', 'Key')
  .requiredOption('--value <value>', 'Value')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'put', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('del')
  .description('Append a Del instruction that removes a record from the given relation at the given key .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--relation <relation>', 'Relation')
  .requiredOption('--key <key>', 'Key')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'del', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('branch')
  .description('Append a conditional branch whose arms are themselves StoragePrograms , enabling nested control flow within a single program tree .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--condition <condition>', 'Condition')
  .requiredOption('--then-branch <thenBranch>', 'Then Branch')
  .requiredOption('--else-branch <elseBranch>', 'Else Branch')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'branch', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('pure')
  .description('Terminate the program with a return value consisting of a variant tag and output fields . No further instructions may be appended after pure .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--variant <variant>', 'Variant')
  .requiredOption('--output <output>', 'Output')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'pure', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('compose')
  .description('Monadic bind : create a new program that runs first , binds its terminal value to bindAs , then continues with second .')
  .requiredOption('--first <first>', 'First')
  .requiredOption('--second <second>', 'Second')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'compose', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('get-lens')
  .description('Append a GetLens instruction that reads through a typed lens reference . The lens encodes relation , key , and field segments as a StateLens . The fetched value is bound to bindAs .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--lens <lens>', 'Lens')
  .requiredOption('--bind-as <bindAs>', 'Bind As')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'getLens', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('put-lens')
  .description('Append a PutLens instruction that writes through a typed lens reference . The lens encodes the target location as a StateLens .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--lens <lens>', 'Lens')
  .requiredOption('--value <value>', 'Value')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'putLens', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

storageProgramCommand
  .command('modify-lens')
  .description('Append a ModifyLens instruction that reads through a lens , applies a transformation function , and writes back through the same lens . This is a read modify write operation .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--lens <lens>', 'Lens')
  .requiredOption('--fn <fn>', 'Fn')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/StorageProgram', 'modifyLens', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const storageProgramCommandTree = {
  group: 'storage-program',
  description: 'Build sequences of storage instructions as inspectable , composable data . A StorageProgram describes what a handler intends to do without executing side effects . Programs can be logged , diffed , serialized , composed , and handed to an interpreter or analyzer',
  commands: [{ action: 'create', command: 'create' }, { action: 'get', command: 'get' }, { action: 'find', command: 'find' }, { action: 'put', command: 'put' }, { action: 'del', command: 'del' }, { action: 'branch', command: 'branch' }, { action: 'pure', command: 'pure' }, { action: 'compose', command: 'compose' }, { action: 'getLens', command: 'get-lens' }, { action: 'putLens', command: 'put-lens' }, { action: 'modifyLens', command: 'modify-lens' }],
};
