// Auto-generated by Clef Clef Bind — cli target
// Concept: PerformanceProfile
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const performanceProfileCommand = new Command('performance-profile')
  .description('Aggregate performance data per static entity connecting 
 slow operations to their declared structure for optimization . 
 Supports timing breakdown for syncs ( when where then phases ) , 
 selection pipeline ( classify resolve spawn connect render ) , 
 and widget rendering ( render count , unnecessary renders , 
 mount unmount timing ) .');

performanceProfileCommand
  .command('aggregate')
  .description('Aggregate performance data for a static entity over a 
 time window . Window as serialized JSON { start , end } .')
  .requiredOption('--symbol <symbol>', 'Symbol')
  .requiredOption('--window <window>', 'Window')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'aggregate', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

performanceProfileCommand
  .command('hotspots')
  .description('Return top N entities by the given metric ( p50 , p90 , 
 p99 , errorRate , unnecessaryRenderPct ) . Results as 
 serialized JSON array of { symbol , value } .')
  .requiredOption('--kind <kind>', 'Kind')
  .requiredOption('--metric <metric>', 'Metric')
  .requiredOption('--top-n <topN>', 'Top N')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'hotspots', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

performanceProfileCommand
  .command('slow-chains')
  .description('Find sync chains whose total p90 exceeds the threshold . 
 Identifies the bottleneck entity in each chain . Results 
 as serialized JSON array of { flowGraphPath , p90TotalMs , 
 bottleneck } .')
  .requiredOption('--threshold-ms <thresholdMs>', 'Threshold Ms')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'slowChains', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

performanceProfileCommand
  .command('compare-windows')
  .description('Compare performance between two time windows for 
 regression detection . Results as serialized JSON : 
 { aP50 , bP50 , aP99 , bP99 , regression , pctChange } .')
  .requiredOption('--symbol <symbol>', 'Symbol')
  .requiredOption('--window-a <windowA>', 'Window A')
  .requiredOption('--window-b <windowB>', 'Window B')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'compareWindows', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

performanceProfileCommand
  .command('get')
  .description('Retrieve profile metadata .')
  .requiredOption('--profile <profile>', 'Profile')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'get', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const performanceProfileCommandTree = {
  group: 'performance-profile',
  description: 'Aggregate performance data per static entity connecting 
 slow operations to their declared structure for optimization . 
 Supports timing breakdown for syncs ( when where then phases ) , 
 selection pipeline ( classify resolve spawn connect render ) , 
 and widget rendering ( render count , unnecessary renders , 
 mount unmount timing ) .',
  commands: [{ action: 'aggregate', command: 'aggregate' }, { action: 'hotspots', command: 'hotspots' }, { action: 'slowChains', command: 'slow-chains' }, { action: 'compareWindows', command: 'compare-windows' }, { action: 'get', command: 'get' }],
};
