// Auto-generated by Clef Clef Bind — mcp target
// Concept: DeploymentHealth
// Do not edit manually; regenerate with: clef interface generate

export const deploymentHealthTools = [
  {
    "type": "tool",
    "name": "deployment_health_record",
    "description": "Record deploymenthealth — Record a health check snapshot for a deployment . The snapshot \n includes runtime statuses , transport connectivity , storage \n adapter health , sync delivery metrics , concept instance \n counts , and cross runtime latency measurements . Automatically \n correlates with DeploymentEntity to map metrics to the \n static deployment topology .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        },
        "snapshot": {
          "type": "string"
        }
      },
      "required": [
        "deployment",
        "snapshot"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_runtime_health",
    "description": "Runtime health deploymenthealth — Return current health status for all runtimes in a deployment . \n Result as serialized JSON array of { name , status , uptime , \n conceptCount , lastChecked , memoryUsage , cpuUsage } . \n status is one of : healthy , degraded , unhealthy , unreachable .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        }
      },
      "required": [
        "deployment"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_transport_health",
    "description": "Transport health deploymenthealth — Return current connectivity status for all transports . \n Result as serialized JSON array of { from , to , protocol , \n status , latencyP50Ms , latencyP99Ms , errorRate , lastChecked } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        }
      },
      "required": [
        "deployment"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_storage_health",
    "description": "Storage health deploymenthealth — Return current status for all storage adapters . Result as \n serialized JSON array of { name , backend , runtime , status , \n latencyP50Ms , latencyP99Ms , connectionPoolUsage , lastChecked } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        }
      },
      "required": [
        "deployment"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_sync_delivery",
    "description": "Sync delivery deploymenthealth — Return sync delivery metrics success failure rates , retry \n counts , and delivery latency per sync . Result as serialized \n JSON array of { sync , tier , deliveredCount , failedCount , \n retryCount , successRate , avgLatencyMs , p99LatencyMs } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        },
        "since": {
          "type": "string"
        }
      },
      "required": [
        "deployment",
        "since"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_concept_instances",
    "description": "Concept instances deploymenthealth — Return instance counts per concept per runtime . Result as \n serialized JSON array of { concept , runtime , instanceCount , \n activeCount , storageBytes } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        }
      },
      "required": [
        "deployment"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_cross_runtime_latency",
    "description": "Cross runtime latency deploymenthealth — Return the latency matrix between all runtimes . Result as \n serialized JSON array of { from , to , p50Ms , p90Ms , p99Ms , \n sampleCount } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        }
      },
      "required": [
        "deployment"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_hotspots",
    "description": "Hotspots deploymenthealth — Return the top N operational hotspots concepts , syncs , \n or transports with the highest error rates , latency , or \n resource usage . Result as serialized JSON array of { entity , \n kind , metric , value , trend } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        },
        "since": {
          "type": "string"
        },
        "topN": {
          "type": "integer"
        }
      },
      "required": [
        "deployment",
        "since",
        "topN"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_correlate_with_errors",
    "description": "Correlate with errors deploymenthealth — Cross reference deployment health with ErrorCorrelation \n entities . Return errors grouped by failing runtime , transport , \n or storage adapter . Result as serialized JSON array of \n { infrastructure , errorCount , topErrors : [ { kind , message , \n count } ] } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        },
        "since": {
          "type": "string"
        }
      },
      "required": [
        "deployment",
        "since"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_compare_windows",
    "description": "Compare windows deploymenthealth — Compare deployment health between two time windows ( e . g . , \n before and after a deploy ) . Result as serialized JSON of \n { runtimeChanges , latencyChanges , errorRateChanges , \n syncDeliveryChanges , regressions : [ ] } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        },
        "windowA": {
          "type": "string"
        },
        "windowB": {
          "type": "string"
        }
      },
      "required": [
        "deployment",
        "windowA",
        "windowB"
      ]
    }
  },
  {
    "type": "tool",
    "name": "deployment_health_slo_status",
    "description": "Slo status deploymenthealth — Return SLO compliance status availability , latency , \n error budgets per runtime and per concept . Result as \n serialized JSON array of { entity , slo , target , actual , \n budget , budgetRemaining , status } . \n status is one of : met , at risk , breached .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "deployment": {
          "type": "string"
        }
      },
      "required": [
        "deployment"
      ]
    }
  }
];
