// Auto-generated by Clef Clef Bind — cli target
// Concept: ChangeStream
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const changeStreamCommand = new Command('change-stream')
  .description('Ordered , resumable stream of atomic change events from a data source . Events are immutable once appended . Consumers track their position independently via acknowledged offsets , enabling replay and exactly once processing');

changeStreamCommand
  .command('append')
  .description('Event appended with monotonically increasing offset .')
  .requiredOption('--type <type>', 'Type')
  .requiredOption('--before <before>', 'Before')
  .requiredOption('--after <after>', 'After')
  .requiredOption('--source <source>', 'Source')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ChangeStream', 'append', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

changeStreamCommand
  .command('subscribe')
  .description('Subscription created from the given offset , or from stream head .')
  .requiredOption('--from-offset <fromOffset>', 'From Offset')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ChangeStream', 'subscribe', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

changeStreamCommand
  .command('read')
  .description('Returns up to maxCount events from current subscription position .')
  .requiredOption('--subscription-id <subscriptionId>', 'Subscription Id')
  .requiredOption('--max-count <maxCount>', 'Max Count')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ChangeStream', 'read', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

changeStreamCommand
  .command('acknowledge')
  .description('Consumer s acknowledged offset recorded .')
  .requiredOption('--consumer <consumer>', 'Consumer')
  .requiredOption('--offset <offset>', 'Offset')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ChangeStream', 'acknowledge', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

changeStreamCommand
  .command('replay')
  .description('Returns all events in the offset range . Immutable replay always returns the same events .')
  .requiredOption('--from <from>', 'From')
  .requiredOption('--to <to>', 'To')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ChangeStream', 'replay', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const changeStreamCommandTree = {
  group: 'change-stream',
  description: 'Ordered , resumable stream of atomic change events from a data source . Events are immutable once appended . Consumers track their position independently via acknowledged offsets , enabling replay and exactly once processing',
  commands: [{ action: 'append', command: 'append' }, { action: 'subscribe', command: 'subscribe' }, { action: 'read', command: 'read' }, { action: 'acknowledge', command: 'acknowledge' }, { action: 'replay', command: 'replay' }],
};
