// Auto-generated by Clef Clef Bind — claude-skills target
// Concept: Branch
// Do not edit manually; regenerate with: clef interface generate

export async function handleBranchSkill(
  command: string,
  args: Record<string, string>,
  kernel: { handleRequest: (input: Record<string, unknown>) => Promise<any> },
): Promise<string> {
  const result = await kernel.handleRequest({ method: command, ...args });
  if (result.error) return `Error: ${result.error}`;
  return JSON.stringify(result.body, null, 2);
}

export const branchSkillCommands = ['create', 'advance', 'delete', 'protect', 'setUpstream', 'divergencePoint', 'archive'];
