// Auto-generated by Clef Clef Bind — cli target
// Concept: QueryExecution
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const queryExecutionCommand = new Command('query-execution')
  .description('Registry and dispatcher for query execution providers that run structured query programs against a named backend . Manages named provider registrations with kind based routing and capability declarations through sync wiring the coordination hub that lets kernel , in memory , remote , and federated backends all accept the same query program language without coupling to one another');

queryExecutionCommand
  .command('register-kind')
  .description('Register an execution kind so that execute and planPushdown dispatches can route to it . Called by provider registration syncs to declare that a handler exists for this kind ( kernel , in memory , remote , federated ) .')
  .requiredOption('--kind <kind>', 'Kind')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryExecution', 'registerKind', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryExecutionCommand
  .command('register')
  .description('Register a named execution provider of a given kind with a JSON array of capability strings . The name identifies the provider and must be unique across all registered providers .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--kind <kind>', 'Kind')
  .requiredOption('--capabilities <capabilities>', 'Capabilities')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryExecution', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryExecutionCommand
  .command('execute')
  .description('Dispatch execution of a serialized query program to all registered providers of the given kind . Returns the result rows and execution metadata as JSON strings .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--kind <kind>', 'Kind')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryExecution', 'execute', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryExecutionCommand
  .command('plan-pushdown')
  .description('Decompose a query program into a pushdown portion that the named provider can execute natively and a residual portion that must run in the framework layer . Returns both as JSON strings .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--provider <provider>', 'Provider')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryExecution', 'planPushdown', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryExecutionCommand
  .command('list')
  .description('Return all registered providers as a JSON array , each entry containing the provider s name , kind , and capabilities .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryExecution', 'list', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

queryExecutionCommand
  .command('get')
  .description('Return the full details of a registered provider including its kind and capabilities as a JSON array string .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/QueryExecution', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const queryExecutionCommandTree = {
  group: 'query-execution',
  description: 'Registry and dispatcher for query execution providers that run structured query programs against a named backend . Manages named provider registrations with kind based routing and capability declarations through sync wiring the coordination hub that lets kernel , in memory , remote , and federated backends all accept the same query program language without coupling to one another',
  commands: [{ action: 'registerKind', command: 'register-kind' }, { action: 'register', command: 'register' }, { action: 'execute', command: 'execute' }, { action: 'planPushdown', command: 'plan-pushdown' }, { action: 'list', command: 'list' }, { action: 'get', command: 'get' }],
};
