// Auto-generated by Clef Clef Bind — mcp target
// Concept: DataFlowPath
// Do not edit manually; regenerate with: clef interface generate

export const dataFlowPathTools = [
  {
    "type": "tool",
    "name": "data_flow_path_trace",
    "description": "Trace dataflowpath — Find all data flow paths between a source and sink \n symbol . Results as serialized JSON array of paths .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "source": {
          "type": "string"
        },
        "sink": {
          "type": "string"
        }
      },
      "required": [
        "source",
        "sink"
      ]
    }
  },
  {
    "type": "tool",
    "name": "data_flow_path_trace_from_config",
    "description": "Trace from config dataflowpath — Trace all places a config value flows to . Results as \n serialized JSON array of paths .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "configKey": {
          "type": "string"
        }
      },
      "required": [
        "configKey"
      ]
    }
  },
  {
    "type": "tool",
    "name": "data_flow_path_trace_to_output",
    "description": "Trace to output dataflowpath — Trace all data sources that contribute to a generated \n output file . Results as serialized JSON array of paths .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "output": {
          "type": "string"
        }
      },
      "required": [
        "output"
      ]
    }
  },
  {
    "type": "resource",
    "name": "data_flow_path_get",
    "uri": "urn:clef://data-flow-paths/{path}",
    "description": "Get dataflowpath — Retrieve data flow path metadata ."
  }
];
