// Auto-generated by Clef Clef Bind — claude-skills target
// Concept: TestEntity
// Do not edit manually; regenerate with: clef interface generate

export async function handleTestEntitySkill(
  command: string,
  args: Record<string, any>,
  kernel: { handleRequest: (input: Record<string, unknown>) => Promise<any> },
): Promise<string> {
  const result = await kernel.handleRequest({ method: command, ...args });
  if (result.error) return `Error: ${result.error}`;
  return JSON.stringify(result.body, null, 2);
}

export const testEntitySkillCommands = ['register', 'get', 'findByEntity', 'findByAction', 'findByKind', 'findFailing', 'coverageReport', 'untestedActions', 'untestedInvariants', 'recordResult'];
