// Auto-generated by Clef Clef Bind — cli target
// Concept: InlineAnnotation
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const inlineAnnotationCommand = new Command('inline-annotation')
  .description('Embed change markers directly within content structure , enabling 
 accept reject review workflows where the document simultaneously 
 holds both before and after states . Content type agnostic scope 
 is opaque bytes resolved by the content system .');

inlineAnnotationCommand
  .command('annotate')
  .description('Annotation embedded in content with status pending .')
  .requiredOption('--content-ref <contentRef>', 'Content Ref')
  .requiredOption('--change-type <changeType>', 'Change Type')
  .requiredOption('--scope <scope>', 'Scope')
  .requiredOption('--author <author>', 'Author')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'annotate', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

inlineAnnotationCommand
  .command('accept')
  .description('Annotation wrapper removed . Change content kept .')
  .requiredOption('--annotation-id <annotationId>', 'Annotation Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'accept', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

inlineAnnotationCommand
  .command('reject')
  .description('Annotation wrapper and change content removed .')
  .requiredOption('--annotation-id <annotationId>', 'Annotation Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'reject', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

inlineAnnotationCommand
  .command('accept-all')
  .description('All pending annotations accepted . Count returned .')
  .requiredOption('--content-ref <contentRef>', 'Content Ref')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'acceptAll', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

inlineAnnotationCommand
  .command('reject-all')
  .description('All pending annotations rejected . Count returned .')
  .requiredOption('--content-ref <contentRef>', 'Content Ref')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'rejectAll', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

inlineAnnotationCommand
  .command('toggle-tracking')
  .description('Tracking enabled or disabled for this document .')
  .requiredOption('--content-ref <contentRef>', 'Content Ref')
  .requiredOption('--enabled <enabled>', 'Enabled')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'toggleTracking', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

inlineAnnotationCommand
  .command('list-pending')
  .description('Returns all annotations with status pending for this content .')
  .requiredOption('--content-ref <contentRef>', 'Content Ref')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'listPending', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const inlineAnnotationCommandTree = {
  group: 'inline-annotation',
  description: 'Embed change markers directly within content structure , enabling 
 accept reject review workflows where the document simultaneously 
 holds both before and after states . Content type agnostic scope 
 is opaque bytes resolved by the content system .',
  commands: [{ action: 'annotate', command: 'annotate' }, { action: 'accept', command: 'accept' }, { action: 'reject', command: 'reject' }, { action: 'acceptAll', command: 'accept-all' }, { action: 'rejectAll', command: 'reject-all' }, { action: 'toggleTracking', command: 'toggle-tracking' }, { action: 'listPending', command: 'list-pending' }],
};
