// Auto-generated by Clef Clef Bind — cli target
// Concept: DeadBranchProvider
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const deadBranchProviderCommand = new Command('dead-branch-provider')
  .description('Identify conditional branches in a StorageProgram that can never be taken given type constraints and concept state invariants . Enables FlowTrace pruning and handler optimization');

deadBranchProviderCommand
  .command('analyze')
  .description('Walk the program s branch tree and check each condition against the constraint set . Branches whose conditions are unsatisfiable under the constraints are reported as dead , along with the total and reachable branch counts .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--constraints <constraints>', 'Constraints')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DeadBranchProvider', 'analyze', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const deadBranchProviderCommandTree = {
  group: 'dead-branch-provider',
  description: 'Identify conditional branches in a StorageProgram that can never be taken given type constraints and concept state invariants . Enables FlowTrace pruning and handler optimization',
  commands: [{ action: 'analyze', command: 'analyze' }],
};
