// Auto-generated by Clef Clef Bind — cli target
// Concept: SuiteManifestEntity
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const suiteManifestEntityCommand = new Command('suite-manifest-entity')
  .description('Queryable representation of a parsed suite manifest ( suite . yaml ) the package of related concepts , syncs , type parameter alignment , dependencies , and versioning . Enables queries like what concepts are in the auth suite? , what syncs does identity depend on? , which suites compose into this app? , and cross suite dependency analysis');

suiteManifestEntityCommand
  .command('register')
  .description('Register a parsed suite manifest . Extracts concept list , sync declarations ( with tiers ) , dependencies , optional concepts , type parameter bindings , and infrastructure section from the manifest .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--manifest <manifest>', 'Manifest')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('get')
  .description('Retrieve a suite entity by name .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('list-all')
  .description('Return all registered suites with name , version , concept count , and sync count . Result as serialized JSON array .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'listAll', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('find-by-concept')
  .description('Return all suites that contain the given concept . Result as serialized JSON array .')
  .requiredOption('--concept <concept>', 'Concept')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'findByConcept', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('find-by-sync')
  .description('Return all suites that declare the given sync . Result as serialized JSON array .')
  .requiredOption('--sync <sync>', 'Sync')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'findBySync', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('concepts')
  .description('Return all concepts in this suite with their spec paths and type parameter bindings . Result as serialized JSON array of { name , spec , params } .')
  .requiredOption('--suite <suite>', 'Suite')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'concepts', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('syncs')
  .description('Return all syncs in this suite with their tiers . Result as serialized JSON array of { name , tier , spec } .')
  .requiredOption('--suite <suite>', 'Suite')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'syncs', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('dependency-graph')
  .description('Return the full suite dependency graph across all registered suites . Result as serialized JSON { nodes : [ { name , version } ] , edges : [ { from , to , constraint } ] } .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'dependencyGraph', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('transitive-dependencies')
  .description('Return all direct and transitive suite dependencies . Result as serialized JSON array of { name , version , depth , via } .')
  .requiredOption('--suite <suite>', 'Suite')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'transitiveDependencies', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('validate-dependencies')
  .description('Validate that all declared dependencies are registered and version constraints are satisfied .')
  .requiredOption('--suite <suite>', 'Suite')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'validateDependencies', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManifestEntityCommand
  .command('cross-suite-conflicts')
  .description('No conflicting concept names or type parameter mismatches across suites .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManifestEntity', 'crossSuiteConflicts', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const suiteManifestEntityCommandTree = {
  group: 'suite-manifest-entity',
  description: 'Queryable representation of a parsed suite manifest ( suite . yaml ) the package of related concepts , syncs , type parameter alignment , dependencies , and versioning . Enables queries like what concepts are in the auth suite? , what syncs does identity depend on? , which suites compose into this app? , and cross suite dependency analysis',
  commands: [{ action: 'register', command: 'register' }, { action: 'get', command: 'get' }, { action: 'listAll', command: 'list-all' }, { action: 'findByConcept', command: 'find-by-concept' }, { action: 'findBySync', command: 'find-by-sync' }, { action: 'concepts', command: 'concepts' }, { action: 'syncs', command: 'syncs' }, { action: 'dependencyGraph', command: 'dependency-graph' }, { action: 'transitiveDependencies', command: 'transitive-dependencies' }, { action: 'validateDependencies', command: 'validate-dependencies' }, { action: 'crossSuiteConflicts', command: 'cross-suite-conflicts' }],
};
