// Auto-generated by Clef Clef Bind — cli target
// Concept: InterfaceEntity
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const interfaceEntityCommand = new Command('interface-entity')
  .description('Queryable representation of a parsed interface manifest 
 ( interface . yaml ) and the API endpoints , CLI commands , MCP tools , 
 and SDK methods generated from it . Bridges concept specs and their 
 external facing interfaces enables queries like what REST
    endpoints expose User/create? , which MCP tools map to this
    concept? , show me all GraphQL mutations , and trace this API
    call back to the concept action that handles it.');

interfaceEntityCommand
  .command('register')
  .description('Register a parsed interface manifest . Extracts targets 
 ( rest , graphql , grpc , cli , mcp , claude skills ) , SDK 
 languages , concept overrides , and indexes all generated 
 endpoints commands tools .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--manifest <manifest>', 'Manifest')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'register', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('get')
  .description('Retrieve an interface entity by name .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'get', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('list-endpoints')
  .description('Return all generated endpoints for a target ( rest , graphql , 
 grpc ) . Result as serialized JSON array of { method , path , 
 concept , action , params , returnType } .')
  .requiredOption('--interface <interface>', 'Interface')
  .requiredOption('--target <target>', 'Target')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'listEndpoints', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('list-commands')
  .description('Return all generated CLI commands . Result as serialized JSON 
 array of { command , subcommand , concept , action , flags } .')
  .requiredOption('--interface <interface>', 'Interface')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'listCommands', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('list-tools')
  .description('Return all generated MCP tools . Result as serialized JSON 
 array of { name , concept , action , inputSchema , description } .')
  .requiredOption('--interface <interface>', 'Interface')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'listTools', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('list-skills')
  .description('Return all generated AI coding assistant skills . Result as 
 serialized JSON array of { name , concept , triggerDescription , 
 targetDirs } .')
  .requiredOption('--interface <interface>', 'Interface')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'listSkills', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('find-by-concept')
  .description('Return all interface exposures for a concept across all 
 registered interfaces and targets . Result as serialized JSON 
 array of { interface , target , endpoint , concept , action } .')
  .requiredOption('--concept <concept>', 'Concept')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findByConcept', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('find-by-action')
  .description('Return all interface exposures for a specific concept action . 
 Result as serialized JSON array of { interface , target , kind , 
 path , method } .')
  .requiredOption('--concept <concept>', 'Concept')
  .requiredOption('--action <action>', 'Action')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findByAction', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('trace-endpoint-to-action')
  .description('Given an API endpoint ( e . g . , POST api users ) , trace it 
 back to the concept , action , handler , and source file that 
 implements it . Full provenance chain .')
  .requiredOption('--target <target>', 'Target')
  .requiredOption('--path <path>', 'Path')
  .requiredOption('--method <method>', 'Method')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'traceEndpointToAction', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('trace-tool-to-action')
  .description('Given an MCP tool name , trace it back to the concept , 
 action , handler , and source file that implements it .')
  .requiredOption('--tool-name <toolName>', 'Tool Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'traceToolToAction', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('generated-schemas')
  .description('Return all generated API schemas ( OpenAPI , AsyncAPI , GraphQL 
 SDL , Proto ) . Result as serialized JSON array of { format , 
 file , conceptCount , endpointCount } .')
  .requiredOption('--interface <interface>', 'Interface')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'generatedSchemas', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

interfaceEntityCommand
  .command('validate-against-specs')
  .description('Validate that all concepts referenced in the interface 
 exist as ConceptEntities and all actions are declared .')
  .requiredOption('--interface <interface>', 'Interface')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'validateAgainstSpecs', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const interfaceEntityCommandTree = {
  group: 'interface-entity',
  description: 'Queryable representation of a parsed interface manifest 
 ( interface . yaml ) and the API endpoints , CLI commands , MCP tools , 
 and SDK methods generated from it . Bridges concept specs and their 
 external facing interfaces enables queries like what REST
    endpoints expose User/create? , which MCP tools map to this
    concept? , show me all GraphQL mutations , and trace this API
    call back to the concept action that handles it.',
  commands: [{ action: 'register', command: 'register' }, { action: 'get', command: 'get' }, { action: 'listEndpoints', command: 'list-endpoints' }, { action: 'listCommands', command: 'list-commands' }, { action: 'listTools', command: 'list-tools' }, { action: 'listSkills', command: 'list-skills' }, { action: 'findByConcept', command: 'find-by-concept' }, { action: 'findByAction', command: 'find-by-action' }, { action: 'traceEndpointToAction', command: 'trace-endpoint-to-action' }, { action: 'traceToolToAction', command: 'trace-tool-to-action' }, { action: 'generatedSchemas', command: 'generated-schemas' }, { action: 'validateAgainstSpecs', command: 'validate-against-specs' }],
};
