// Auto-generated by Clef Clef Bind — mcp target
// Concept: StorageProgram
// Do not edit manually; regenerate with: clef interface generate

export const storageProgramTools = [
  {
    "type": "tool",
    "name": "storage_program_create",
    "description": "Create storageprogram — Initialize an empty program ready to receive instructions .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        }
      },
      "required": [
        "program"
      ]
    }
  },
  {
    "type": "resource",
    "name": "storage_program_get",
    "uri": "urn:clef://storage-programs/{program}",
    "description": "Get storageprogram — Append a Get instruction that reads a single record by key . \n The fetched value will be bound to the bindAs name during \n interpretation ."
  },
  {
    "type": "resource",
    "name": "storage_program_find",
    "uri": "urn:clef://storage-programs/{program}",
    "description": "Find storageprogram — Append a Find instruction that queries records matching the \n criteria filter . Results are bound to bindAs during interpretation ."
  },
  {
    "type": "tool",
    "name": "storage_program_put",
    "description": "Put storageprogram — Append a Put instruction that writes a record to the given \n relation at the given key .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        },
        "relation": {
          "type": "string"
        },
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "program",
        "relation",
        "key",
        "value"
      ]
    }
  },
  {
    "type": "tool",
    "name": "storage_program_del",
    "description": "Del storageprogram — Append a Del instruction that removes a record from the given \n relation at the given key .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        },
        "relation": {
          "type": "string"
        },
        "key": {
          "type": "string"
        }
      },
      "required": [
        "program",
        "relation",
        "key"
      ]
    }
  },
  {
    "type": "tool",
    "name": "storage_program_branch",
    "description": "Branch storageprogram — Append a conditional branch whose arms are themselves \n StoragePrograms , enabling nested control flow within \n a single program tree .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        },
        "condition": {
          "type": "string"
        },
        "thenBranch": {
          "type": "string"
        },
        "elseBranch": {
          "type": "string"
        }
      },
      "required": [
        "program",
        "condition",
        "thenBranch",
        "elseBranch"
      ]
    }
  },
  {
    "type": "tool",
    "name": "storage_program_pure",
    "description": "Pure storageprogram — Terminate the program with a return value consisting of a \n variant tag and output fields . No further instructions may \n be appended after pure .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        },
        "variant": {
          "type": "string"
        },
        "output": {
          "type": "string"
        }
      },
      "required": [
        "program",
        "variant",
        "output"
      ]
    }
  },
  {
    "type": "tool",
    "name": "storage_program_compose",
    "description": "Compose storageprogram — Monadic bind : create a new program that runs first , binds its \n terminal value to bindAs , then continues with second .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "first": {
          "type": "string"
        },
        "second": {
          "type": "string"
        },
        "bindAs": {
          "type": "string"
        }
      },
      "required": [
        "first",
        "second",
        "bindAs"
      ]
    }
  },
  {
    "type": "resource",
    "name": "storage_program_get_lens",
    "uri": "urn:clef://storage-programs/{program}",
    "description": "Get lens storageprogram — Append a GetLens instruction that reads through a typed lens \n reference . The lens encodes relation , key , and field segments \n as a StateLens . The fetched value is bound to bindAs ."
  },
  {
    "type": "tool",
    "name": "storage_program_put_lens",
    "description": "Put lens storageprogram — Append a PutLens instruction that writes through a typed lens \n reference . The lens encodes the target location as a StateLens .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        },
        "lens": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "program",
        "lens",
        "value"
      ]
    }
  },
  {
    "type": "tool",
    "name": "storage_program_modify_lens",
    "description": "Modify lens storageprogram — Append a ModifyLens instruction that reads through a lens , \n applies a transformation function , and writes back through \n the same lens . This is a read modify write operation .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        },
        "lens": {
          "type": "string"
        },
        "fn": {
          "type": "string"
        }
      },
      "required": [
        "program",
        "lens",
        "fn"
      ]
    }
  }
];
