// Auto-generated by COPF Interface Kit — cli target
// Concept: ProjectScaffold
// Do not edit manually; regenerate with: copf interface generate

import { Command } from 'commander';

export const projectScaffoldCommand = new Command('project-scaffold')
  .description('Initialize new COPF projects with the standard directory 
 structure , example concept specs , and configuration files');

projectScaffoldCommand
  .command('init')
  .description('Create a new COPF project directory with specs , syncs , 
 implementations , and configuration files Generates an 
 example concept and sync to get started')
  .argument('<name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'scaffold', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const projectScaffoldCommandTree = {
  group: 'project-scaffold',
  description: 'Initialize new COPF projects with the standard directory 
 structure , example concept specs , and configuration files',
  commands: [{ action: 'scaffold', command: 'init' }],
};
