// McpServer Concept Implementation
//
// Serves the MCP protocol over stdio, auto-discovering tools
// generated by any Bind MCP target. Reads the interface manifest
// to find the MCP output directory, dynamically imports all
// generated .tools.ts files, and registers every tool/resource.
//
// Routes tool calls to the corresponding concept handlers via
// the handler registry.

import type { ConceptHandler, ConceptStorage } from '../../../runtime/types.js';

// ─── Tool registry (in-memory, populated on start) ───────

interface RegisteredTool {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  type: 'tool' | 'resource' | 'resource-template';
  // Routing info — concept + action extracted from the tool name
  concept: string;
  action: string;
}

const toolRegistry = new Map<string, RegisteredTool>();

function toPascalCase(value: string): string {
  return value
    .split(/[-_]/g)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toSnakeCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/-/g, '_')
    .toLowerCase();
}

function camelCaseFromSnake(value: string): string {
  const parts = value.split('_').filter(Boolean);
  if (parts.length === 0) return value;
  return parts[0] + parts.slice(1).map(part => part.charAt(0).toUpperCase() + part.slice(1)).join('');
}

export function inferConceptFromToolFile(toolFile: string): string {
  const path = toolFile.replace(/\\/g, '/');
  const parts = path.split('/');
  const dirName = parts[parts.length - 2] || '';
  return toPascalCase(dirName);
}

export function inferActionFromToolName(toolName: string, conceptName: string): string {
  const prefix = `${toSnakeCase(conceptName)}_`;
  if (toolName.startsWith(prefix)) {
    return camelCaseFromSnake(toolName.slice(prefix.length));
  }
  return inferAction(toolName);
}

// ─── McpServer Handler ──────────────────────────────────

export const mcpServerHandler: ConceptHandler = {

  async start(input, storage) {
    const manifestPath = input.manifestPath as string;
    const transport = input.transport as string;

    if (!transport || (transport !== 'stdio' && transport !== 'sse')) {
      return { variant: 'error', message: `Unsupported transport "${transport}". Use "stdio" or "sse".` };
    }

    try {
      // Read the interface manifest to find MCP output dir
      const fs = await import('fs');
      const path = await import('path');
      const yaml = await import('yaml');

      const manifestContent = fs.readFileSync(
        path.resolve(manifestPath),
        'utf-8',
      );
      const manifest = yaml.parse(manifestContent);
      const mcpTarget = manifest?.targets?.mcp;

      if (!mcpTarget) {
        return { variant: 'error', message: `No MCP target found in manifest: ${manifestPath}` };
      }

      const outputDir = path.resolve(
        path.dirname(manifestPath),
        mcpTarget.outputDir || './.claude/mcp',
      );

      // Discover all .tools.ts files in the output directory
      const toolFiles: string[] = [];
      function walkDir(dir: string) {
        if (!fs.existsSync(dir)) return;
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          if (entry.isDirectory()) {
            walkDir(path.join(dir, entry.name));
          } else if (entry.name.endsWith('.tools.ts')) {
            toolFiles.push(path.join(dir, entry.name));
          }
        }
      }
      walkDir(outputDir);

      // Dynamically import each tool file and register tools
      toolRegistry.clear();
      let totalTools = 0;

      for (const toolFile of toolFiles) {
        try {
          const mod = await import(`file://${toolFile.replace(/\\/g, '/')}`);
          // Each module exports a *Tools array (e.g., scoreApiTools)
          for (const exportName of Object.keys(mod)) {
            const arr = mod[exportName];
            if (!Array.isArray(arr)) continue;
            for (const entry of arr) {
              if (!entry.name) continue;
              // Only register tools (not resources/templates for now)
              const inferredConcept = inferConceptFromToolFile(toolFile);
              const tool: RegisteredTool = {
                name: entry.name,
                description: entry.description || '',
                inputSchema: entry.inputSchema || { type: 'object', properties: {}, required: [] },
                type: entry.type || 'tool',
                concept: entry.concept || inferredConcept || inferConcept(entry.name),
                action: entry.action || inferActionFromToolName(entry.name, entry.concept || inferredConcept || inferConcept(entry.name)),
              };
              toolRegistry.set(tool.name, tool);
              totalTools++;
            }
          }
        } catch (err) {
          // Skip files that fail to import
          console.error(`Warning: failed to import ${toolFile}:`, err);
        }
      }

      await storage.put('status', 'server', {
        status: 'running',
        transport,
        manifestPath,
        toolCount: totalTools,
      });

      return { variant: 'ok', status: 'running', toolCount: totalTools };
    } catch (err) {
      return {
        variant: 'error',
        message: err instanceof Error ? err.message : String(err),
      };
    }
  },

  async registerTool(input, storage) {
    const name = input.name as string;
    const concept = input.concept as string;
    const action = input.action as string;
    const description = input.description as string;
    const schema = input.schema as string;

    if (toolRegistry.has(name)) {
      return { variant: 'duplicate', name };
    }

    let inputSchema: Record<string, unknown>;
    try {
      inputSchema = JSON.parse(schema);
    } catch {
      inputSchema = { type: 'object', properties: {}, required: [] };
    }

    const tool: RegisteredTool = {
      name,
      description,
      inputSchema,
      type: 'tool',
      concept,
      action,
    };

    toolRegistry.set(name, tool);

    await storage.put('tools', `tool:${name}`, {
      toolName: name,
      toolConcept: concept,
      toolAction: action,
      toolDescription: description,
      toolSchema: schema,
    });

    return { variant: 'ok', tool: name };
  },

  async handleCall(input, _storage) {
    const toolName = input.toolName as string;
    const argsStr = input.arguments as string;

    const tool = toolRegistry.get(toolName);
    if (!tool) {
      return { variant: 'notfound', toolName };
    }

    try {
      // Parse arguments
      let args: Record<string, unknown>;
      try {
        args = JSON.parse(argsStr);
      } catch {
        args = {};
      }

      // The actual handler dispatch happens through the kernel's
      // concept transport. For the standalone MCP server, we
      // import and call handlers directly.
      return {
        variant: 'ok',
        result: JSON.stringify({
          tool: tool.name,
          concept: tool.concept,
          action: tool.action,
          args,
          note: 'Handler dispatch via kernel transport',
        }),
      };
    } catch (err) {
      return {
        variant: 'error',
        message: err instanceof Error ? err.message : String(err),
      };
    }
  },

  async stop(_input, storage) {
    toolRegistry.clear();
    await storage.put('status', 'server', { status: 'stopped' });
    return { variant: 'ok', status: 'stopped' };
  },

  async listTools(_input, _storage) {
    const tools = Array.from(toolRegistry.values()).map(t => ({
      name: t.name,
      type: t.type,
      concept: t.concept,
      action: t.action,
      description: t.description.slice(0, 120),
    }));
    return { variant: 'ok', tools: JSON.stringify(tools, null, 2) };
  },
};

// ─── Helpers ─────────────────────────────────────────────

/** Infer concept name from tool name (e.g. "score_api_list_concepts" → "ScoreApi") */
function inferConcept(toolName: string): string {
  // Tool names follow pattern: concept_name_action_name
  // Find the longest prefix that matches a known concept pattern
  const parts = toolName.split('_');
  // Try progressively longer prefixes
  for (let len = Math.min(parts.length - 1, 4); len >= 1; len--) {
    const prefix = parts.slice(0, len).join('_');
    // Convert to PascalCase
    const pascal = prefix.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase());
    return pascal;
  }
  return toolName;
}

/** Infer action name from tool name (e.g. "score_api_list_concepts" → "listConcepts") */
function inferAction(toolName: string): string {
  const parts = toolName.split('_');
  if (parts.length <= 1) return toolName;
  // Skip concept prefix (first 1-3 parts) and camelCase the rest
  // Heuristic: concept is typically 1-3 parts
  for (let skip = 1; skip <= Math.min(3, parts.length - 1); skip++) {
    const rest = parts.slice(skip);
    if (rest.length > 0) {
      return rest[0] + rest.slice(1).map(p => p[0].toUpperCase() + p.slice(1)).join('');
    }
  }
  return parts[parts.length - 1];
}

// ─── Standalone MCP server entry point ───────────────────
// This is called when the file is run directly via `npx tsx`

export async function bootMcpServer(manifestPath: string) {
  const { Server } = await import('@modelcontextprotocol/sdk/server/index.js');
  const { StdioServerTransport } = await import('@modelcontextprotocol/sdk/server/stdio.js');
  const { ListToolsRequestSchema, CallToolRequestSchema } = await import('@modelcontextprotocol/sdk/types.js');

  const fs = await import('fs');
  const path = await import('path');
  const yaml = await import('yaml');
  const { createInMemoryStorage } = await import('../../../runtime/adapters/storage.js');

  // Read manifest
  const resolved = path.resolve(manifestPath);
  const manifestContent = fs.readFileSync(resolved, 'utf-8');
  const manifest = yaml.parse(manifestContent);
  const mcpTarget = manifest?.targets?.mcp;

  if (!mcpTarget) {
    console.error(`No MCP target in manifest: ${manifestPath}`);
    process.exit(1);
  }

  // outputDir in manifest is relative to project root (cwd), not manifest file
  const outputDir = path.resolve(
    process.cwd(),
    mcpTarget.outputDir || './.claude/mcp',
  );

  // Discover tool files
  const toolFiles: string[] = [];
  function walkDir(dir: string) {
    if (!fs.existsSync(dir)) return;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walkDir(path.join(dir, entry.name));
      } else if (entry.name.endsWith('.tools.ts')) {
        toolFiles.push(path.join(dir, entry.name));
      }
    }
  }
  walkDir(outputDir);

  // Import all tools from Bind-generated files
  const allTools: RegisteredTool[] = [];
  for (const toolFile of toolFiles) {
    try {
      const mod = await import(`file://${toolFile.replace(/\\/g, '/')}`);
      for (const exportName of Object.keys(mod)) {
        const arr = mod[exportName];
        if (!Array.isArray(arr)) continue;
        for (const entry of arr) {
          if (!entry.name || entry.type !== 'tool') continue;
          const inferredConcept = inferConceptFromToolFile(toolFile);
          allTools.push({
            name: entry.name,
            description: entry.description || '',
            inputSchema: entry.inputSchema || { type: 'object', properties: {}, required: [] },
            type: 'tool',
            concept: entry.concept || inferredConcept || inferConcept(entry.name),
            action: entry.action || inferActionFromToolName(entry.name, entry.concept || inferredConcept || inferConcept(entry.name)),
          });
          toolRegistry.set(entry.name, allTools[allTools.length - 1]);
        }
      }
    } catch {
      // skip files that fail to import
    }
  }

  // Also register the ScoreQuery and ScoreNavigator tools directly
  // (these are the devtools-specific tools from our concepts)
  const devtools: Array<{ name: string; desc: string; concept: string; action: string; schema: Record<string, unknown> }> = [
    {
      name: 'score_query',
      desc: 'Run a GraphQL query against the Score index. Collections: concepts, syncs, symbols, files, handlers, widgets, themes, deployments, suites, interfaces. Example: { concepts { conceptName purpose actions } }',
      concept: 'ScoreQuery', action: 'query',
      schema: { type: 'object', properties: { graphql: { type: 'string', description: 'GraphQL query string' } }, required: ['graphql'] },
    },
    {
      name: 'score_show',
      desc: 'Show a Score entity by kind and name with all related items. Kinds: concept, sync, symbol, file, handler, widget, theme, deployment, suite, interface.',
      concept: 'ScoreNavigator', action: 'show',
      schema: { type: 'object', properties: { kind: { type: 'string' }, name: { type: 'string' } }, required: ['kind', 'name'] },
    },
    {
      name: 'score_traverse',
      desc: 'Traverse a relationship from the current Score item to a related item. Use after score_show to navigate the graph.',
      concept: 'ScoreNavigator', action: 'traverse',
      schema: { type: 'object', properties: { relation: { type: 'string', description: 'Relationship name (actions, syncs, stateFields, triggers, effects, concepts, handler, suites)' }, target: { type: 'string', description: 'Name of the target item' } }, required: ['relation', 'target'] },
    },
    {
      name: 'score_back',
      desc: 'Go back to the previous Score item in the traversal history.',
      concept: 'ScoreNavigator', action: 'back',
      schema: { type: 'object', properties: {}, required: [] },
    },
    {
      name: 'score_list',
      desc: 'List all Score entities of a given kind. Kinds: concept, sync, symbol, file, handler, widget, theme, deployment, suite, interface.',
      concept: 'ScoreNavigator', action: 'list',
      schema: { type: 'object', properties: { kind: { type: 'string' } }, required: ['kind'] },
    },
  ];

  for (const dt of devtools) {
    const tool: RegisteredTool = {
      name: dt.name,
      description: dt.desc,
      inputSchema: dt.schema,
      type: 'tool',
      concept: dt.concept,
      action: dt.action,
    };
    allTools.push(tool);
    toolRegistry.set(tool.name, tool);
  }

  // Start Score seeding in the background so initialize can complete quickly.
  const sharedStorage = createInMemoryStorage();
  const conceptsNeedingScoreSeed = new Set(['ScoreApi', 'ScoreIndex', 'ScoreNavigator', 'ScoreQuery']);
  const scoreSeedPromise = seedScoreIndex(sharedStorage).catch((err) => {
    console.error('Failed to seed Score index for MCP server:', err);
    throw err;
  });

  // Create MCP server
  const server = new Server(
    { name: mcpTarget.name || 'clef-devtools', version: manifest.interface?.version || '0.1.0' },
    { capabilities: { tools: {} } },
  );

  // Handle tools/list
  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: allTools.map(t => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
  }));

  // Handle tools/call — route to concept handlers
  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const toolName = request.params.name;
    const args = (request.params.arguments || {}) as Record<string, unknown>;

    const tool = toolRegistry.get(toolName);
    if (!tool) {
      return {
        content: [{ type: 'text' as const, text: `Unknown tool: ${toolName}` }],
        isError: true,
      };
    }

    try {
      if (conceptsNeedingScoreSeed.has(tool.concept)) {
        await scoreSeedPromise;
      }

      const handler = await resolveHandler(tool.concept);
      if (!handler) {
        return {
          content: [{ type: 'text' as const, text: `No handler for concept: ${tool.concept}` }],
          isError: true,
        };
      }

      // Use shared storage so ScoreNavigator cursor persists across calls
      const result = await handler[tool.action](args, sharedStorage);
      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
      };
    } catch (err) {
      return {
        content: [{ type: 'text' as const, text: `Error: ${err instanceof Error ? err.message : String(err)}` }],
        isError: true,
      };
    }
  });

  // Connect via stdio
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

/** Seed the shared storage with Score index data from the project */
export async function seedScoreIndex(storage: ConceptStorage) {
  const fs = await import('fs');
  const path = await import('path');
  const { scoreIndexHandler } = await import('../score/score-index.handler.js');
  const cwd = process.cwd();
  const sourceDirs = ['bind', 'cli', 'examples', 'handlers', 'repertoire', 'runtime', 'score', 'specs', 'surface', 'syncs', 'tests'];
  const excludedDirs = new Set(['.git', 'node_modules', 'dist', 'coverage', '.claude', '.codex', 'generated']);

  async function indexFile(absPath: string) {
    const relPath = path.relative(cwd, absPath).replace(/\\/g, '/');
    const content = fs.readFileSync(absPath, 'utf-8');
    const definitions = extractDefinitions(relPath, content);
    await scoreIndexHandler.upsertFile({
      path: relPath,
      language: inferLanguageFromPath(relPath),
      role: inferRoleFromPath(relPath),
      definitions,
    }, storage);

    for (const symbol of extractSymbols(relPath, content)) {
      await scoreIndexHandler.upsertSymbol(symbol, storage);
    }

    if (relPath.endsWith('.concept')) {
      const name = extractConceptName(content) || path.basename(relPath, '.concept');
      await scoreIndexHandler.upsertConcept({
        name,
        purpose: extractPurpose(content),
        actions: extractActions(content),
        stateFields: extractStateFields(content),
        file: relPath,
      }, storage);
      return;
    }

    if (relPath.endsWith('.sync')) {
      for (const s of extractSyncs(content)) {
        await scoreIndexHandler.upsertSync({
          name: s.name,
          annotation: s.annotation,
          triggers: s.triggers,
          effects: s.effects,
          file: relPath,
        }, storage);
      }
      return;
    }

    if (relPath.endsWith('.handler.ts')) {
      const concept = path.basename(relPath, '.handler.ts')
        .replace(/(^|-)(\w)/g, (_: string, __: string, c: string) => c.toUpperCase());
      const actions = extractHandlerActions(content);
      const lines = content.split('\n').length;
      await storage.put('handlers', `handler:${concept}:typescript`, {
        handlerConcept: concept,
        handlerLanguage: 'typescript',
        handlerFile: relPath,
        handlerActions: actions,
        handlerLineCount: lines,
      });
    }
  }

  async function walkDir(dir: string): Promise<void> {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isSymbolicLink()) continue;
      if (entry.isDirectory()) {
        if (excludedDirs.has(entry.name)) continue;
        await walkDir(path.join(dir, entry.name));
        continue;
      }
      await indexFile(path.join(dir, entry.name));
    }
  }

  for (const dir of sourceDirs) {
    const fullDir = path.join(cwd, dir);
    if (!fs.existsSync(fullDir)) continue;
    await walkDir(fullDir);
  }

  const suiteDirs = ['suites', 'repertoire/concepts', 'bind/interface', 'score/semantic', 'score/analysis', 'score/parse', 'score/discovery', 'score/auto'];
  for (const dir of suiteDirs) {
    const fullDir = path.join(cwd, dir);
    if (!fs.existsSync(fullDir)) continue;
    for (const yamlPath of findFilesNamed(fullDir, 'suite.yaml', fs, path)) {
      try {
        const yaml = await import('yaml');
        const suiteContent = yaml.parse(fs.readFileSync(yamlPath, 'utf-8'));
        const relPath = path.relative(cwd, yamlPath).replace(/\\/g, '/');
        const fallbackName = path.basename(path.dirname(yamlPath));
        const conceptMap = suiteContent?.concepts || {};
        const syncSection = suiteContent?.syncs || {};
        const conceptNames = Array.isArray(conceptMap)
          ? conceptMap
          : Object.keys(conceptMap);
        const suiteSyncs = Array.isArray(syncSection)
          ? syncSection
          : [
            ...(syncSection.required || []),
            ...(syncSection.recommended || []),
          ];

        await storage.put('suiteManifests', `suite:${suiteContent?.suite?.name || fallbackName}`, {
          suiteName: suiteContent?.suite?.name || fallbackName,
          suiteVersion: suiteContent?.suite?.version || '0.0.0',
          suiteConcepts: conceptNames,
          suiteSyncs,
          suiteFile: relPath,
        });
      } catch {
        // skip malformed suite files
      }
    }
  }
}

// ─── Lightweight spec extractors (no full parser dependency) ─

function extractConceptName(content: string): string | null {
  const match = content.match(/concept\s+(\w+)/);
  return match ? match[1] : null;
}

function extractPurpose(content: string): string {
  const match = content.match(/purpose\s*\{([^}]*)\}/s);
  return match ? match[1].trim().replace(/\s+/g, ' ') : '';
}

function extractActions(content: string): string[] {
  const actions: string[] = [];
  const re = /action\s+(\w+)\s*\(/g;
  let m;
  while ((m = re.exec(content)) !== null) {
    actions.push(m[1]);
  }
  return actions;
}

function extractStateFields(content: string): string[] {
  const stateMatch = content.match(/state\s*\{([\s\S]*?)\n\s*\}/);
  if (!stateMatch) return [];
  const fields: string[] = [];
  const re = /(\w+)\s*:/g;
  let m;
  while ((m = re.exec(stateMatch[1])) !== null) {
    fields.push(m[1]);
  }
  return fields;
}

function extractSyncs(content: string): Array<{ name: string; annotation: string; triggers: string[]; effects: string[] }> {
  const syncs: Array<{ name: string; annotation: string; triggers: string[]; effects: string[] }> = [];
  const syncBlocks = content.split(/(?=^sync\s)/m);
  for (const block of syncBlocks) {
    const nameMatch = block.match(/^sync\s+(\w+)\s*(?:\[(\w+)\])?/);
    if (!nameMatch) continue;
    const triggers: string[] = [];
    const effects: string[] = [];
    // Extract when patterns: Concept/action
    const whenMatch = block.match(/when\s*\{([\s\S]*?)\}/);
    if (whenMatch) {
      const re = /(\w+)\/(\w+)/g;
      let m;
      while ((m = re.exec(whenMatch[1])) !== null) {
        triggers.push(`${m[1]}/${m[2]}`);
      }
    }
    // Extract then actions: Concept/action
    const thenMatch = block.match(/then\s*\{([\s\S]*?)\}/);
    if (thenMatch) {
      const re = /(\w+)\/(\w+)/g;
      let m;
      while ((m = re.exec(thenMatch[1])) !== null) {
        effects.push(`${m[1]}/${m[2]}`);
      }
    }
    syncs.push({ name: nameMatch[1], annotation: nameMatch[2] || 'eager', triggers, effects });
  }
  return syncs;
}

function extractHandlerActions(content: string): string[] {
  const actions: string[] = [];
  const re = /async\s+(\w+)\s*\(\s*input/g;
  let m;
  while ((m = re.exec(content)) !== null) {
    actions.push(m[1]);
  }
  return actions;
}

function inferLanguageFromPath(filePath: string): string {
  const ext = filePath.split('.').pop()?.toLowerCase() || '';
  const langMap: Record<string, string> = {
    ts: 'typescript', tsx: 'typescript', js: 'javascript', jsx: 'javascript',
    concept: 'concept-spec', sync: 'sync-spec', yaml: 'yaml', yml: 'yaml',
    json: 'json', md: 'markdown', widget: 'widget-spec', theme: 'theme-spec', derived: 'derived-spec',
  };
  return langMap[ext] || ext || 'unknown';
}

function inferRoleFromPath(filePath: string): string {
  const normalized = filePath.replace(/\\/g, '/');
  if (normalized.includes('/generated/') || normalized.startsWith('generated/')) return 'generated';
  if (normalized.includes('/tests/') || normalized.endsWith('.test.ts')) return 'test';
  if (/\.(concept|sync|widget|theme|derived)$/.test(normalized)) return 'spec';
  if (/\.(yaml|yml|json)$/.test(normalized)) return 'config';
  if (normalized.endsWith('.md')) return 'doc';
  return 'source';
}

function lineNumberAt(content: string, offset: number): number {
  return content.slice(0, offset).split('\n').length;
}

function extractDefinitions(filePath: string, content: string): string[] {
  if (filePath.endsWith('.concept')) {
    return [extractConceptName(content), ...extractActions(content)].filter((value): value is string => Boolean(value));
  }
  if (filePath.endsWith('.sync')) {
    return extractSyncs(content).map(sync => sync.name);
  }
  const definitions: string[] = [];
  const regexes = [
    /export\s+(?:async\s+)?function\s+(\w+)/g,
    /export\s+const\s+(\w+)/g,
    /export\s+class\s+(\w+)/g,
    /export\s+interface\s+(\w+)/g,
    /export\s+type\s+(\w+)/g,
  ];
  for (const regex of regexes) {
    let match;
    while ((match = regex.exec(content)) !== null) {
      definitions.push(match[1]);
    }
  }
  return Array.from(new Set(definitions));
}

function extractSymbols(filePath: string, content: string): Array<{ name: string; kind: string; file: string; line: number; scope: string }> {
  const symbols: Array<{ name: string; kind: string; file: string; line: number; scope: string }> = [];

  if (filePath.endsWith('.concept')) {
    const conceptName = extractConceptName(content);
    if (conceptName) {
      const conceptMatch = content.match(/concept\s+(\w+)/);
      symbols.push({
        name: conceptName,
        kind: 'concept',
        file: filePath,
        line: conceptMatch ? lineNumberAt(content, conceptMatch.index || 0) : 1,
        scope: 'module',
      });
    }
    const actionRegex = /action\s+(\w+)\s*\(/g;
    let match;
    while ((match = actionRegex.exec(content)) !== null) {
      symbols.push({
        name: match[1],
        kind: 'action',
        file: filePath,
        line: lineNumberAt(content, match.index),
        scope: conceptName || 'module',
      });
    }
    return symbols;
  }

  if (filePath.endsWith('.sync')) {
    for (const sync of extractSyncs(content)) {
      const match = content.match(new RegExp(`^sync\\s+${sync.name}\\b`, 'm'));
      symbols.push({
        name: sync.name,
        kind: 'sync',
        file: filePath,
        line: match ? lineNumberAt(content, match.index || 0) : 1,
        scope: 'module',
      });
    }
    return symbols;
  }

  const patterns: Array<{ regex: RegExp; kind: string }> = [
    { regex: /export\s+(?:async\s+)?function\s+(\w+)/g, kind: 'function' },
    { regex: /export\s+const\s+(\w+)/g, kind: 'variable' },
    { regex: /export\s+class\s+(\w+)/g, kind: 'class' },
    { regex: /export\s+interface\s+(\w+)/g, kind: 'type' },
    { regex: /export\s+type\s+(\w+)/g, kind: 'type' },
  ];

  for (const pattern of patterns) {
    let match;
    while ((match = pattern.regex.exec(content)) !== null) {
      symbols.push({
        name: match[1],
        kind: pattern.kind,
        file: filePath,
        line: lineNumberAt(content, match.index),
        scope: 'module',
      });
    }
  }

  return symbols;
}

function findFilesNamed(rootDir: string, fileName: string, fs: typeof import('fs'), path: typeof import('path')): string[] {
  const matches: string[] = [];
  function walk(dir: string) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isSymbolicLink()) continue;
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.name === fileName) {
        matches.push(fullPath);
      }
    }
  }
  walk(rootDir);
  return matches;
}

/** Resolve a concept name to its handler module */
async function resolveHandler(conceptName: string): Promise<ConceptHandler | null> {
  // Map concept names to handler file paths
  const kebab = conceptName.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  // Try multiple locations
  const candidates = [
    `../../../handlers/ts/framework/${kebab}.handler.js`,
    `../../../handlers/ts/score/${kebab}.handler.js`,
    `../../../handlers/ts/app/${kebab}.handler.js`,
    `../../../handlers/ts/framework/providers/${kebab}.handler.js`,
  ];

  for (const candidate of candidates) {
    try {
      const mod = await import(candidate);
      // Find the handler export (e.g., scoreApiHandler, scoreQueryHandler)
      for (const key of Object.keys(mod)) {
        if (key.endsWith('Handler') && typeof mod[key] === 'object') {
          return mod[key] as ConceptHandler;
        }
      }
    } catch {
      // try next candidate
    }
  }

  return null;
}
