// Auto-generated by Clef Clef Bind — mcp target
// Concept: ScoreIndex
// Do not edit manually; regenerate with: clef interface generate

export const scoreIndexTools = [
  {
    "type": "tool",
    "name": "score_index_upsert_concept",
    "description": "Upsert concept scoreindex — Insert or update a concept entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "purpose": {
          "type": "string"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "stateFields": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "purpose",
        "actions",
        "stateFields",
        "file"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_sync",
    "description": "Upsert sync scoreindex — Insert or update a sync entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "annotation": {
          "type": "string"
        },
        "triggers": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "effects": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "annotation",
        "triggers",
        "effects",
        "file"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_symbol",
    "description": "Upsert symbol scoreindex — Insert or update a symbol entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "file": {
          "type": "string"
        },
        "line": {
          "type": "integer"
        },
        "scope": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "kind",
        "file",
        "line",
        "scope"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_file",
    "description": "Upsert file scoreindex — Insert or update a file entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "definitions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "path",
        "language",
        "role",
        "definitions"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_handler",
    "description": "Upsert handler scoreindex — Insert or update a handler entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "concept": {
          "type": "string"
        },
        "language": {
          "type": "string"
        },
        "file": {
          "type": "string"
        },
        "actions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "lineCount": {
          "type": "integer"
        }
      },
      "required": [
        "concept",
        "language",
        "file",
        "actions",
        "lineCount"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_widget_impl",
    "description": "Upsert widget impl scoreindex — Insert or update a widget implementation entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "widget": {
          "type": "string"
        },
        "framework": {
          "type": "string"
        },
        "file": {
          "type": "string"
        },
        "component": {
          "type": "string"
        }
      },
      "required": [
        "widget",
        "framework",
        "file",
        "component"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_theme_impl",
    "description": "Upsert theme impl scoreindex — Insert or update a theme implementation entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "theme": {
          "type": "string"
        },
        "platform": {
          "type": "string"
        },
        "file": {
          "type": "string"
        },
        "tokenCount": {
          "type": "integer"
        }
      },
      "required": [
        "theme",
        "platform",
        "file",
        "tokenCount"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_deployment",
    "description": "Upsert deployment scoreindex — Insert or update a deployment entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "app": {
          "type": "string"
        },
        "runtimes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "app",
        "runtimes",
        "file"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_suite_manifest",
    "description": "Upsert suite manifest scoreindex — Insert or update a suite manifest entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "concepts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "syncs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "file": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "version",
        "concepts",
        "syncs",
        "file"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_upsert_interface",
    "description": "Upsert interface scoreindex — Insert or update an interface entry in the index .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "targets": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "endpointCount": {
          "type": "integer"
        },
        "file": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "targets",
        "endpointCount",
        "file"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_remove_by_file",
    "description": "Remove by file scoreindex — Remove all index entries associated with a file .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        }
      },
      "required": [
        "path"
      ]
    }
  },
  {
    "type": "tool",
    "name": "score_index_clear",
    "description": "Clear scoreindex — Clear all index entries . Used before a full reindex .",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "type": "tool",
    "name": "score_index_stats",
    "description": "Stats scoreindex — Return current index statistics .",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  }
];
