// Auto-generated by Clef Clef Bind — cli target
// Concept: PessimisticLock
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const pessimisticLockCommand = new Command('pessimistic-lock')
  .description('Prevent conflicts by granting exclusive write access to a resource , serializing edits rather than reconciling them after the fact . Complementary to ConflictResolution use locking for non mergeable content ( binary files , legal documents ) and resolution for mergeable content ( text , structured data ) . checkOut may complete after an arbitrarily long wait if the resource is locked and the requester is queued');

pessimisticLockCommand
  .command('check-out')
  .description('Exclusive lock granted to holder .')
  .requiredOption('--resource <resource>', 'Resource')
  .requiredOption('--holder <holder>', 'Holder')
  .requiredOption('--duration <duration>', 'Duration')
  .requiredOption('--reason <reason>', 'Reason')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/PessimisticLock', 'checkOut', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

pessimisticLockCommand
  .command('check-in')
  .description('Lock released . Next requester in queue is notified .')
  .requiredOption('--lock-id <lockId>', 'Lock Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/PessimisticLock', 'checkIn', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

pessimisticLockCommand
  .command('break-lock')
  .description('Lock forcibly released . Reason is mandatory and recorded .')
  .requiredOption('--lock-id <lockId>', 'Lock Id')
  .requiredOption('--breaker <breaker>', 'Breaker')
  .requiredOption('--reason <reason>', 'Reason')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/PessimisticLock', 'breakLock', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

pessimisticLockCommand
  .command('renew')
  .description('Lock expiry extended by the additional duration .')
  .requiredOption('--lock-id <lockId>', 'Lock Id')
  .requiredOption('--additional-duration <additionalDuration>', 'Additional Duration')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/PessimisticLock', 'renew', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

pessimisticLockCommand
  .command('query-locks')
  .description('All active locks , optionally filtered to a specific resource .')
  .requiredOption('--resource <resource>', 'Resource')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/PessimisticLock', 'queryLocks', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

pessimisticLockCommand
  .command('query-queue')
  .description('Wait queue for the resource .')
  .requiredOption('--resource <resource>', 'Resource')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/PessimisticLock', 'queryQueue', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const pessimisticLockCommandTree = {
  group: 'pessimistic-lock',
  description: 'Prevent conflicts by granting exclusive write access to a resource , serializing edits rather than reconciling them after the fact . Complementary to ConflictResolution use locking for non mergeable content ( binary files , legal documents ) and resolution for mergeable content ( text , structured data ) . checkOut may complete after an arbitrarily long wait if the resource is locked and the requester is queued',
  commands: [{ action: 'checkOut', command: 'check-out' }, { action: 'checkIn', command: 'check-in' }, { action: 'breakLock', command: 'break-lock' }, { action: 'renew', command: 'renew' }, { action: 'queryLocks', command: 'query-locks' }, { action: 'queryQueue', command: 'query-queue' }],
};
