// Auto-generated by COPF Interface Kit — cli target
// Concept: KitManager
// Do not edit manually; regenerate with: copf interface generate

import { Command } from 'commander';

export const kitManagerCommand = new Command('kit-manager')
  .description('Manage concept kits scaffold new kits , validate kit 
 manifests and cross kit references , run kit tests , list 
 active kits , and check app overrides');

kitManagerCommand
  .command('init')
  .description('Scaffold a new kit directory with kit yaml , concept 
 and sync subdirectories , and example files')
  .argument('<name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'init', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

kitManagerCommand
  .command('validate')
  .description('Validate a kit manifest , its concept specs , sync 
 definitions , and cross kit concept references')
  .argument('<path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'validate', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

kitManagerCommand
  .command('test')
  .description('Run conformance and integration tests for a kit 
 Tests invariants from concept specs and validates 
 sync compilation')
  .argument('<path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'test', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

kitManagerCommand
  .command('list')
  .description('List all kits used by the current application , 
 including their versions and concept counts')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'list', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

kitManagerCommand
  .command('check-overrides')
  .description('Verify that application sync overrides reference 
 valid syncs in the target kit')
  .requiredOption('--path <path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'checkOverrides', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const kitManagerCommandTree = {
  group: 'kit-manager',
  description: 'Manage concept kits scaffold new kits , validate kit 
 manifests and cross kit references , run kit tests , list 
 active kits , and check app overrides',
  commands: [{ action: 'init', command: 'init' }, { action: 'validate', command: 'validate' }, { action: 'test', command: 'test' }, { action: 'list', command: 'list' }, { action: 'checkOverrides', command: 'check-overrides' }],
};
