// Auto-generated by Clef Clef Bind — cli target
// Concept: ApiSurface
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const apiSurfaceCommand = new Command('api-surface')
  .description('Compose generated interfaces from multiple concepts into a cohesive , unified API surface per target . For REST : a single router with concept namespaced routes . For GraphQL : a merged schema with shared types . For CLI : a command tree with concept subcommands . For MCP : a combined tool set . For SDKs : a single client with concept namespaced methods . Renamed from Surface to avoid collision with concept interface suites surface render surface . concept ( runtime rendering target for DOM , terminal , etc . )');

apiSurfaceCommand
  .command('compose')
  .description('Merge per concept generated outputs into a unified surface . Create shared entrypoint ( router , schema , command root , etc . ) . Deduplicate shared types . Apply suite level middleware .')
  .requiredOption('--suite <suite>', 'Suite')
  .requiredOption('--target <target>', 'Target')
  .requiredOption('--outputs <outputs>', 'Outputs')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ApiSurface', 'compose', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

apiSurfaceCommand
  .command('entrypoint')
  .description('Return the composed entrypoint file content .')
  .requiredOption('--surface <surface>', 'Surface')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ApiSurface', 'entrypoint', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const apiSurfaceCommandTree = {
  group: 'api-surface',
  description: 'Compose generated interfaces from multiple concepts into a cohesive , unified API surface per target . For REST : a single router with concept namespaced routes . For GraphQL : a merged schema with shared types . For CLI : a command tree with concept subcommands . For MCP : a combined tool set . For SDKs : a single client with concept namespaced methods . Renamed from Surface to avoid collision with concept interface suites surface render surface . concept ( runtime rendering target for DOM , terminal , etc . )',
  commands: [{ action: 'compose', command: 'compose' }, { action: 'entrypoint', command: 'entrypoint' }],
};
