// Auto-generated by Clef Clef Bind — mcp target
// Concept: IntegrationTestGen
// Do not edit manually; regenerate with: clef interface generate

export const integrationTestGenTools = [
  {
    "type": "tool",
    "name": "integration_test_gen_generate",
    "description": "Generate integrationtestgen — ProcessSpec JSON emitted with one step per fixture , steps ordered by \n after chain dependencies , and CheckVerification assertions for all \n annotated variants . The generation is stored for later retrieval .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "conceptSpec": {
          "type": "string"
        },
        "ingestManifest": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "required": [
        "conceptSpec",
        "ingestManifest",
        "source"
      ]
    }
  },
  {
    "type": "tool",
    "name": "integration_test_gen_run",
    "description": "Run integrationtestgen — All steps executed ( regardless of individual pass fail ) . The results \n JSON contains per step outcome records including actual variant , \n expected variant , and CheckVerification verdict . passed and failed \n are the aggregate totals .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "processSpec": {
          "type": "string"
        }
      },
      "required": [
        "processSpec"
      ]
    }
  },
  {
    "type": "tool",
    "name": "integration_test_gen_preview",
    "description": "Preview integrationtestgen — Steps JSON array computed from fixtures and their after chain ordering . \n No persistent state is written .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "conceptSpec": {
          "type": "string"
        },
        "source": {
          "type": "string"
        }
      },
      "required": [
        "conceptSpec",
        "source"
      ]
    }
  },
  {
    "type": "resource-template",
    "name": "integration_test_gen_list",
    "uriTemplate": "urn:clef://integration-test-gens",
    "description": "List integrationtestgen — Return all stored generation records ordered by generatedAt descending . \n Each record includes the concept name , source path , step count , and \n generation timestamp ."
  },
  {
    "type": "tool",
    "name": "integration_test_gen_register",
    "description": "Register integrationtestgen — Return static metadata for PluginRegistry . \n name : IntegrationTestGen \n inputKind : ConceptSpec \n outputKind : ProcessSpec \n capabilities : [ fixture-walk , after-chain , check-verification , external-call ]",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  }
];
