// Auto-generated by Clef Clef Bind — mcp target
// Concept: StateField
// Do not edit manually; regenerate with: clef interface generate

export const stateFieldTools = [
  {
    "type": "tool",
    "name": "state_field_register",
    "description": "Register statefield — Register a state field extracted from a concept spec . \n Cardinality is inferred from the type expression \n ( set , mapping , list , option , scalar ) .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "concept": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "typeExpr": {
          "type": "string"
        }
      },
      "required": [
        "concept",
        "name",
        "typeExpr"
      ]
    }
  },
  {
    "type": "resource",
    "name": "state_field_find_by_concept",
    "uri": "urn:clef://state-fields/{concept}",
    "description": "Find by concept statefield — Return all state fields for a given concept . \n Results as serialized JSON array ."
  },
  {
    "type": "tool",
    "name": "state_field_trace_to_generated",
    "description": "Trace to generated statefield — Trace this field to its generated code representations \n across target languages . Results as serialized JSON array \n of { language , symbol , file } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "field": {
          "type": "string"
        }
      },
      "required": [
        "field"
      ]
    }
  },
  {
    "type": "tool",
    "name": "state_field_trace_to_storage",
    "description": "Trace to storage statefield — Trace this field to its storage representation \n database columns , document keys , etc . Results as \n serialized JSON array of { adapter , columnOrKey } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "field": {
          "type": "string"
        }
      },
      "required": [
        "field"
      ]
    }
  },
  {
    "type": "resource",
    "name": "state_field_get",
    "uri": "urn:clef://state-fields/{field}",
    "description": "Get statefield — Retrieve state field metadata ."
  }
];
