// Auto-generated by Clef Clef Bind — cli target
// Concept: ThemeImplementationEntity
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const themeImplementationEntityCommand = new Command('theme-implementation-entity')
  .description('Queryable representation of a generated theme implementation file 
 CSS custom properties , React Native StyleSheet , Design Token Community 
 Group JSON , or other platform specific output generated from a . theme 
 spec . Links the generated output back to its ThemeEntity source , 
 tracks the full AST token tree , and enables token resolution tracing 
 from component styling back to theme spec declarations .');

themeImplementationEntityCommand
  .command('register')
  .description('Register a generated theme implementation . Parses the source 
 to extract token paths , resolved values , and platform specific 
 structure . The theme field links to the ThemeEntity this 
 implements . Platform is one of : css , react native , dtcg json , 
 scss , tailwind , android xml , ios swift .')
  .requiredOption('--theme <theme>', 'Theme')
  .requiredOption('--platform <platform>', 'Platform')
  .requiredOption('--source-file <sourceFile>', 'Source File')
  .requiredOption('--ast <ast>', 'Ast')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'register', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

themeImplementationEntityCommand
  .command('get')
  .description('Retrieve a theme implementation by theme name and platform .')
  .requiredOption('--theme <theme>', 'Theme')
  .requiredOption('--platform <platform>', 'Platform')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'get', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

themeImplementationEntityCommand
  .command('get-by-file')
  .description('Retrieve a theme implementation by its source file path .')
  .requiredOption('--source-file <sourceFile>', 'Source File')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'getByFile', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

themeImplementationEntityCommand
  .command('find-by-theme')
  .description('Return all implementations for a theme across platforms . 
 Results as serialized JSON array .')
  .requiredOption('--theme <theme>', 'Theme')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findByTheme', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

themeImplementationEntityCommand
  .command('find-by-platform')
  .description('Return all theme implementations for a given platform . 
 Results as serialized JSON array .')
  .requiredOption('--platform <platform>', 'Platform')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findByPlatform', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

themeImplementationEntityCommand
  .command('resolve-token')
  .description('Resolve a token path in the generated output back to its 
 theme spec declaration and show the platform specific syntax . 
 E . g . , CSS : var ( color primary -500 ) -> spec : palette . primary')
  .requiredOption('--impl <impl>', 'Impl')
  .requiredOption('--token-path <tokenPath>', 'Token Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'resolveToken', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

themeImplementationEntityCommand
  .command('diff-from-spec')
  .description('Compare the generated implementation against its theme spec 
 to find drift missing tokens , stale values , etc . 
 Result as serialized JSON array of { token , specValue , implValue } .')
  .requiredOption('--impl <impl>', 'Impl')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'diffFromSpec', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const themeImplementationEntityCommandTree = {
  group: 'theme-implementation-entity',
  description: 'Queryable representation of a generated theme implementation file 
 CSS custom properties , React Native StyleSheet , Design Token Community 
 Group JSON , or other platform specific output generated from a . theme 
 spec . Links the generated output back to its ThemeEntity source , 
 tracks the full AST token tree , and enables token resolution tracing 
 from component styling back to theme spec declarations .',
  commands: [{ action: 'register', command: 'register' }, { action: 'get', command: 'get' }, { action: 'getByFile', command: 'get-by-file' }, { action: 'findByTheme', command: 'find-by-theme' }, { action: 'findByPlatform', command: 'find-by-platform' }, { action: 'resolveToken', command: 'resolve-token' }, { action: 'diffFromSpec', command: 'diff-from-spec' }],
};
