// Auto-generated by COPF Interface Kit — cli target
// Concept: Emitter
// Do not edit manually; regenerate with: copf interface generate

import { Command } from 'commander';

export const emitterCommand = new Command('emitter')
  .description('Manage generated file output, traceability, and drift detection.');

emitterCommand
  .command('write')
  .description('Write a single generated file')
  .argument('<path>', 'Path')
  .requiredOption('--content <content>', 'File content to write')
  .option('-f, --format-hint <formatHint>', 'Formatter to apply (e.g., prettier, rustfmt)')
  .requiredOption('--sources <sources>', 'Sources')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'write', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

emitterCommand
  .command('write-batch')
  .description('Atomically write a batch of generated files')
  .requiredOption('--files <files>', 'Files')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'writeBatch', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

emitterCommand
  .command('format')
  .description('Format a generated file')
  .argument('<path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'format', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

emitterCommand
  .command('clean')
  .description('Remove orphaned generated files')
  .argument('<outputDir>', 'Output Dir')
  .option('--current-manifest <currentManifest>', 'Path to current manifest listing expected files')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf emitter clean ./generated  # Clean generated directory')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'clean', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

emitterCommand
  .command('manifest')
  .description('List all tracked output files')
  .argument('<outputDir>', 'Output Dir')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf emitter manifest ./generated  # List outputs in generated/')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'manifest', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

emitterCommand
  .command('trace')
  .description('Show which sources produced an output file')
  .argument('<outputPath>', 'Output Path')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf emitter trace ./generated/user.types.ts  # Trace provenance of a generated file')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'trace', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

emitterCommand
  .command('affected')
  .description('Show what outputs change if a source changes')
  .argument('<sourcePath>', 'Source Path')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf emitter affected ./specs/app/user.concept  # Impact analysis for a concept spec')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'affected', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

emitterCommand
  .command('audit')
  .description('Check generated files for drift from expected output')
  .argument('<outputDir>', 'Output Dir')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  copf emitter audit ./generated  # Audit generated directory')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'audit', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const emitterCommandTree = {
  group: 'emitter',
  description: 'Manage generated file output, traceability, and drift detection.',
  commands: [{ action: 'write', command: 'write' }, { action: 'writeBatch', command: 'write-batch' }, { action: 'format', command: 'format' }, { action: 'clean', command: 'clean' }, { action: 'manifest', command: 'manifest' }, { action: 'trace', command: 'trace' }, { action: 'affected', command: 'affected' }, { action: 'audit', command: 'audit' }],
};
