// Auto-generated by Clef Clef Bind — cli target
// Concept: DerivedEntity
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const derivedEntityCommand = new Command('derived-entity')
  .description('Queryable representation of a parsed derived concept a named composition of base concepts and syncs . Enables trace rollup by linking derivedContext tags to the composition hierarchy , and powers queries like what concepts does this derived concept compose? and what syncs wire it together?');

derivedEntityCommand
  .command('register')
  .description('Register a parsed derived concept as a semantic entity . Extracts composition hierarchy , claimed syncs , surface actions queries , and operational principle from the DerivedAST .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--ast <ast>', 'Ast')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DerivedEntity', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

derivedEntityCommand
  .command('get')
  .description('Retrieve a derived entity by name .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DerivedEntity', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

derivedEntityCommand
  .command('find-by-composed-concept')
  .description('Return all derived concepts that compose the given concept . Results as serialized JSON array .')
  .requiredOption('--concept <concept>', 'Concept')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DerivedEntity', 'findByComposedConcept', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

derivedEntityCommand
  .command('find-by-sync')
  .description('Return all derived concepts that claim the given sync . Results as serialized JSON array .')
  .requiredOption('--sync-name <syncName>', 'Sync Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DerivedEntity', 'findBySync', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

derivedEntityCommand
  .command('composition-tree')
  .description('Build the full composition hierarchy , resolving nested derived concepts into a tree . Returns serialized JSON .')
  .requiredOption('--entity <entity>', 'Entity')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DerivedEntity', 'compositionTree', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

derivedEntityCommand
  .command('trace-rollup')
  .description('Roll up a flow trace by grouping sync firings under the derived concept s claimed syncs , producing a summary view . Returns serialized JSON .')
  .requiredOption('--entity <entity>', 'Entity')
  .requiredOption('--flow-id <flowId>', 'Flow Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DerivedEntity', 'traceRollup', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const derivedEntityCommandTree = {
  group: 'derived-entity',
  description: 'Queryable representation of a parsed derived concept a named composition of base concepts and syncs . Enables trace rollup by linking derivedContext tags to the composition hierarchy , and powers queries like what concepts does this derived concept compose? and what syncs wire it together?',
  commands: [{ action: 'register', command: 'register' }, { action: 'get', command: 'get' }, { action: 'findByComposedConcept', command: 'find-by-composed-concept' }, { action: 'findBySync', command: 'find-by-sync' }, { action: 'compositionTree', command: 'composition-tree' }, { action: 'traceRollup', command: 'trace-rollup' }],
};
