// Auto-generated by Clef Clef Bind — cli target
// Concept: BindRewriteProvider
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const bindRewriteProviderCommand = new Command('bind-rewrite-provider')
  .description('Rewrite data binding expressions in RenderProgram instruction sequences remapping binding expression strings so that component data sources can be swapped through a pure instruction rewrite over the program');

bindRewriteProviderCommand
  .command('register')
  .description('Return static metadata for PluginRegistry . name : BindRewriteProvider kind : bind-rewrite capabilities : [ expression-rewrite , data-source-swap ]')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/BindRewriteProvider', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

bindRewriteProviderCommand
  .command('apply')
  .description('Walk the instruction sequence and rewrite binding expressions per the rewrites mapping in spec . Instructions with tag bind have their expr field remapped if it appears in the mapping . Non bind instructions pass through unchanged . Returns the new serialized program and the updated list of applied transforms .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--spec <spec>', 'Spec')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/BindRewriteProvider', 'apply', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const bindRewriteProviderCommandTree = {
  group: 'bind-rewrite-provider',
  description: 'Rewrite data binding expressions in RenderProgram instruction sequences remapping binding expression strings so that component data sources can be swapped through a pure instruction rewrite over the program',
  commands: [{ action: 'register', command: 'register' }, { action: 'apply', command: 'apply' }],
};
