// Auto-generated by Clef Clef Bind — cli target
// Concept: DevServer
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const devServerCommand = new Command('dev-server')
  .description('Start , stop , and monitor a local development server that watches concept specs and syncs for changes and auto-recompiles');

devServerCommand
  .command('start')
  .description('Start a local development server that watches for changes and auto-recompiles .')
  .requiredOption('--port <port>', 'Port')
  .requiredOption('--watch-dirs <watchDirs>', 'Watch dirs')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DevServer', 'start', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

devServerCommand
  .command('stop')
  .description('Stop the running development server .')
  .requiredOption('--session <session>', 'Session')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DevServer', 'stop', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

devServerCommand
  .command('status')
  .description('Check whether the dev server is running and view uptime stats .')
  .requiredOption('--session <session>', 'Session')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DevServer', 'status', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const devServerCommandTree = {
  group: 'dev-server',
  description: 'Start , stop , and monitor a local development server that watches concept specs and syncs for changes and auto-recompiles',
  commands: [{ action: 'start', command: 'start' }, { action: 'stop', command: 'stop' }, { action: 'status', command: 'status' }],
};
