// Auto-generated by Clef Clef Bind — mcp target
// Concept: SemanticEmbedding
// Do not edit manually; regenerate with: clef interface generate

export const semanticEmbeddingTools = [
  {
    "type": "tool",
    "name": "semantic_embedding_compute",
    "description": "Compute semanticembedding — Compute a vector embedding for a definition unit using \n the specified model ( codeBERT , unixcoder , openai code , \n voyage code ) .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "unit": {
          "type": "string"
        },
        "model": {
          "type": "string"
        }
      },
      "required": [
        "unit",
        "model"
      ]
    }
  },
  {
    "type": "resource-template",
    "name": "semantic_embedding_search_similar",
    "uriTemplate": "urn:clef://semantic-embeddings",
    "description": "Search similar semanticembedding — Find definition units most similar to the query vector , \n optionally filtered by language and kind . Results as \n serialized JSON array of { unit , score } ."
  },
  {
    "type": "resource-template",
    "name": "semantic_embedding_search_natural_language",
    "uriTemplate": "urn:clef://semantic-embeddings",
    "description": "Search natural language semanticembedding — Search for code matching a natural language description . \n Embeds the query and finds nearest definition units . \n Results as serialized JSON array of { unit , score } ."
  },
  {
    "type": "resource",
    "name": "semantic_embedding_get",
    "uri": "urn:clef://semantic-embeddings/{embedding}",
    "description": "Get semanticembedding — Retrieve embedding metadata ( vector omitted for size ) ."
  }
];
