// Auto-generated by Clef Clef Bind — cli target
// Concept: TemporalVersion
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const temporalVersionCommand = new Command('temporal-version')
  .description('Track content versions with bitemporal semantics when recorded 
 ( system time ) and when valid ( application time ) . Enables time travel 
 queries across both dimensions independently .');

temporalVersionCommand
  .command('record')
  .description('Version recorded with current system timestamp as systemFrom .')
  .requiredOption('--content-hash <contentHash>', 'Content Hash')
  .requiredOption('--valid-from <validFrom>', 'Valid From')
  .requiredOption('--valid-to <validTo>', 'Valid To')
  .requiredOption('--metadata <metadata>', 'Metadata')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'record', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

temporalVersionCommand
  .command('as-of')
  .description('Returns the version active at the given system and or valid time .')
  .requiredOption('--system-time <systemTime>', 'System Time')
  .requiredOption('--valid-time <validTime>', 'Valid Time')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'asOf', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

temporalVersionCommand
  .command('between')
  .description('Returns all versions active within the range on the 
 given dimension system or valid .')
  .requiredOption('--start <start>', 'Start')
  .requiredOption('--end <end>', 'End')
  .requiredOption('--dimension <dimension>', 'Dimension')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'between', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

temporalVersionCommand
  .command('current')
  .description('Returns the currently active version .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'current', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

temporalVersionCommand
  .command('supersede')
  .description('Creates a new version . Sets systemTo on the old version .')
  .requiredOption('--version-id <versionId>', 'Version Id')
  .requiredOption('--content-hash <contentHash>', 'Content Hash')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'supersede', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const temporalVersionCommandTree = {
  group: 'temporal-version',
  description: 'Track content versions with bitemporal semantics when recorded 
 ( system time ) and when valid ( application time ) . Enables time travel 
 queries across both dimensions independently .',
  commands: [{ action: 'record', command: 'record' }, { action: 'asOf', command: 'as-of' }, { action: 'between', command: 'between' }, { action: 'current', command: 'current' }, { action: 'supersede', command: 'supersede' }],
};
