// Auto-generated by Clef Clef Bind — cli target
// Concept: InterfaceScaffoldGen
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const interfaceScaffoldGenCommand = new Command('scaffold-interface')
  .description('Generate interface manifest (interface.yaml).');

interfaceScaffoldGenCommand
  .command('interface')
  .description('Scaffold an interface.yaml with targets, SDKs, and concept overrides.')
  .requiredOption('-n, --name <name>', 'Interface name')
  .option('-t, --targets <targets>', 'Comma-separated targets (rest, graphql, grpc, cli, mcp, claude-skills)', 'rest')
  .option('-s, --sdks <sdks>', 'Comma-separated SDK languages (typescript, python, go, rust, java, swift)', 'typescript')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  clef scaffold interface --name my-api --targets rest,graphql --sdks typescript,python  # Scaffold a REST + GraphQL interface')
  .addHelpText('after', '  clef scaffold interface --name my-api --targets rest,graphql,grpc,cli,mcp,claude-skills  # Scaffold a full-stack interface')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/InterfaceScaffoldGen', 'generate', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

interfaceScaffoldGenCommand
  .command('generate-dual')
  .description('Generate two companion interface manifests implementing the dual manifest Bind architecture . The config manifest ( manifest_type : config ) covers developer facing admin and configuration concepts with restricted auth ( admin role , api_key cookie oauth ) . The content manifest ( manifest_type : content ) covers user facing content and entity concepts with permissive auth ( anonymous default , cookie bearer_token oauth wallet ) . Both manifests share the same targets and SDKs but have separate base paths , rate limits , and concept groupings . See Architecture doc Section 6.1 6.2 .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--targets <targets>', 'Targets')
  .requiredOption('--sdks <sdks>', 'Sdks')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/InterfaceScaffoldGen', 'generateDual', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

interfaceScaffoldGenCommand
  .command('preview')
  .description('Dry-run: compute output files without writing. Uses Emitter content-addressing to show what would change.')
  .requiredOption('-n, --name <name>', 'Interface name')
  .option('-t, --targets <targets>', 'Comma-separated targets')
  .requiredOption('--sdks <sdks>', 'Sdks')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/InterfaceScaffoldGen', 'preview', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

interfaceScaffoldGenCommand
  .command('register')
  .description('Return static metadata for PluginRegistry . name : InterfaceScaffoldGen inputKind : InterfaceConfig outputKind : InterfaceManifest capabilities : [ interface-yaml , target-config , sdk-config , dual-manifest ]')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/InterfaceScaffoldGen', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const interfaceScaffoldGenCommandTree = {
  group: 'scaffold-interface',
  description: 'Generate interface manifest (interface.yaml).',
  commands: [{ action: 'generate', command: 'interface' }, { action: 'generateDual', command: 'generate-dual' }, { action: 'preview', command: 'preview' }, { action: 'register', command: 'register' }],
};
