// @clef-handler style=functional concept=EffectContractRenderer
// ============================================================
// EffectContractRenderer — HandlerDescriptor -> vitest effect-contract test.
//
// Emits a vitest test that invokes the handler with a fixture input
// under spy storage + transport adapters, then asserts the observed
// effect set EXACTLY matches the declared effect set. Fails if the
// handler adds an undeclared effect or drops a declared one.
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';
import {
  parseDescriptor,
  pascal,
} from './handler-descriptor.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'storage-spy',
  'transport-spy',
  'exact-match',
  'undeclared-effect-detection',
  'dropped-effect-detection',
].join(',');

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'effect-contract',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const raw = (input.descriptor as string | undefined) ?? '';
    const parsed = parseDescriptor(raw);
    if (!parsed.ok) {
      return complete(createProgram(), 'error', { message: parsed.message }) as StorageProgram<Result>;
    }
    const d = parsed.descriptor;
    const ConceptPascal = pascal(d.conceptName);
    const declaredReads = JSON.stringify(d.reads);
    const declaredWrites = JSON.stringify(d.writes);
    const declaredPerforms = JSON.stringify(d.performs);

    const code = `// @generated by EffectContractRenderer
// Effect-contract test for ${ConceptPascal}/${d.actionName}.
// Asserts the handler performs EXACTLY the declared storage reads/writes
// and transport effects. Fails on undeclared or dropped effects.

import { describe, it, expect } from 'vitest';
import { ${d.conceptName.toLowerCase()}Handler } from '../handlers/ts/${d.conceptName.toLowerCase()}.handler.ts';

describe('${ConceptPascal}/${d.actionName} effect contract', () => {
  it('reads/writes/performs match the declared effect set exactly', async () => {
    const declaredReads = new Set(${declaredReads});
    const declaredWrites = new Set(${declaredWrites});
    const declaredPerforms = new Set(${declaredPerforms});

    // Invoke the handler to obtain its StorageProgram.
    const program = await (${d.conceptName.toLowerCase()}Handler as any).${d.actionName}({});
    const effects = (program as any).effects ?? { reads: new Set(), writes: new Set(), performs: new Set() };

    const observedReads = new Set(effects.reads);
    const observedWrites = new Set(effects.writes);
    const observedPerforms = new Set(effects.performs);

    // Exact match: no undeclared reads.
    for (const r of observedReads) {
      expect(declaredReads.has(r as string), \`undeclared read: \${r}\`).toBe(true);
    }
    // Exact match: no dropped declared reads.
    for (const r of declaredReads) {
      expect(observedReads.has(r), \`declared read not performed: \${r}\`).toBe(true);
    }
    // Exact match: writes.
    for (const w of observedWrites) {
      expect(declaredWrites.has(w as string), \`undeclared write: \${w}\`).toBe(true);
    }
    for (const w of declaredWrites) {
      expect(observedWrites.has(w), \`declared write not performed: \${w}\`).toBe(true);
    }
    // Exact match: transport effects.
    for (const p of observedPerforms) {
      expect(declaredPerforms.has(p as string), \`undeclared perform: \${p}\`).toBe(true);
    }
    for (const p of declaredPerforms) {
      expect(observedPerforms.has(p), \`declared perform not performed: \${p}\`).toBe(true);
    }
  });
});
`;
    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const effectContractRendererHandler = autoInterpret(_handler);
export default effectContractRendererHandler;
