// @clef-handler style=functional concept=FieldTransformFuzzRenderer
// ============================================================
// FieldTransformFuzzRenderer — HandlerDescriptor -> fast-check fuzz test.
//
// Emits a vitest test that uses fast-check arbitraries to drive both
// happy-path and malformed-path inputs against the concept handler.
// For each FieldTransform-declared field a matching arbitrary is built
// (string/number/boolean/object/array/nullable, defaulting to
// fc.anything() when the type is unknown). The happy-path property
// asserts the handler returns variant === 'ok'. The malformed-path
// property mutates one field at a time (missing / null / wrong-type)
// and asserts the handler returns a non-ok variant without throwing.
// Default fast-check shrinking is enabled via fc.assert defaults.
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';
import { parseDescriptor, pascal, type FieldTransform } from './handler-descriptor.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'property-based',
  'mutation',
  'field-transform',
  'malformed-input',
  'crash-detection',
  'fast-check',
].join(',');

function arbitraryFor(field: FieldTransform): string {
  const name = field.from.toLowerCase();
  if (/(^|_)(id|uuid)$/.test(name) || name.endsWith('id')) return 'fc.string({ minLength: 1 })';
  if (/(email)/.test(name)) return 'fc.emailAddress()';
  if (/(lat|lon|lng|latitude|longitude)/.test(name)) return 'fc.double({ noNaN: true })';
  if (/(count|age|size|num|amount|qty|index|offset|limit)/.test(name)) return 'fc.integer()';
  if (/(flag|enabled|is[A-Z]|has[A-Z]|bool)/.test(name)) return 'fc.boolean()';
  if (/(name|title|label|desc|text|message|body)/.test(name)) return 'fc.string({ minLength: 1 })';
  if (/(tags|items|list|entries|members)/.test(name)) return 'fc.array(fc.string())';
  if (/(config|meta|options|params|data)/.test(name)) return 'fc.dictionary(fc.string(), fc.anything())';
  return 'fc.anything()';
}

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'field-transform-fuzz',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const raw = (input.descriptor as string | undefined) ?? '';
    const parsed = parseDescriptor(raw);
    if (!parsed.ok) {
      return complete(createProgram(), 'error', { message: parsed.message }) as StorageProgram<Result>;
    }
    const d = parsed.descriptor;
    const fields = d.requestFields ?? [];
    const ConceptPascal = pascal(d.conceptName);
    const conceptLower = d.conceptName.toLowerCase();
    const fieldNames = JSON.stringify(fields.map((f) => f.from));

    const arbEntries = fields
      .map((f) => `  ${JSON.stringify(f.from)}: ${arbitraryFor(f)},`)
      .join('\n');

    const code = `// @generated by FieldTransformFuzzRenderer
// Fast-check fuzz test for ${ConceptPascal}/${d.actionName}.
// Runs a happy-path property (all fields valid) and a malformed-path
// property (one field mutated: missing, null, or wrong type).

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import { ${conceptLower}Handler } from '../handlers/ts/${conceptLower}.handler.ts';

const FIELDS = ${fieldNames};

const fieldArbs: Record<string, fc.Arbitrary<unknown>> = {
${arbEntries}
};

function happyRecord(): fc.Arbitrary<Record<string, unknown>> {
  return fc.record(fieldArbs);
}

function wrongTypeArb(field: string): fc.Arbitrary<unknown> {
  return fc.constant({ __fuzzWrongType: field });
}

function mutate(
  base: Record<string, unknown>,
  field: string,
  mutation: 'omit' | 'null' | 'wrongType',
  wrong: unknown,
): Record<string, unknown> {
  const clone: Record<string, unknown> = { ...base };
  if (mutation === 'omit') { delete clone[field]; return clone; }
  if (mutation === 'null') { clone[field] = null; return clone; }
  clone[field] = wrong;
  return clone;
}

describe('${ConceptPascal}/${d.actionName} FieldTransform fuzz', () => {
  it('happy-path inputs return ok', async () => {
    await fc.assert(
      fc.asyncProperty(happyRecord(), async (input) => {
        const r = await (${conceptLower}Handler as any).${d.actionName}(input);
        expect(r).toBeDefined();
        expect(r.variant).toBe('ok');
      }),
    );
  });

  for (const field of FIELDS) {
    for (const mutation of ['omit', 'null', 'wrongType'] as const) {
      it(\`malformed \${mutation} of \${field} returns non-ok without throwing\`, async () => {
        await fc.assert(
          fc.asyncProperty(
            happyRecord(),
            wrongTypeArb(field),
            async (base, wrong) => {
              const mutated = mutate(base, field, mutation, wrong);
              let r: { variant: string; [key: string]: unknown } | undefined;
              let threw = false;
              try {
                r = await (${conceptLower}Handler as any).${d.actionName}(mutated);
              } catch {
                threw = true;
              }
              expect(threw).toBe(false);
              expect(r).toBeDefined();
              expect(r!.variant).not.toBe('ok');
            },
          ),
        );
      });
    }
  }
});
`;
    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const fieldTransformFuzzRendererHandler = autoInterpret(_handler);
export default fieldTransformFuzzRendererHandler;
