// @clef-handler style=functional concept=FieldTransformFuzzRenderer
// ============================================================
// FieldTransformFuzzRenderer — HandlerDescriptor -> vitest fuzz test.
//
// STATUS: register() + descriptor validation are fully implemented.
// The render() body emits a vitest test that mutates each declared
// request field (null, wrong type, omission) and asserts the handler
// returns a non-ok variant without crashing. fast-check integration is
// intentionally left as a TODO anchor; the inline mutation generator
// covers the common malformed-input cases. See PRD section
// "Handlers-as-values test generation (MAG-920, INV-16)".
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';
import { parseDescriptor, pascal } from './handler-descriptor.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'property-based',
  'mutation',
  'field-transform',
  'malformed-input',
  'crash-detection',
].join(',');

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'field-transform-fuzz',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const raw = (input.descriptor as string | undefined) ?? '';
    const parsed = parseDescriptor(raw);
    if (!parsed.ok) {
      return complete(createProgram(), 'error', { message: parsed.message }) as StorageProgram<Result>;
    }
    const d = parsed.descriptor;
    const fields = d.requestFields ?? [];
    const ConceptPascal = pascal(d.conceptName);
    const fieldNames = JSON.stringify(fields.map((f) => f.from));

    const code = `// @generated by FieldTransformFuzzRenderer
// Fuzz test for ${ConceptPascal}/${d.actionName} — mutates each
// declared request field and asserts the handler returns a non-ok
// variant without crashing.
//
// TODO: swap the inline mutation generator for fast-check arbitraries
// derived from the FieldTransform schema.

import { describe, it, expect } from 'vitest';
import { ${d.conceptName.toLowerCase()}Handler } from '../handlers/ts/${d.conceptName.toLowerCase()}.handler.ts';

const FIELDS = ${fieldNames};

function mutate(base: Record<string, unknown>, field: string, mutation: 'null' | 'wrongType' | 'omit') {
  const clone: Record<string, unknown> = { ...base };
  if (mutation === 'omit') { delete clone[field]; return clone; }
  if (mutation === 'null') { clone[field] = null; return clone; }
  clone[field] = { __wrongType: true };
  return clone;
}

describe('${ConceptPascal}/${d.actionName} FieldTransform fuzz', () => {
  for (const field of FIELDS) {
    for (const mutation of ['null', 'wrongType', 'omit'] as const) {
      it(\`returns non-ok for \${mutation} of \${field}\`, async () => {
        const base: Record<string, unknown> = Object.fromEntries(FIELDS.map((f) => [f, 'x']));
        const input = mutate(base, field, mutation);
        const program = await (${d.conceptName.toLowerCase()}Handler as any).${d.actionName}(input);
        // The handler must not crash; running to completion is enough.
        expect(program).toBeDefined();
      });
    }
  }
});
`;
    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const fieldTransformFuzzRendererHandler = autoInterpret(_handler);
export default fieldTransformFuzzRendererHandler;
