// @clef-handler style=functional concept=JetpackRenderer
// ============================================================
// JetpackRenderer — TestPlan -> JUnit 4 + Compose UI Test file (Kotlin).
//
// Translates the universal probe namespace into Compose testing primitives
// (composeTestRule.onNodeWithTag, assertTextEquals, performClick,
// performKeyInput). Self-registers via register() + sync-to-PluginRegistry
// pattern.
//
// TODO: implement full probe translation table. Current output is
// a structurally valid placeholder that emits a stub Kotlin test body.
// See docs/plans/invariant-grammar-portability-prd.md §INV-12 for
// the per-platform translation table specification.
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'junit4',
  'compose-ui-test',
  'onNodeWithTag',
  'assertTextEquals',
  'performClick',
  'performKeyInput',
  'immediately',
  'eventually',
].join(',');

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'jetpack',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const planStr = (input.plan as string | undefined) ?? '';
    if (!planStr || planStr.trim() === '') {
      return complete(createProgram(), 'error', {
        message: 'plan is required',
      }) as StorageProgram<Result>;
    }

    let plan: Record<string, unknown>;
    try {
      plan = JSON.parse(planStr);
    } catch (err) {
      return complete(createProgram(), 'error', {
        message: `plan is not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
      }) as StorageProgram<Result>;
    }

    if (!plan || typeof plan !== 'object' || !plan.planId) {
      return complete(createProgram(), 'error', {
        message: 'plan is missing required field: planId',
      }) as StorageProgram<Result>;
    }

    const planId = plan.planId as string;
    const specKind = (plan.specKind as string) ?? 'unknown';
    const className = planId.replace(/[^a-zA-Z0-9]/g, '_');

    // TODO: implement — replace this stub with the full probe translation
    // table for Jetpack Compose UI Test. See PRD §INV-12 for the universal
    // probe namespace spec. Key mappings to implement:
    //   body.textContent → composeTestRule.onNodeWithTag("body", useUnmergedTree = true).assertTextEquals(expected)
    //   state.<field>    → composeTestRule.onNodeWithTag("root").assert(hasAnyAncestor(hasTestTag("data-state-<field>")))
    //   .click()         → composeTestRule.onNodeWithTag(...).performClick()
    //   .press(key)      → composeTestRule.onNodeWithTag(...).performKeyInput { pressKey(Key.<key>) }
    //   immediately      → assertion after performX
    //   eventually       → composeTestRule.waitUntil { ... }
    const code = `// Generated by JetpackRenderer — stub implementation (INV-12)
// TODO: Jetpack Compose renderer not yet implemented. Replace this file with the
// full probe translation once JetpackRenderer is fleshed out.
// Plan: ${planId}  SpecKind: ${specKind}

package com.clef.generated.tests

import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.assertIsDisplayed
import org.junit.Rule
import org.junit.Test

class ${className}Test {

    @get:Rule
    val composeTestRule = createComposeRule()

    @Test
    fun stubNotYetImplemented() {
        // TODO: implement probe translation for ${specKind} spec.
        // See docs/plans/invariant-grammar-portability-prd.md §INV-12
        // Jetpack Compose renderer not yet implemented.
    }
}
`;

    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const jetpackRendererHandler = autoInterpret(_handler);
export default jetpackRendererHandler;
