// @clef-handler style=functional concept=MockHandlerRenderer
// ============================================================
// MockHandlerRenderer — HandlerDescriptor -> mock handler source.
//
// Given a HandlerDescriptor (either StorageProgram-derived or
// ExternalHandler-manifest-derived), emit a TypeScript handler source
// string that satisfies the same action interface but returns canned
// responses. Self-registers via the PluginRegistry pattern.
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';
import {
  parseDescriptor,
  pascal,
  type HandlerDescriptor,
} from './handler-descriptor.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'storage-program',
  'external-handler',
  'field-transform',
  'seed-map',
  'canned-response',
].join(',');

function renderExternalMock(d: HandlerDescriptor): string {
  const ConceptPascal = pascal(d.conceptName);
  const responseShape = (d.responseFields ?? [])
    .map((f) => `    ${JSON.stringify(f.to)}: ${JSON.stringify(`<mocked:${f.to}>`)},`)
    .join('\n');
  const requestCheck = (d.requestFields ?? [])
    .map((f) => `  // expects input.${f.from} -> request.${f.to}`)
    .join('\n');
  return `// @generated by MockHandlerRenderer
// Mock handler for ${ConceptPascal}/${d.actionName} (external, ${d.method ?? 'HTTP'} ${d.path ?? ''}).
// Returns canned responses shaped by the declared response FieldTransforms.

import type { FunctionalConceptHandler } from '../../runtime/functional-handler.ts';
import { createProgram, complete, type StorageProgram } from '../../runtime/storage-program.ts';
import { autoInterpret } from '../../runtime/functional-compat.ts';

type Result = { variant: string; [key: string]: unknown };

const _mock: FunctionalConceptHandler = {
  ${d.actionName}(_input: Record<string, unknown>) {
${requestCheck}
    const response = {
${responseShape}
    };
    return complete(createProgram(), 'ok', response) as StorageProgram<Result>;
  },
};

export const ${d.conceptName}MockHandler = autoInterpret(_mock);
export default ${d.conceptName}MockHandler;
`;
}

function renderStorageMock(d: HandlerDescriptor): string {
  const ConceptPascal = pascal(d.conceptName);
  const readsList = d.reads.map((r) => JSON.stringify(r)).join(', ');
  const writesList = d.writes.map((w) => JSON.stringify(w)).join(', ');
  const primaryOk = d.variants.includes('ok') ? 'ok' : d.variants[0] ?? 'ok';
  return `// @generated by MockHandlerRenderer
// Mock handler for ${ConceptPascal}/${d.actionName} (storage).
// Services reads from a seed map; writes are no-ops.
// Declared reads:  [${readsList}]
// Declared writes: [${writesList}]

import type { FunctionalConceptHandler } from '../../runtime/functional-handler.ts';
import { createProgram, complete, type StorageProgram } from '../../runtime/storage-program.ts';
import { autoInterpret } from '../../runtime/functional-compat.ts';

type Result = { variant: string; [key: string]: unknown };

/** Seed map the mock services reads from. Override per-test by assigning keys. */
export const ${d.conceptName}MockSeed: Record<string, Record<string, unknown>> = {
${d.reads.map((r) => `  ${JSON.stringify(r)}: {},`).join('\n')}
};

const _mock: FunctionalConceptHandler = {
  ${d.actionName}(_input: Record<string, unknown>) {
    // Writes are no-ops in the mock; reads resolve from ${d.conceptName}MockSeed.
    return complete(createProgram(), ${JSON.stringify(primaryOk)}, {}) as StorageProgram<Result>;
  },
};

export const ${d.conceptName}MockHandler = autoInterpret(_mock);
export default ${d.conceptName}MockHandler;
`;
}

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'mock-handler',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const raw = (input.descriptor as string | undefined) ?? '';
    const parsed = parseDescriptor(raw);
    if (!parsed.ok) {
      return complete(createProgram(), 'error', { message: parsed.message }) as StorageProgram<Result>;
    }
    const code = parsed.descriptor.kind === 'external'
      ? renderExternalMock(parsed.descriptor)
      : renderStorageMock(parsed.descriptor);
    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const mockHandlerRendererHandler = autoInterpret(_handler);
export default mockHandlerRendererHandler;
