// @clef-handler style=functional concept=ReplayHandlerRenderer
// ============================================================
// ReplayHandlerRenderer — HandlerDescriptor -> record/replay handler source.
//
// Emits a self-contained TypeScript handler that switches on
// CLEF_REPLAY_MODE. In record mode it calls the real handler, computes
// a stable fingerprint from the request, and appends a cassette entry
// under tests/cassettes/<concept>/<action>.json. In replay mode
// (default) it loads the cassette and returns the matching response,
// throwing a descriptive error when the fingerprint is not recorded.
//
// Fingerprinting:
//   - External descriptors: apply the request-side FieldTransforms to
//     produce the remote-shaped payload, then SHA-256 hex of the
//     stably-serialized JSON.
//   - Storage descriptors: SHA-256 hex of stably-serialized input.
// Stable serialization sorts object keys recursively so call-sites with
// different key order produce the same fingerprint.
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';
import { parseDescriptor, pascal, type HandlerDescriptor } from './handler-descriptor.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'record-mode',
  'replay-mode',
  'cassette',
  'fingerprint',
  'external-handler',
].join(',');

function renderRequestShape(d: HandlerDescriptor): string {
  if (d.kind === 'external' && d.requestFields && d.requestFields.length > 0) {
    const lines = d.requestFields.map(
      (f) => `  if (${JSON.stringify(f.from)} in input) out[${JSON.stringify(f.to)}] = (input as any)[${JSON.stringify(f.from)}];`,
    );
    return `function shapeRequest(input: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
${lines.join('\n')}
  return out;
}`;
  }
  return `function shapeRequest(input: Record<string, unknown>): Record<string, unknown> {
  return input;
}`;
}

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'replay-handler',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const raw = (input.descriptor as string | undefined) ?? '';
    const parsed = parseDescriptor(raw);
    if (!parsed.ok) {
      return complete(createProgram(), 'error', { message: parsed.message }) as StorageProgram<Result>;
    }
    const d = parsed.descriptor;
    const ConceptPascal = pascal(d.conceptName);
    const conceptLower = d.conceptName.toLowerCase();
    const cassettePath = `tests/cassettes/${conceptLower}/${d.actionName}.json`;
    const shapeFn = renderRequestShape(d);

    const code = `// @generated by ReplayHandlerRenderer
// Record/replay handler for ${ConceptPascal}/${d.actionName}.
// CLEF_REPLAY_MODE=record -> call real handler, append to cassette.
// CLEF_REPLAY_MODE=replay (default) -> read cassette, match by fingerprint.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { createHash } from 'node:crypto';
import { ${conceptLower}Handler as realHandler } from '../handlers/ts/${conceptLower}.handler.ts';

const CASSETTE_PATH = ${JSON.stringify(cassettePath)};

type CassetteEntry = { fingerprint: string; request: unknown; response: unknown };

${shapeFn}

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(stableStringify).join(',') + ']';
  const obj = value as Record<string, unknown>;
  const keys = Object.keys(obj).sort();
  return '{' + keys.map((k) => JSON.stringify(k) + ':' + stableStringify(obj[k])).join(',') + '}';
}

function fingerprint(input: Record<string, unknown>): string {
  const shaped = shapeRequest(input);
  return createHash('sha256').update(stableStringify(shaped)).digest('hex');
}

function loadCassette(): CassetteEntry[] {
  if (!fs.existsSync(CASSETTE_PATH)) return [];
  const raw = fs.readFileSync(CASSETTE_PATH, 'utf8');
  if (raw.trim() === '') return [];
  const parsed = JSON.parse(raw);
  return Array.isArray(parsed) ? parsed as CassetteEntry[] : [];
}

function writeCassette(entries: CassetteEntry[]): void {
  fs.mkdirSync(path.dirname(CASSETTE_PATH), { recursive: true });
  fs.writeFileSync(CASSETTE_PATH, JSON.stringify(entries, null, 2), 'utf8');
}

export const ${d.conceptName}ReplayHandler = {
  async ${d.actionName}(input: Record<string, unknown>) {
    const mode = (globalThis as any).process?.env?.CLEF_REPLAY_MODE ?? 'replay';
    const fp = fingerprint(input);

    if (mode === 'record') {
      const response = await (realHandler as any).${d.actionName}(input);
      const entries = loadCassette();
      if (!entries.some((e) => e.fingerprint === fp)) {
        entries.push({ fingerprint: fp, request: shapeRequest(input), response });
        writeCassette(entries);
      }
      return response;
    }

    const entries = loadCassette();
    const hit = entries.find((e) => e.fingerprint === fp);
    if (!hit) {
      throw new Error(
        'ReplayHandler: no cassette entry for fingerprint ' + fp +
        ' in ' + CASSETTE_PATH + ' (re-run with CLEF_REPLAY_MODE=record to record).',
      );
    }
    return hit.response;
  },
};

export default ${d.conceptName}ReplayHandler;
`;
    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const replayHandlerRendererHandler = autoInterpret(_handler);
export default replayHandlerRendererHandler;
