// @clef-handler style=functional concept=ReplayHandlerRenderer
// ============================================================
// ReplayHandlerRenderer — HandlerDescriptor -> record/replay handler source.
//
// STATUS: register() + descriptor validation are fully implemented.
// The render() body emits a minimal, compilable record/replay handler
// skeleton that switches on CLEF_REPLAY_MODE; the cassette-fingerprint
// logic is intentionally left as a TODO anchor because a full
// implementation requires a shared cassette-io helper that is not yet
// carved out. See the PRD section "Handlers-as-values test generation
// (MAG-920, INV-16)" for the full target behavior.
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';
import { parseDescriptor, pascal } from './handler-descriptor.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'record-mode',
  'replay-mode',
  'cassette',
  'fingerprint',
  'external-handler',
].join(',');

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'replay-handler',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const raw = (input.descriptor as string | undefined) ?? '';
    const parsed = parseDescriptor(raw);
    if (!parsed.ok) {
      return complete(createProgram(), 'error', { message: parsed.message }) as StorageProgram<Result>;
    }
    const d = parsed.descriptor;
    const ConceptPascal = pascal(d.conceptName);

    const code = `// @generated by ReplayHandlerRenderer
// Record/replay handler skeleton for ${ConceptPascal}/${d.actionName}.
// CLEF_REPLAY_MODE=record -> call real handler, persist to
//   tests/cassettes/${d.conceptName.toLowerCase()}/${d.actionName}.json
// CLEF_REPLAY_MODE=replay (default) -> read from cassette.
//
// TODO: wire cassette fingerprint derived from FieldTransform-shaped
// request, cassette read/write helpers, and real-handler fallthrough.

import type { FunctionalConceptHandler } from '../../runtime/functional-handler.ts';
import { createProgram, complete, type StorageProgram } from '../../runtime/storage-program.ts';
import { autoInterpret } from '../../runtime/functional-compat.ts';

type Result = { variant: string; [key: string]: unknown };

const CASSETTE_PATH = 'tests/cassettes/${d.conceptName.toLowerCase()}/${d.actionName}.json';
const MODE = (globalThis as any).process?.env?.CLEF_REPLAY_MODE ?? 'replay';

const _replay: FunctionalConceptHandler = {
  ${d.actionName}(_input: Record<string, unknown>) {
    if (MODE === 'record') {
      // TODO: call real handler, capture response, write to CASSETTE_PATH.
      return complete(createProgram(), 'ok', { mode: 'record', cassette: CASSETTE_PATH }) as StorageProgram<Result>;
    }
    // TODO: load cassette from CASSETTE_PATH, match by request fingerprint.
    return complete(createProgram(), 'ok', { mode: 'replay', cassette: CASSETTE_PATH }) as StorageProgram<Result>;
  },
};

export const ${d.conceptName}ReplayHandler = autoInterpret(_replay);
export default ${d.conceptName}ReplayHandler;
`;
    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const replayHandlerRendererHandler = autoInterpret(_handler);
export default replayHandlerRendererHandler;
