// @clef-handler style=functional concept=SvelteRenderer
// ============================================================
// SvelteRenderer — TestPlan -> Vitest + Svelte Testing Library test file.
//
// Translates the universal probe namespace into Svelte Testing Library
// primitives (render, screen.getByTestId, fireEvent, waitFor).
// Self-registers via register() + sync-to-PluginRegistry pattern.
//
// TODO: implement full probe translation table. Current output is
// a structurally valid placeholder that emits a stub test body.
// See docs/plans/invariant-grammar-portability-prd.md §INV-12 for
// the per-platform translation table specification.
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../../runtime/functional-compat.ts';

type Result = { variant: string; [key: string]: unknown };

const CAPABILITIES = [
  'vitest',
  'svelte-testing-library',
  'render',
  'screen',
  'fireEvent',
  'waitFor',
  'immediately',
  'eventually',
].join(',');

const _handler: FunctionalConceptHandler = {
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'svelte',
      capabilities: CAPABILITIES,
    }) as StorageProgram<Result>;
  },

  render(input: Record<string, unknown>) {
    const planStr = (input.plan as string | undefined) ?? '';
    if (!planStr || planStr.trim() === '') {
      return complete(createProgram(), 'error', {
        message: 'plan is required',
      }) as StorageProgram<Result>;
    }

    let plan: Record<string, unknown>;
    try {
      plan = JSON.parse(planStr);
    } catch (err) {
      return complete(createProgram(), 'error', {
        message: `plan is not valid JSON: ${err instanceof Error ? err.message : String(err)}`,
      }) as StorageProgram<Result>;
    }

    if (!plan || typeof plan !== 'object' || !plan.planId) {
      return complete(createProgram(), 'error', {
        message: 'plan is missing required field: planId',
      }) as StorageProgram<Result>;
    }

    const planId = plan.planId as string;
    const specKind = (plan.specKind as string) ?? 'unknown';

    // TODO: implement — replace this stub with the full probe translation
    // table for Svelte Testing Library. See PRD §INV-12 for the universal
    // probe namespace spec (body.textContent → screen.getByTestId('body').textContent,
    // state.<field> → screen.getByTestId('root').getAttribute('data-state-<field>'), etc.)
    const code = `// @generated by SvelteRenderer — stub implementation (INV-12)
// TODO: Svelte renderer not yet implemented. Replace this file with the
// full probe translation once SvelteRenderer is fleshed out.
// Plan: ${planId}  SpecKind: ${specKind}

import { describe, it, expect } from 'vitest';
import { render, screen } from '@testing-library/svelte';

describe('${planId}', () => {
  it('// Svelte renderer not yet implemented', () => {
    // TODO: implement probe translation for ${specKind} spec.
    // See docs/plans/invariant-grammar-portability-prd.md §INV-12
    expect(true).toBe(true);
  });
});
`;

    return complete(createProgram(), 'ok', { code }) as StorageProgram<Result>;
  },
};

export const svelteRendererHandler = autoInterpret(_handler);
export default svelteRendererHandler;
