// Auto-generated by Clef Clef Bind — mcp target
// Concept: ProgramSlice
// Do not edit manually; regenerate with: clef interface generate

export const programSliceTools = [
  {
    "type": "tool",
    "name": "program_slice_compute",
    "description": "Compute programslice — Compute a program slice from the given criterion symbol . \n Direction is forward ( what is affected ) or backward \n ( what contributes ) .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "criterion": {
          "type": "string"
        },
        "direction": {
          "type": "string"
        }
      },
      "required": [
        "criterion",
        "direction"
      ]
    }
  },
  {
    "type": "tool",
    "name": "program_slice_files_in_slice",
    "description": "Files in slice programslice — Return all files included in the slice . \n Results as serialized JSON array .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "slice": {
          "type": "string"
        }
      },
      "required": [
        "slice"
      ]
    }
  },
  {
    "type": "tool",
    "name": "program_slice_symbols_in_slice",
    "description": "Symbols in slice programslice — Return all symbols included in the slice . \n Results as serialized JSON array .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "slice": {
          "type": "string"
        }
      },
      "required": [
        "slice"
      ]
    }
  },
  {
    "type": "resource",
    "name": "program_slice_get",
    "uri": "urn:clef://program-slices/{slice}",
    "description": "Get programslice — Retrieve slice metadata ."
  }
];
