// Auto-generated by Clef Clef Bind — mcp target
// Concept: SyncCompiler
// Do not edit manually; regenerate with: clef interface generate

export const syncCompilerTools = [
  {
    "type": "tool",
    "name": "sync_compiler_compile",
    "description": "Compile synccompiler — Transform the parsed sync AST into a CompiledSync \n object that the engine can register and evaluate . \n Resolve where clause queries into query plans .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "sync": {
          "type": "string"
        },
        "ast": {
          "type": "string"
        }
      },
      "required": [
        "sync",
        "ast"
      ]
    }
  }
];
