// Auto-generated by Clef Clef Bind — cli target
// Concept: ClefBase
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const clefBaseCommand = new Command('clef-base')
  .description('The complete Clef Base application platform a hierarchical composition of all content , infrastructure , LLM , process , view / surface , and integration concepts . ClefBase is the root derived concept that represents everything needed to run a full Clef application : content management with schemas and transclusions , version control with branching and merging , real-time collaboration , identity and access control , LLM agents with content-native personas , multi-step process execution , data-driven views with composable queries , headless UI rendering , composable diagramming with pluggable notations and graph analysis , plugin extensibility , offline-first support , HTTP routing , and package management . Every concept in clef-base is reachable through this hierarchy .');

clefBaseCommand
  .command('create-content')
  .description('Surface action: createContent')
  .requiredOption('--type <type>', 'Type')
  .requiredOption('--content <content>', 'Content')
  .requiredOption('--created-by <createdBy>', 'Created By')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'createContent', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('compile-content')
  .description('Surface action: compileContent')
  .requiredOption('--page-id <pageId>', 'Page Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'compileContent', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('define-schema')
  .description('Surface action: defineSchema')
  .requiredOption('--schema <schema>', 'Schema')
  .requiredOption('--fields <fields>', 'Fields')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'defineSchema', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('apply-schema')
  .description('Surface action: applySchema')
  .requiredOption('--entity-id <entity_id>', 'Entity_id')
  .requiredOption('--schema <schema>', 'Schema')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'applySchema', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('spawn-agent')
  .description('Surface action: spawnAgent')
  .requiredOption('--persona-page-id <personaPageId>', 'Persona Page Id')
  .requiredOption('--strategy <strategy>', 'Strategy')
  .requiredOption('--tools <tools>', 'Tools')
  .requiredOption('--context <context>', 'Context')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'spawnAgent', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('invoke-agent')
  .description('Surface action: invokeAgent')
  .requiredOption('--session <session>', 'Session')
  .requiredOption('--goal <goal>', 'Goal')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'invokeAgent', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('create-trigger')
  .description('Surface action: createTrigger')
  .requiredOption('--persona-page-id <personaPageId>', 'Persona Page Id')
  .requiredOption('--trigger-type <triggerType>', 'Trigger Type')
  .requiredOption('--config <config>', 'Config')
  .requiredOption('--strategy <strategy>', 'Strategy')
  .requiredOption('--tools <tools>', 'Tools')
  .requiredOption('--cooldown-ms <cooldownMs>', 'Cooldown Ms')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'createTrigger', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('start-process')
  .description('Surface action: startProcess')
  .requiredOption('--spec <spec>', 'Spec')
  .requiredOption('--input <input>', 'Input')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'startProcess', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('approve-step')
  .description('Surface action: approveStep')
  .requiredOption('--work-item <workItem>', 'Work Item')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'approveStep', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('create-view')
  .description('Surface action: createView')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--data-source <dataSource>', 'Data Source')
  .requiredOption('--filter <filter>', 'Filter')
  .requiredOption('--sort <sort>', 'Sort')
  .requiredOption('--projection <projection>', 'Projection')
  .requiredOption('--presentation <presentation>', 'Presentation')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'createView', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('resolve-view')
  .description('Surface action: resolveView')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'resolveView', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('install-package')
  .description('Surface action: installPackage')
  .requiredOption('--package-name <packageName>', 'Package Name')
  .requiredOption('--version <version>', 'Version')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'installPackage', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('browse-packages')
  .description('Surface action: browsePackages')
  .requiredOption('--query <query>', 'Query')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'browsePackages', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('create-diagram')
  .description('Surface action: createDiagram')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--notation <notation>', 'Notation')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'createDiagram', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('export-diagram')
  .description('Surface action: exportDiagram')
  .requiredOption('--canvas <canvas>', 'Canvas')
  .requiredOption('--format <format>', 'Format')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'exportDiagram', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('analyze-graph')
  .description('Surface action: analyzeGraph')
  .requiredOption('--graph <graph>', 'Graph')
  .requiredOption('--algorithm <algorithm>', 'Algorithm')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'analyzeGraph', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('get-content')
  .description('Surface query: getContent')
  .requiredOption('--node <node>', 'Node')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'getContent', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('get-agent-status')
  .description('Surface query: getAgentStatus')
  .requiredOption('--session <session>', 'Session')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'getAgentStatus', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('list-sessions')
  .description('Surface query: listSessions')
  .requiredOption('--persona-page-id <personaPageId>', 'Persona Page Id')
  .requiredOption('--status <status>', 'Status')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'listSessions', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('get-process-status')
  .description('Surface query: getProcessStatus')
  .requiredOption('--process-run <processRun>', 'Process Run')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'getProcessStatus', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

clefBaseCommand
  .command('get-view')
  .description('Surface query: getView')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ClefBase', 'getView', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const clefBaseCommandTree = {
  group: 'clef-base',
  description: 'The complete Clef Base application platform a hierarchical composition of all content , infrastructure , LLM , process , view / surface , and integration concepts . ClefBase is the root derived concept that represents everything needed to run a full Clef application : content management with schemas and transclusions , version control with branching and merging , real-time collaboration , identity and access control , LLM agents with content-native personas , multi-step process execution , data-driven views with composable queries , headless UI rendering , composable diagramming with pluggable notations and graph analysis , plugin extensibility , offline-first support , HTTP routing , and package management . Every concept in clef-base is reachable through this hierarchy .',
  commands: [{ action: 'createContent', command: 'create-content' }, { action: 'compileContent', command: 'compile-content' }, { action: 'defineSchema', command: 'define-schema' }, { action: 'applySchema', command: 'apply-schema' }, { action: 'spawnAgent', command: 'spawn-agent' }, { action: 'invokeAgent', command: 'invoke-agent' }, { action: 'createTrigger', command: 'create-trigger' }, { action: 'startProcess', command: 'start-process' }, { action: 'approveStep', command: 'approve-step' }, { action: 'createView', command: 'create-view' }, { action: 'resolveView', command: 'resolve-view' }, { action: 'installPackage', command: 'install-package' }, { action: 'browsePackages', command: 'browse-packages' }, { action: 'createDiagram', command: 'create-diagram' }, { action: 'exportDiagram', command: 'export-diagram' }, { action: 'analyzeGraph', command: 'analyze-graph' }, { action: 'getContent', command: 'get-content' }, { action: 'getAgentStatus', command: 'get-agent-status' }, { action: 'listSessions', command: 'list-sessions' }, { action: 'getProcessStatus', command: 'get-process-status' }, { action: 'getView', command: 'get-view' }],
};
