// Auto-generated by Clef Clef Bind — mcp target
// Concept: TransformExtractionProvider
// Do not edit manually; regenerate with: clef interface generate

export const transformExtractionProviderTools = [
  {
    "type": "tool",
    "name": "transform_extraction_provider_analyze",
    "description": "Analyze transformextractionprovider — Parse the program and extract its appliedTransforms \n metadata . Return the list of transform names that were \n applied , in order of application , plus the total count .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        }
      },
      "required": [
        "program"
      ]
    }
  }
];
