// SlotProvider — types.ts
// Generated by NextjsGen. Do not edit manually.
// Uses fp-ts for purely functional, composable concept implementations.

// Storage interface for SlotProvider
export interface SlotProviderStorage {
  readonly get: (relation: string, key: string) => Promise<Record<string, unknown> | null>;
  readonly put: (relation: string, key: string, value: Record<string, unknown>) => Promise<void>;
  readonly delete: (relation: string, key: string) => Promise<boolean>;
  readonly find: (relation: string, filter?: Record<string, unknown>) => Promise<readonly Record<string, unknown>[]>;
}

export interface SlotProviderInitializeInput {
  readonly provider: string;
  readonly domain: string;
}

export interface SlotProviderInitializeOutputOk {
  readonly variant: 'ok';
  readonly provider: string;
  readonly pluginRef: string;
}

export interface SlotProviderInitializeOutputAlreadyExists {
  readonly variant: 'already_exists';
  readonly provider: string;
  readonly pluginRef: string;
}

export type SlotProviderInitializeOutput =
  | SlotProviderInitializeOutputOk
  | SlotProviderInitializeOutputAlreadyExists;

export interface SlotProviderDefineInput {
  readonly slotName: string;
  readonly accepts: string;
  readonly multiple: boolean;
}

export interface SlotProviderDefineOutputOk {
  readonly variant: 'ok';
  readonly slotName: string;
  readonly slotId: string;
}

export interface SlotProviderDefineOutputAlreadyExists {
  readonly variant: 'already_exists';
  readonly slotName: string;
  readonly message: string;
}

export type SlotProviderDefineOutput =
  | SlotProviderDefineOutputOk
  | SlotProviderDefineOutputAlreadyExists;

export interface SlotProviderFillInput {
  readonly slotName: string;
  readonly content: Record<string, unknown>;
}

export interface SlotProviderFillOutputOk {
  readonly variant: 'ok';
  readonly slotName: string;
  readonly filled: boolean;
}

export interface SlotProviderFillOutputNotFound {
  readonly variant: 'not_found';
  readonly slotName: string;
  readonly message: string;
}

export type SlotProviderFillOutput =
  | SlotProviderFillOutputOk
  | SlotProviderFillOutputNotFound;

export interface SlotProviderClearInput {
  readonly slotName: string;
}

export interface SlotProviderClearOutputOk {
  readonly variant: 'ok';
  readonly slotName: string;
  readonly cleared: boolean;
}

export interface SlotProviderClearOutputNotFound {
  readonly variant: 'not_found';
  readonly slotName: string;
  readonly message: string;
}

export type SlotProviderClearOutput =
  | SlotProviderClearOutputOk
  | SlotProviderClearOutputNotFound;

export interface SlotProviderGetSlotsInput {
  readonly prefix?: string;
}

export interface SlotProviderGetSlotsOutputOk {
  readonly variant: 'ok';
  readonly slots: readonly Record<string, unknown>[];
  readonly count: number;
}

export type SlotProviderGetSlotsOutput =
  | SlotProviderGetSlotsOutputOk;

// --- Variant constructors ---

export const initializeOk = (provider: string, pluginRef: string): SlotProviderInitializeOutput =>
  ({ variant: 'ok', provider, pluginRef } as SlotProviderInitializeOutput);

export const initializeAlreadyExists = (provider: string, pluginRef: string): SlotProviderInitializeOutput =>
  ({ variant: 'already_exists', provider, pluginRef } as SlotProviderInitializeOutput);

export const defineOk = (slotName: string, slotId: string): SlotProviderDefineOutput =>
  ({ variant: 'ok', slotName, slotId } as SlotProviderDefineOutput);

export const defineAlreadyExists = (slotName: string, message: string): SlotProviderDefineOutput =>
  ({ variant: 'already_exists', slotName, message } as SlotProviderDefineOutput);

export const fillOk = (slotName: string, filled: boolean): SlotProviderFillOutput =>
  ({ variant: 'ok', slotName, filled } as SlotProviderFillOutput);

export const fillNotFound = (slotName: string, message: string): SlotProviderFillOutput =>
  ({ variant: 'not_found', slotName, message } as SlotProviderFillOutput);

export const clearOk = (slotName: string, cleared: boolean): SlotProviderClearOutput =>
  ({ variant: 'ok', slotName, cleared } as SlotProviderClearOutput);

export const clearNotFound = (slotName: string, message: string): SlotProviderClearOutput =>
  ({ variant: 'not_found', slotName, message } as SlotProviderClearOutput);

export const getSlotsOk = (slots: readonly Record<string, unknown>[], count: number): SlotProviderGetSlotsOutput =>
  ({ variant: 'ok', slots, count } as SlotProviderGetSlotsOutput);
