// BindingProvider — handler.ts
// Generated by NextjsGen. Do not edit manually.
// Uses fp-ts for purely functional, composable concept implementations.

import * as TE from 'fp-ts/TaskEither';
import * as O from 'fp-ts/Option';
import { pipe } from 'fp-ts/function';

import type {
  BindingProviderStorage,
  BindingProviderInitializeInput,
  BindingProviderInitializeOutput,
  BindingProviderBindInput,
  BindingProviderBindOutput,
  BindingProviderSyncInput,
  BindingProviderSyncOutput,
  BindingProviderInvokeInput,
  BindingProviderInvokeOutput,
  BindingProviderUnbindInput,
  BindingProviderUnbindOutput,
} from './types.js';

import {
  initializeOk,
  initializeAlreadyExists,
  bindOk,
  bindConflict,
  syncOk,
  syncNotFound,
  invokeOk,
  invokeNotFound,
  unbindOk,
  unbindNotFound,
} from './types.js';

// --- Domain types ---

export interface BindingProviderError {
  readonly code: string;
  readonly message: string;
}

// --- Helpers ---

const storageError = (error: unknown): BindingProviderError => ({
  code: 'STORAGE_ERROR',
  message: error instanceof Error ? error.message : String(error),
});

const generateId = (): string =>
  `bp-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

const nowISO = (): string => new Date().toISOString();

// --- Handler interface ---

export interface BindingProviderHandler {
  readonly initialize: (
    input: BindingProviderInitializeInput,
    storage: BindingProviderStorage,
  ) => TE.TaskEither<BindingProviderError, BindingProviderInitializeOutput>;
  readonly bind: (
    input: BindingProviderBindInput,
    storage: BindingProviderStorage,
  ) => TE.TaskEither<BindingProviderError, BindingProviderBindOutput>;
  readonly sync: (
    input: BindingProviderSyncInput,
    storage: BindingProviderStorage,
  ) => TE.TaskEither<BindingProviderError, BindingProviderSyncOutput>;
  readonly invoke: (
    input: BindingProviderInvokeInput,
    storage: BindingProviderStorage,
  ) => TE.TaskEither<BindingProviderError, BindingProviderInvokeOutput>;
  readonly unbind: (
    input: BindingProviderUnbindInput,
    storage: BindingProviderStorage,
  ) => TE.TaskEither<BindingProviderError, BindingProviderUnbindOutput>;
}

// --- Implementation ---

export const bindingProviderHandler: BindingProviderHandler = {
  // Idempotent initialization: register this provider in storage and plugin-registry.
  initialize: (input, storage) =>
    pipe(
      TE.tryCatch(
        () => storage.find('provider', { provider: input.provider }),
        storageError,
      ),
      TE.chain((existing) => {
        const pluginRef = `surface-provider:${input.domain}`;
        if (existing.length > 0) {
          return TE.right(initializeAlreadyExists(input.provider, pluginRef));
        }
        return pipe(
          TE.tryCatch(
            async () => {
              const id = generateId();
              await storage.put('provider', id, {
                id,
                provider: input.provider,
                domain: input.domain,
                pluginRef,
                createdAt: nowISO(),
              });
              await storage.put('plugin-registry', pluginRef, {
                pluginRef,
                provider: input.provider,
                kind: 'binding-provider',
                registeredAt: nowISO(),
              });
            },
            storageError,
          ),
          TE.map(() => initializeOk(input.provider, pluginRef)),
        );
      }),
    ),

  // Create a binding between a source and target reference with a given direction.
  bind: (input, storage) =>
    pipe(
      TE.tryCatch(
        () => storage.find('binding', { sourceRef: input.sourceRef, targetRef: input.targetRef }),
        storageError,
      ),
      TE.chain((existing) => {
        if (existing.length > 0) {
          return TE.right(bindConflict(input.sourceRef, input.targetRef, 'binding already exists between source and target'));
        }
        const bindingId = generateId();
        return pipe(
          TE.tryCatch(
            async () => {
              await storage.put('binding', bindingId, {
                id: bindingId,
                sourceRef: input.sourceRef,
                targetRef: input.targetRef,
                direction: input.direction,
                synced: false,
                createdAt: nowISO(),
              });
            },
            storageError,
          ),
          TE.map(() => bindOk(bindingId, input.sourceRef, input.targetRef)),
        );
      }),
    ),

  // Synchronize the data flow for an existing binding.
  sync: (input, storage) =>
    pipe(
      TE.tryCatch(
        () => storage.get('binding', input.bindingId),
        storageError,
      ),
      TE.chain((result) => {
        if (result === null) {
          return TE.right(syncNotFound(input.bindingId, `binding '${input.bindingId}' not found`));
        }
        return pipe(
          TE.tryCatch(
            async () => {
              await storage.put('binding', input.bindingId, {
                ...result,
                synced: true,
                lastSyncedAt: nowISO(),
              });
            },
            storageError,
          ),
          TE.map(() => syncOk(input.bindingId, true)),
        );
      }),
    ),

  // Invoke the binding, pushing a payload through the data channel.
  invoke: (input, storage) =>
    pipe(
      TE.tryCatch(
        () => storage.get('binding', input.bindingId),
        storageError,
      ),
      TE.chain((result) => {
        if (result === null) {
          return TE.right(invokeNotFound(input.bindingId, `binding '${input.bindingId}' not found`));
        }
        return pipe(
          TE.tryCatch(
            async () => {
              const invocationId = generateId();
              await storage.put('invocation', invocationId, {
                id: invocationId,
                bindingId: input.bindingId,
                payload: input.payload,
                invokedAt: nowISO(),
              });
              return { invocationId, ...input.payload };
            },
            storageError,
          ),
          TE.map((resultData) => invokeOk(input.bindingId, resultData)),
        );
      }),
    ),

  // Remove a binding from the provider.
  unbind: (input, storage) =>
    pipe(
      TE.tryCatch(
        () => storage.get('binding', input.bindingId),
        storageError,
      ),
      TE.chain((result) => {
        if (result === null) {
          return TE.right(unbindNotFound(input.bindingId, `binding '${input.bindingId}' not found`));
        }
        return pipe(
          TE.tryCatch(
            () => storage.delete('binding', input.bindingId),
            storageError,
          ),
          TE.map(() => unbindOk(input.bindingId)),
        );
      }),
    ),
};
