// Auto-generated by Clef Clef Bind — cli target
// Concept: VariantExtractionProvider
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const variantExtractionProviderCommand = new Command('variant-extraction-provider')
  .description('Extract the set of completion variant tags reachable from a StorageProgram s branch structure by walking its instruction tree enabling static verification of sync coverage against the handler s actual behavior');

variantExtractionProviderCommand
  .command('analyze')
  .description('Walk the instruction tree . For each pure pureFrom terminal , extract the variant tag . For branch instructions , recurse into both arms and union the variant sets . Return the set of all reachable variant tags as a serialized JSON array , plus the total branch count for complexity analysis .')
  .requiredOption('--program <program>', 'Program')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VariantExtractionProvider', 'analyze', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const variantExtractionProviderCommandTree = {
  group: 'variant-extraction-provider',
  description: 'Extract the set of completion variant tags reachable from a StorageProgram s branch structure by walking its instruction tree enabling static verification of sync coverage against the handler s actual behavior',
  commands: [{ action: 'analyze', command: 'analyze' }],
};
