// Auto-generated by Clef Clef Bind — cli target
// Concept: DeployOrchestrator
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const deployOrchestratorCommand = new Command('deploy-orchestrator')
  .description('End to end deployment orchestrator that boots a kernel with all deployment concepts , compiles routing syncs , and executes the full deploy pipeline . Provider agnostic runtime selection is driven by the deploy manifest and routed via syncs');

deployOrchestratorCommand
  .command('deploy')
  .description('Full deployment pipeline completed : manifest parsed , plan created , validated , runtime provisioned , and deployed .')
  .requiredOption('--manifest-path <manifestPath>', 'Manifest Path')
  .requiredOption('--environment <environment>', 'Environment')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DeployOrchestrator', 'deploy', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

deployOrchestratorCommand
  .command('deploy-all')
  .description('All discoverable clef apps deployed to their configured runtimes , then cross app dependencies configured via env vars .')
  .requiredOption('--project-root <projectRoot>', 'Project Root')
  .requiredOption('--environment <environment>', 'Environment')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DeployOrchestrator', 'deployAll', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

deployOrchestratorCommand
  .command('status')
  .description('Current status of a deployment run .')
  .requiredOption('--run <run>', 'Run')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/DeployOrchestrator', 'status', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const deployOrchestratorCommandTree = {
  group: 'deploy-orchestrator',
  description: 'End to end deployment orchestrator that boots a kernel with all deployment concepts , compiles routing syncs , and executes the full deploy pipeline . Provider agnostic runtime selection is driven by the deploy manifest and routed via syncs',
  commands: [{ action: 'deploy', command: 'deploy' }, { action: 'deployAll', command: 'deploy-all' }, { action: 'status', command: 'status' }],
};
