// Auto-generated by Clef Clef Bind — cli target
// Concept: GenerationProvenance
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const generationProvenanceCommand = new Command('generation-provenance')
  .description('Tracks which generator produced which file , from what source 
 spec , with what configuration . Enables queries like what
    generated this handler? , if I change the scaffold generator,
    which files will be regenerated? , is this file hand-written
    or generated? , and show the generation chain from spec to
    final artifact.');

generationProvenanceCommand
  .command('record')
  .description('Record that a file was generated by a specific generator 
 from a source spec with given config . sourceSpecKind is 
 one of : concept , sync , derived , widget , theme , suite , 
 deploy , interface . generator is the concept name ( e . g . , 
 HandlerScaffoldGen , SurfaceComponentScaffoldGen ) .')
  .requiredOption('--output-file <outputFile>', 'Output File')
  .requiredOption('--generator <generator>', 'Generator')
  .requiredOption('--source-spec <sourceSpec>', 'Source Spec')
  .requiredOption('--source-spec-kind <sourceSpecKind>', 'Source Spec Kind')
  .requiredOption('--config <config>', 'Config')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'record', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

generationProvenanceCommand
  .command('get-by-file')
  .description('Get generation provenance for a file .')
  .requiredOption('--output-file <outputFile>', 'Output File')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'getByFile', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

generationProvenanceCommand
  .command('find-by-generator')
  .description('Return all files produced by a given generator . Result as 
 serialized JSON array of { outputFile , sourceSpec , generatedAt } .')
  .requiredOption('--generator <generator>', 'Generator')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findByGenerator', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

generationProvenanceCommand
  .command('find-by-source')
  .description('Return all files generated from a given source spec . Result 
 as serialized JSON array of { outputFile , generator , generatedAt } .')
  .requiredOption('--source-spec <sourceSpec>', 'Source Spec')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findBySource', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

generationProvenanceCommand
  .command('generation-chain')
  .description('Trace the full generation chain from source spec through 
 intermediate generators to final output . Result as serialized 
 JSON array of { step , input , generator , output } .')
  .requiredOption('--output-file <outputFile>', 'Output File')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'generationChain', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

generationProvenanceCommand
  .command('stale-files')
  .description('Return all generated files whose source spec has been 
 modified since last generation . Result as serialized JSON 
 array of { outputFile , sourceSpec , generator , generatedAt , 
 sourceModified } .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'staleFiles', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

generationProvenanceCommand
  .command('impact-of-generator-change')
  .description('Return all files that would be regenerated if a generator 
 changes . Result as serialized JSON array of { outputFile , 
 sourceSpec } .')
  .requiredOption('--generator <generator>', 'Generator')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'impactOfGeneratorChange', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

generationProvenanceCommand
  .command('is-generated')
  .description('This file was generated .')
  .requiredOption('--file <file>', 'File')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'isGenerated', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const generationProvenanceCommandTree = {
  group: 'generation-provenance',
  description: 'Tracks which generator produced which file , from what source 
 spec , with what configuration . Enables queries like what
    generated this handler? , if I change the scaffold generator,
    which files will be regenerated? , is this file hand-written
    or generated? , and show the generation chain from spec to
    final artifact.',
  commands: [{ action: 'record', command: 'record' }, { action: 'getByFile', command: 'get-by-file' }, { action: 'findByGenerator', command: 'find-by-generator' }, { action: 'findBySource', command: 'find-by-source' }, { action: 'generationChain', command: 'generation-chain' }, { action: 'staleFiles', command: 'stale-files' }, { action: 'impactOfGeneratorChange', command: 'impact-of-generator-change' }, { action: 'isGenerated', command: 'is-generated' }],
};
