// Auto-generated by Clef Clef Bind — cli target
// Concept: SurfaceComponentScaffoldGen
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const surfaceComponentScaffoldGenCommand = new Command('scaffold')
  .description('Generate Clef Surface headless component (widget, anatomy, machine, kit).');

surfaceComponentScaffoldGenCommand
  .command('component')
  .description('Scaffold a complete Clef Surface headless component with FSM, anatomy, and machine.')
  .requiredOption('-n, --name <name>', 'PascalCase component name')
  .option('-p, --parts <parts>', 'Comma-separated anatomy part names', 'root,trigger,content')
  .option('-s, --states <states>', 'Comma-separated FSM state names', 'idle,active')
  .option('-e, --events <events>', 'Comma-separated FSM event names', 'open,close')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  clef scaffold component --name Dialog --parts root,trigger,backdrop,content,title,closeTrigger --states closed,open --events open,close,escape  # Generate a dialog component')
  .addHelpText('after', '  clef scaffold component --name Tabs --parts root,list,trigger,content,indicator --states idle,focused,selected --events focus,select,blur  # Generate a tabs component')
  .addHelpText('after', '  clef scaffold component --name Card --parts root,header,body,footer --slots header,footer  # Generate with slots')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'generate', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

surfaceComponentScaffoldGenCommand
  .command('preview')
  .description('Dry-run: compute output files without writing. Uses Emitter content-addressing to show what would change.')
  .requiredOption('-n, --name <name>', 'PascalCase component name')
  .option('-p, --parts <parts>', 'Comma-separated anatomy part names')
  .requiredOption('--states <states>', 'States')
  .requiredOption('--events <events>', 'Events')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'preview', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

surfaceComponentScaffoldGenCommand
  .command('register')
  .description('Return static metadata for PluginRegistry 
 name : SurfaceComponentScaffoldGen 
 inputKind : ComponentConfig 
 outputKind : SurfaceComponent 
 capabilities : [ widget , anatomy , machine , slots ]')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'register', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const surfaceComponentScaffoldGenCommandTree = {
  group: 'scaffold',
  description: 'Generate Clef Surface headless component (widget, anatomy, machine, kit).',
  commands: [{ action: 'generate', command: 'component' }, { action: 'preview', command: 'preview' }, { action: 'register', command: 'register' }],
};
