// Auto-generated by Clef Clef Bind — mcp target
// Concept: Symbol
// Do not edit manually; regenerate with: clef interface generate

export const symbolTools = [
  {
    "type": "tool",
    "name": "symbol_register",
    "description": "Register symbol — Create a new symbol with a globally unique symbol string . \n Kind is one of : function , class , type , variable , concept , \n action , variant , state field , sync , config key .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "symbolString": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "definingFile": {
          "type": "string"
        }
      },
      "required": [
        "symbolString",
        "kind",
        "displayName",
        "definingFile"
      ]
    }
  },
  {
    "type": "tool",
    "name": "symbol_resolve",
    "description": "Resolve symbol — Resolve a symbol string to its registered symbol .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "symbolString": {
          "type": "string"
        }
      },
      "required": [
        "symbolString"
      ]
    }
  },
  {
    "type": "resource",
    "name": "symbol_find_by_kind",
    "uri": "urn:clef://symbols/{kind}",
    "description": "Find by kind symbol — Return all symbols of the given kind , optionally filtered \n by namespace . Results as serialized JSON array ."
  },
  {
    "type": "resource",
    "name": "symbol_find_by_file",
    "uri": "urn:clef://symbols/{file}",
    "description": "Find by file symbol — Return all symbols defined in the given file . \n Results as serialized JSON array ."
  },
  {
    "type": "tool",
    "name": "symbol_rename",
    "description": "Rename symbol — Rename a symbol and update all tracked occurrences .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "symbol": {
          "type": "string"
        },
        "newName": {
          "type": "string"
        }
      },
      "required": [
        "symbol",
        "newName"
      ]
    }
  },
  {
    "type": "resource",
    "name": "symbol_get",
    "uri": "urn:clef://symbols/{symbol}",
    "description": "Get symbol — Retrieve a symbol s metadata ."
  }
];
