// Auto-generated by Clef Clef Bind — mcp target
// Concept: SurfaceThemeScaffoldGen
// Do not edit manually; regenerate with: clef interface generate

export const surfaceThemeScaffoldGenTools = [
  {
    "type": "tool",
    "name": "surface_theme_scaffold_gen_generate",
    "description": "Generate surfacethemescaffoldgen — Theme scaffold generated with tokens and theme manifests .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "primaryColor": {
          "type": "string"
        },
        "fontFamily": {
          "type": "string"
        },
        "baseSize": {
          "type": "integer"
        },
        "scale": {
          "oneOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ]
        },
        "secondaryColor": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "borderRadius": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "mode": {
          "type": "string"
        },
        "extends": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "name",
        "primaryColor",
        "fontFamily",
        "baseSize",
        "scale",
        "secondaryColor",
        "borderRadius",
        "mode",
        "extends"
      ]
    }
  },
  {
    "type": "tool",
    "name": "surface_theme_scaffold_gen_preview",
    "description": "Preview surfacethemescaffoldgen — Dry run : compute output files without writing . Uses \n Emitter content addressing to classify each file as \n new , changed , or unchanged .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "primaryColor": {
          "type": "string"
        },
        "fontFamily": {
          "type": "string"
        },
        "baseSize": {
          "type": "integer"
        },
        "scale": {
          "oneOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ]
        },
        "secondaryColor": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "borderRadius": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        },
        "mode": {
          "type": "string"
        },
        "extends": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "name",
        "primaryColor",
        "fontFamily",
        "baseSize",
        "scale",
        "secondaryColor",
        "borderRadius",
        "mode",
        "extends"
      ]
    }
  },
  {
    "type": "tool",
    "name": "surface_theme_scaffold_gen_register",
    "description": "Register surfacethemescaffoldgen — Return static metadata for PluginRegistry . \n name : SurfaceThemeScaffoldGen \n inputKind : ThemeConfig \n outputKind : SurfaceTheme \n capabilities : [ palette , typography , spacing , motion , elevation , radius , extends , wcag ]",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  }
];
