// Authentication — conformance.test.ts
// Generated by NextjsGen. Do not edit manually.
// Verifies spec invariants using fp-ts assertions.

import { describe, it, expect } from 'vitest';
import * as TE from 'fp-ts/TaskEither';
import * as E from 'fp-ts/Either';
import { pipe } from 'fp-ts/function';

import { authenticationHandler } from './handler.js';
import type { AuthenticationStorage } from './types.js';

// In-memory storage for conformance tests
const createTestStorage = (): AuthenticationStorage => {
  const store = new Map<string, Map<string, Record<string, unknown>>>();
  return {
    get: async (relation, key) => store.get(relation)?.get(key) ?? null,
    put: async (relation, key, value) => {
      if (!store.has(relation)) store.set(relation, new Map());
      store.get(relation)!.set(key, value);
    },
    delete: async (relation, key) => store.get(relation)?.delete(key) ?? false,
    find: async (relation) => [...(store.get(relation)?.values() ?? [])],
  };
};

describe('Authentication conformance', () => {
  it('register creates new account, duplicate returns already_exists', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    // AFTER: register a new user
    const registerResult = await handler.register(
      { userId: 'u-test-001', credentials: 'secret123' },
      storage,
    )();
    expect(E.isRight(registerResult)).toBe(true);
    if (E.isRight(registerResult)) {
      expect(registerResult.right.variant).toBe('ok');
    }

    // THEN: duplicate register returns already_exists
    const dupResult = await handler.register(
      { userId: 'u-test-001', credentials: 'other' },
      storage,
    )();
    expect(E.isRight(dupResult)).toBe(true);
    if (E.isRight(dupResult)) {
      expect(dupResult.right.variant).toBe('already_exists');
    }
  });

  it('login succeeds with correct credentials', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    // Setup
    await handler.register(
      { userId: 'u-test-002', credentials: 'secret' },
      storage,
    )();

    // Assert: login with correct password
    const loginResult = await handler.login(
      { userId: 'u-test-002', credentials: 'secret' },
      storage,
    )();
    expect(E.isRight(loginResult)).toBe(true);
    if (E.isRight(loginResult)) {
      expect(loginResult.right.variant).toBe('ok');
      if (loginResult.right.variant === 'ok') {
        expect(loginResult.right.userId).toBe('u-test-002');
        expect(loginResult.right.token).toBeTruthy();
      }
    }
  });

  it('login fails with wrong credentials', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    // Setup
    await handler.register(
      { userId: 'u-test-003', credentials: 'secret' },
      storage,
    )();

    // Assert: login with wrong password
    const loginResult = await handler.login(
      { userId: 'u-test-003', credentials: 'wrong' },
      storage,
    )();
    expect(E.isRight(loginResult)).toBe(true);
    if (E.isRight(loginResult)) {
      expect(loginResult.right.variant).toBe('invalid_credentials');
    }
  });

  it('login fails for nonexistent user', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    const loginResult = await handler.login(
      { userId: 'ghost', credentials: 'anything' },
      storage,
    )();
    expect(E.isRight(loginResult)).toBe(true);
    if (E.isRight(loginResult)) {
      expect(loginResult.right.variant).toBe('invalid_credentials');
    }
  });

  it('logout succeeds for registered user', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    await handler.register(
      { userId: 'u-test-004', credentials: 'pass' },
      storage,
    )();

    const logoutResult = await handler.logout(
      { userId: 'u-test-004' },
      storage,
    )();
    expect(E.isRight(logoutResult)).toBe(true);
    if (E.isRight(logoutResult)) {
      expect(logoutResult.right.variant).toBe('ok');
    }
  });

  it('logout returns notfound for missing user', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    const logoutResult = await handler.logout(
      { userId: 'ghost' },
      storage,
    )();
    expect(E.isRight(logoutResult)).toBe(true);
    if (E.isRight(logoutResult)) {
      expect(logoutResult.right.variant).toBe('notfound');
    }
  });

  it('resetPassword generates token for existing user', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    await handler.register(
      { userId: 'u-test-005', credentials: 'pass' },
      storage,
    )();

    const resetResult = await handler.resetPassword(
      { userId: 'u-test-005' },
      storage,
    )();
    expect(E.isRight(resetResult)).toBe(true);
    if (E.isRight(resetResult)) {
      expect(resetResult.right.variant).toBe('ok');
      if (resetResult.right.variant === 'ok') {
        expect(resetResult.right.resetToken).toBeTruthy();
      }
    }
  });

  it('resetPassword returns notfound for missing user', async () => {
    const storage = createTestStorage();
    const handler = authenticationHandler;

    const resetResult = await handler.resetPassword(
      { userId: 'ghost' },
      storage,
    )();
    expect(E.isRight(resetResult)).toBe(true);
    if (E.isRight(resetResult)) {
      expect(resetResult.right.variant).toBe('notfound');
    }
  });
});
