// Authentication — route.ts
// Generated by NextjsGen. Do not edit manually.
// Next.js App Router Route Handler — maps HTTP to concept actions.
// Place at: app/api/authentication/route.ts

import { NextRequest, NextResponse } from 'next/server';
import * as TE from 'fp-ts/TaskEither';
import * as T from 'fp-ts/Task';
import * as E from 'fp-ts/Either';
import { pipe } from 'fp-ts/function';

import type { AuthenticationHandler, AuthenticationError } from './handler.js';
import type { AuthenticationStorage } from './types.js';

const errorResponse = (error: AuthenticationError, status = 422): NextResponse =>
  NextResponse.json({ errors: [{ code: error.code, message: error.message }] }, { status });

const successResponse = <T>(data: T, status = 200): NextResponse =>
  NextResponse.json(data, { status });

export const createAuthenticationRoute = (
  handler: AuthenticationHandler,
  storage: AuthenticationStorage,
) => {
  const dispatch = async (
    action: string,
    input: Record<string, unknown>,
  ): Promise<NextResponse> => {
    switch (action) {
      case 'register': {
        const result = await pipe(
          handler.register(input as any, storage),
          TE.fold(
            (error) => T.of(errorResponse(error)),
            (output) => T.of(
              output.variant === 'already_exists'
                ? NextResponse.json(output, { status: 409 })
                : NextResponse.json(output, { status: 201 }),
            ),
          ),
        )();
        return result;
      }

      case 'login': {
        const result = await pipe(
          handler.login(input as any, storage),
          TE.fold(
            (error) => T.of(errorResponse(error)),
            (output) => T.of(
              output.variant === 'invalid_credentials'
                ? NextResponse.json(output, { status: 401 })
                : NextResponse.json(output, { status: 200 }),
            ),
          ),
        )();
        return result;
      }

      case 'logout': {
        const result = await pipe(
          handler.logout(input as any, storage),
          TE.fold(
            (error) => T.of(errorResponse(error)),
            (output) => T.of(
              output.variant === 'notfound'
                ? NextResponse.json(output, { status: 404 })
                : NextResponse.json(output, { status: 200 }),
            ),
          ),
        )();
        return result;
      }

      case 'resetPassword': {
        const result = await pipe(
          handler.resetPassword(input as any, storage),
          TE.fold(
            (error) => T.of(errorResponse(error)),
            (output) => T.of(
              output.variant === 'notfound'
                ? NextResponse.json(output, { status: 404 })
                : NextResponse.json(output, { status: 200 }),
            ),
          ),
        )();
        return result;
      }

      default:
        return NextResponse.json(
          { errors: [{ code: 'UNKNOWN_ACTION', message: `Unknown action: ${action}` }] },
          { status: 404 },
        );
    }
  };

  const POST = async (request: NextRequest): Promise<NextResponse> => {
    const body = await request.json() as { action: string; input: Record<string, unknown> };
    return dispatch(body.action, body.input);
  };

  return { POST };
};
