// Auto-generated by Clef Clef Bind — mcp target
// Concept: InterfaceEntity
// Do not edit manually; regenerate with: clef interface generate

export const interfaceEntityTools = [
  {
    "type": "tool",
    "name": "interface_entity_register",
    "description": "Register interfaceentity — Register a parsed interface manifest . Extracts targets \n ( rest , graphql , grpc , cli , mcp , claude skills ) , SDK \n languages , concept overrides , and indexes all generated \n endpoints commands tools .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "manifest": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "source",
        "manifest"
      ]
    }
  },
  {
    "type": "resource",
    "name": "interface_entity_get",
    "uri": "urn:clef://interface-entitys/{name}",
    "description": "Get interfaceentity — Retrieve an interface entity by name ."
  },
  {
    "type": "resource-template",
    "name": "interface_entity_list_endpoints",
    "uriTemplate": "urn:clef://interface-entitys",
    "description": "List endpoints interfaceentity — Return all generated endpoints for a target ( rest , graphql , \n grpc ) . Result as serialized JSON array of { method , path , \n concept , action , params , returnType } ."
  },
  {
    "type": "resource-template",
    "name": "interface_entity_list_commands",
    "uriTemplate": "urn:clef://interface-entitys",
    "description": "List commands interfaceentity — Return all generated CLI commands . Result as serialized JSON \n array of { command , subcommand , concept , action , flags } ."
  },
  {
    "type": "resource-template",
    "name": "interface_entity_list_tools",
    "uriTemplate": "urn:clef://interface-entitys",
    "description": "List tools interfaceentity — Return all generated MCP tools . Result as serialized JSON \n array of { name , concept , action , inputSchema , description } ."
  },
  {
    "type": "resource-template",
    "name": "interface_entity_list_skills",
    "uriTemplate": "urn:clef://interface-entitys",
    "description": "List skills interfaceentity — Return all generated AI coding assistant skills . Result as \n serialized JSON array of { name , concept , triggerDescription , \n targetDirs } ."
  },
  {
    "type": "resource",
    "name": "interface_entity_find_by_concept",
    "uri": "urn:clef://interface-entitys/{concept}",
    "description": "Find by concept interfaceentity — Return all interface exposures for a concept across all \n registered interfaces and targets . Result as serialized JSON \n array of { interface , target , endpoint , concept , action } ."
  },
  {
    "type": "resource",
    "name": "interface_entity_find_by_action",
    "uri": "urn:clef://interface-entitys/{concept}",
    "description": "Find by action interfaceentity — Return all interface exposures for a specific concept action . \n Result as serialized JSON array of { interface , target , kind , \n path , method } ."
  },
  {
    "type": "tool",
    "name": "interface_entity_trace_endpoint_to_action",
    "description": "Trace endpoint to action interfaceentity — Given an API endpoint ( e . g . , POST api users ) , trace it \n back to the concept , action , handler , and source file that \n implements it . Full provenance chain .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "target": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "method": {
          "type": "string"
        }
      },
      "required": [
        "target",
        "path",
        "method"
      ]
    }
  },
  {
    "type": "tool",
    "name": "interface_entity_trace_tool_to_action",
    "description": "Trace tool to action interfaceentity — Given an MCP tool name , trace it back to the concept , \n action , handler , and source file that implements it .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "toolName": {
          "type": "string"
        }
      },
      "required": [
        "toolName"
      ]
    }
  },
  {
    "type": "tool",
    "name": "interface_entity_generated_schemas",
    "description": "Generated schemas interfaceentity — Return all generated API schemas ( OpenAPI , AsyncAPI , GraphQL \n SDL , Proto ) . Result as serialized JSON array of { format , \n file , conceptCount , endpointCount } .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "interface": {
          "type": "string"
        }
      },
      "required": [
        "interface"
      ]
    }
  },
  {
    "type": "tool",
    "name": "interface_entity_validate_against_specs",
    "description": "Validate against specs interfaceentity — Validate that all concepts referenced in the interface \n exist as ConceptEntities and all actions are declared .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "interface": {
          "type": "string"
        }
      },
      "required": [
        "interface"
      ]
    }
  }
];
