// Auto-generated by Clef Clef Bind — mcp target
// Concept: DevServer
// Do not edit manually; regenerate with: clef interface generate

export const devServerTools = [
  {
    "type": "tool",
    "name": "dev_server_start",
    "description": "Start devserver — Development server started . Resource is tracking \n the specified directories for changes .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "port": {
          "type": "integer"
        },
        "watchDirs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "port",
        "watchDirs"
      ]
    }
  },
  {
    "type": "tool",
    "name": "dev_server_stop",
    "description": "Stop devserver — Server stopped cleanly .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "session": {
          "type": "string"
        }
      },
      "required": [
        "session"
      ]
    }
  },
  {
    "type": "tool",
    "name": "dev_server_status",
    "description": "Status devserver — Server is running with current stats .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "session": {
          "type": "string"
        }
      },
      "required": [
        "session"
      ]
    }
  }
];
