// Auto-generated by Clef Clef Bind — cli target
// Concept: ProgramCache
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const programCacheCommand = new Command('program-cache')
  .description('Memoize StorageProgram execution results keyed by program fingerprint and storage state hash . Enables incremental re evaluation where only changed programs or changed state invalidates cached results');

programCacheCommand
  .command('lookup')
  .description('A cached result exists for this program and state combination .')
  .requiredOption('--program-hash <programHash>', 'Program Hash')
  .requiredOption('--state-hash <stateHash>', 'State Hash')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ProgramCache', 'lookup', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

programCacheCommand
  .command('store')
  .description('Result cached under the given program and state hashes .')
  .requiredOption('--program-hash <programHash>', 'Program Hash')
  .requiredOption('--state-hash <stateHash>', 'State Hash')
  .requiredOption('--result <result>', 'Result')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ProgramCache', 'store', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

programCacheCommand
  .command('invalidate-by-state')
  .description('Remove all entries whose stateHash matches , returning the count of evicted entries . Called when storage state changes .')
  .requiredOption('--state-hash <stateHash>', 'State Hash')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ProgramCache', 'invalidateByState', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

programCacheCommand
  .command('invalidate-by-program')
  .description('Remove all entries for the given program hash , returning the count of evicted entries . Called when handler code is redeployed .')
  .requiredOption('--program-hash <programHash>', 'Program Hash')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ProgramCache', 'invalidateByProgram', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

programCacheCommand
  .command('stats')
  .description('Return aggregate cache statistics : total entries , hit rate as a percentage string , and approximate memory usage .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ProgramCache', 'stats', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const programCacheCommandTree = {
  group: 'program-cache',
  description: 'Memoize StorageProgram execution results keyed by program fingerprint and storage state hash . Enables incremental re evaluation where only changed programs or changed state invalidates cached results',
  commands: [{ action: 'lookup', command: 'lookup' }, { action: 'store', command: 'store' }, { action: 'invalidateByState', command: 'invalidate-by-state' }, { action: 'invalidateByProgram', command: 'invalidate-by-program' }, { action: 'stats', command: 'stats' }],
};
