// Auto-generated by Clef Clef Bind — mcp target
// Concept: InfrastructureCore
// Do not edit manually; regenerate with: clef interface generate

export const infrastructureCoreTools = [
  {
    "type": "tool",
    "name": "infrastructure_core_register_plugin",
    "description": "Register plugin infrastructurecore — registerPlugin succeeded",
    "inputSchema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "metadata": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "name",
        "metadata"
      ]
    }
  },
  {
    "type": "tool",
    "name": "infrastructure_core_discover_plugins",
    "description": "Discover plugins infrastructurecore — discoverPlugins succeeded",
    "inputSchema": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        }
      },
      "required": [
        "type"
      ]
    }
  },
  {
    "type": "tool",
    "name": "infrastructure_core_invalidate_cache",
    "description": "Invalidate cache infrastructurecore — invalidateCache succeeded",
    "inputSchema": {
      "type": "object",
      "properties": {
        "bin": {
          "type": "string"
        },
        "key": {
          "type": "string"
        }
      },
      "required": [
        "bin",
        "key"
      ]
    }
  },
  {
    "type": "tool",
    "name": "infrastructure_core_publish_event",
    "description": "Publish event infrastructurecore — publishEvent succeeded",
    "inputSchema": {
      "type": "object",
      "properties": {
        "event": {
          "type": "string"
        },
        "payload": {
          "type": "string"
        }
      },
      "required": [
        "event",
        "payload"
      ]
    }
  },
  {
    "type": "tool",
    "name": "infrastructure_core_validate",
    "description": "Validate infrastructurecore — validate succeeded",
    "inputSchema": {
      "type": "object",
      "properties": {
        "validator": {
          "type": "string"
        },
        "data": {
          "type": "string"
        }
      },
      "required": [
        "validator",
        "data"
      ]
    }
  },
  {
    "type": "resource",
    "name": "infrastructure_core_get_cached",
    "uri": "derived:://infrastructure-cores/{bin}",
    "description": "Get cached infrastructurecore — getCached query result"
  },
  {
    "type": "resource",
    "name": "infrastructure_core_get_plugin_definitions",
    "uri": "derived:://infrastructure-cores/{type}",
    "description": "Get plugin definitions infrastructurecore — getPluginDefinitions query result"
  }
];
