// Auto-generated by Clef Clef Bind — cli target
// Concept: ConceptScaffoldGen
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const conceptScaffoldGenCommand = new Command('scaffold')
  .description('Generate concept specification (.concept) file with annotations, state groups, and capabilities.');

conceptScaffoldGenCommand
  .command('concept')
  .description('Scaffold a .concept file with annotations, state (groups, enums, records), actions, capabilities, and register().')
  .requiredOption('-n, --name <name>', 'PascalCase concept name')
  .requiredOption('--type-param <typeParam>', 'Type Param')
  .option('--purpose <purpose>', 'Purpose description')
  .requiredOption('--state-fields <stateFields>', 'State Fields')
  .option('-a, --actions <actions>', 'Comma-separated action names')
  .option('--version <version>', 'Spec version number for @version annotation')
  .option('--gate <gate>', 'Add @gate annotation for async-gated concepts')
  .option('--capabilities <capabilities>', 'Comma-separated capability names for capabilities block')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  clef scaffold concept --name User --actions create,update,delete  # Scaffold a basic concept')
  .addHelpText('after', '  clef scaffold concept --name Article --param A --category domain  # Scaffold with custom type parameter')
  .addHelpText('after', '  clef scaffold concept --name Bookmark --purpose 'Save and organize references.'  # Scaffold with purpose')
  .addHelpText('after', '  clef scaffold concept --name Approval --version 2 --gate --capabilities search,export,bulk  # Scaffold with version, gate, and capabilities')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'generate', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

conceptScaffoldGenCommand
  .command('preview')
  .description('Dry-run: compute output files without writing. Uses Emitter content-addressing to show what would change.')
  .requiredOption('-n, --name <name>', 'PascalCase concept name')
  .requiredOption('--type-param <typeParam>', 'Type Param')
  .requiredOption('--purpose <purpose>', 'Purpose')
  .requiredOption('--state-fields <stateFields>', 'State Fields')
  .requiredOption('--actions <actions>', 'Actions')
  .requiredOption('--version <version>', 'Version')
  .requiredOption('--gate <gate>', 'Gate')
  .requiredOption('--capabilities <capabilities>', 'Capabilities')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'preview', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

conceptScaffoldGenCommand
  .command('register')
  .description('Return static metadata for PluginRegistry . 
 name : ConceptScaffoldGen 
 inputKind : ConceptConfig 
 outputKind : ConceptSpec 
 capabilities : [ concept-spec , state-fields , state-groups , actions , 
 invariants , version-annotation , gate-annotation , 
 capabilities-block , enum-types , record-types , 
 list-option-wrappers , all-primitives ]')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'register', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const conceptScaffoldGenCommandTree = {
  group: 'scaffold',
  description: 'Generate concept specification (.concept) file with annotations, state groups, and capabilities.',
  commands: [{ action: 'generate', command: 'concept' }, { action: 'preview', command: 'preview' }, { action: 'register', command: 'register' }],
};
