// Auto-generated by Clef Clef Bind — cli target
// Concept: VariantEntity
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const variantEntityCommand = new Command('variant-entity')
  .description('Action return variant as a first class branching point in sync chains . Enables dead variant detection and sync coverage analysis identifying variants that no sync pattern matches on');

variantEntityCommand
  .command('register')
  .description('Register a variant extracted from an action in a concept spec . Fields is serialized JSON array of { name , typeExpr } .')
  .requiredOption('--action <action>', 'Action')
  .requiredOption('--tag <tag>', 'Tag')
  .requiredOption('--fields <fields>', 'Fields')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VariantEntity', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

variantEntityCommand
  .command('matching-syncs')
  .description('Return all syncs whose when pattern matches this variant s tag . Results as serialized JSON array .')
  .requiredOption('--variant <variant>', 'Variant')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VariantEntity', 'matchingSyncs', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

variantEntityCommand
  .command('is-dead')
  .description('This variant has no sync matching it and or no runtime occurrences . Both values are true or false .')
  .requiredOption('--variant <variant>', 'Variant')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VariantEntity', 'isDead', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

variantEntityCommand
  .command('get')
  .description('Retrieve variant entity metadata .')
  .requiredOption('--variant <variant>', 'Variant')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VariantEntity', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const variantEntityCommandTree = {
  group: 'variant-entity',
  description: 'Action return variant as a first class branching point in sync chains . Enables dead variant detection and sync coverage analysis identifying variants that no sync pattern matches on',
  commands: [{ action: 'register', command: 'register' }, { action: 'matchingSyncs', command: 'matching-syncs' }, { action: 'isDead', command: 'is-dead' }, { action: 'get', command: 'get' }],
};
