// Auto-generated by Clef Clef Bind — cli target
// Concept: CommutativityProvider
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const commutativityProviderCommand = new Command('commutativity-provider')
  .description('Determine whether two StoragePrograms commute , meaning they produce the same result regardless of execution order . Enables safe concurrent execution and parallel FlowTrace branch tracing');

commutativityProviderCommand
  .command('check')
  .description('Compare the read and write sets of both programs . If neither program s write set overlaps the other s read or write set , the programs commute . Returns the determination and reasoning .')
  .requiredOption('--program-a <programA>', 'Program A')
  .requiredOption('--program-b <programB>', 'Program B')
  .requiredOption('--read-write-sets-a <readWriteSetsA>', 'Read Write Sets A')
  .requiredOption('--read-write-sets-b <readWriteSetsB>', 'Read Write Sets B')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/CommutativityProvider', 'check', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const commutativityProviderCommandTree = {
  group: 'commutativity-provider',
  description: 'Determine whether two StoragePrograms commute , meaning they produce the same result regardless of execution order . Enables safe concurrent execution and parallel FlowTrace branch tracing',
  commands: [{ action: 'check', command: 'check' }],
};
