// Auto-generated by Clef Clef Bind — cli target
// Concept: RetentionPolicy
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const retentionPolicyCommand = new Command('retention-policy')
  .description('Govern how long versions and records must be kept and when they may 
 be disposed , including legal hold suspension of normal disposition . 
 A record under active legal hold can never be disposed regardless 
 of retention period expiration .');

retentionPolicyCommand
  .command('set-retention')
  .description('Retention policy created for the given record type .')
  .requiredOption('--record-type <recordType>', 'Record Type')
  .requiredOption('--period <period>', 'Period')
  .requiredOption('--unit <unit>', 'Unit')
  .requiredOption('--disposition-action <dispositionAction>', 'Disposition Action')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'setRetention', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

retentionPolicyCommand
  .command('apply-hold')
  .description('Legal hold applied . All records matching scope pattern are held .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--scope <scope>', 'Scope')
  .requiredOption('--reason <reason>', 'Reason')
  .requiredOption('--issuer <issuer>', 'Issuer')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'applyHold', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

retentionPolicyCommand
  .command('release-hold')
  .description('Hold released . Records revert to normal retention rules .')
  .requiredOption('--hold-id <holdId>', 'Hold Id')
  .requiredOption('--released-by <releasedBy>', 'Released By')
  .requiredOption('--reason <reason>', 'Reason')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'releaseHold', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

retentionPolicyCommand
  .command('check-disposition')
  .description('Record has passed its retention period and has no active holds .')
  .requiredOption('--record <record>', 'Record')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'checkDisposition', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

retentionPolicyCommand
  .command('dispose')
  .description('Record disposed per its policy . Disposition logged .')
  .requiredOption('--record <record>', 'Record')
  .requiredOption('--disposed-by <disposedBy>', 'Disposed By')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'dispose', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

retentionPolicyCommand
  .command('audit-log')
  .description('Returns disposition log , filtered to specific record if provided .')
  .requiredOption('--record <record>', 'Record')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'auditLog', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const retentionPolicyCommandTree = {
  group: 'retention-policy',
  description: 'Govern how long versions and records must be kept and when they may 
 be disposed , including legal hold suspension of normal disposition . 
 A record under active legal hold can never be disposed regardless 
 of retention period expiration .',
  commands: [{ action: 'setRetention', command: 'set-retention' }, { action: 'applyHold', command: 'apply-hold' }, { action: 'releaseHold', command: 'release-hold' }, { action: 'checkDisposition', command: 'check-disposition' }, { action: 'dispose', command: 'dispose' }, { action: 'auditLog', command: 'audit-log' }],
};
