// Auto-generated by Clef Clef Bind — mcp target
// Concept: ApiSurface
// Do not edit manually; regenerate with: clef interface generate

export const apiSurfaceTools = [
  {
    "type": "tool",
    "name": "api_surface_compose",
    "description": "Compose apisurface — Merge per concept generated outputs into a unified surface . \n Create shared entrypoint ( router , schema , command root , etc . ) . \n Deduplicate shared types . Apply suite level middleware .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "suite": {
          "type": "string"
        },
        "target": {
          "type": "string"
        },
        "outputs": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "suite",
        "target",
        "outputs"
      ]
    }
  },
  {
    "type": "tool",
    "name": "api_surface_entrypoint",
    "description": "Entrypoint apisurface — Return the composed entrypoint file content .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "surface": {
          "type": "string"
        }
      },
      "required": [
        "surface"
      ]
    }
  }
];
