// Auto-generated by Clef Clef Bind — mcp target
// Concept: A11yAdaptProvider
// Do not edit manually; regenerate with: clef interface generate

export const a11yAdaptProviderTools = [
  {
    "type": "tool",
    "name": "a11y_adapt_provider_register",
    "description": "Register a11yadaptprovider — Return static metadata for PluginRegistry . \n name : A11yAdaptProvider \n kind : a11y-adapt \n capabilities : [ aria-modification , aria-injection , keyboard-adapt , focus-adapt ]",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "required": []
    }
  },
  {
    "type": "tool",
    "name": "a11y_adapt_provider_apply",
    "description": "Apply a11yadaptprovider — Apply modifications to matching instructions first , then \n insert additions before the terminal pure instruction . \n Modifications match on partial instruction patterns and \n merge new fields . Additions are complete instructions \n injected into the sequence . Returns the new serialized \n program and the updated list of applied transforms .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "program": {
          "type": "string"
        },
        "spec": {
          "type": "string"
        }
      },
      "required": [
        "program",
        "spec"
      ]
    }
  }
];
