// Auto-generated by Clef Clef Bind — cli target
// Concept: VercelRuntime
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const vercelRuntimeCommand = new Command('vercel-runtime')
  .description('Manage Vercel project deployments . Owns project configurations , deployment URLs , edge regions , and serverless function settings');

vercelRuntimeCommand
  .command('provision')
  .description('Vercel project created with specified framework .')
  .requiredOption('--concept <concept>', 'Concept')
  .requiredOption('--team-id <teamId>', 'Team Id')
  .requiredOption('--framework <framework>', 'Framework')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VercelRuntime', 'provision', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

vercelRuntimeCommand
  .command('deploy')
  .description('Build completed and deployment created .')
  .requiredOption('--project <project>', 'Project')
  .requiredOption('--source-directory <sourceDirectory>', 'Source Directory')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VercelRuntime', 'deploy', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

vercelRuntimeCommand
  .command('set-traffic-weight')
  .description('Traffic split between current and previous deployments .')
  .requiredOption('--project <project>', 'Project')
  .requiredOption('--weight <weight>', 'Weight')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VercelRuntime', 'setTrafficWeight', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

vercelRuntimeCommand
  .command('rollback')
  .description('Production alias pointed to previous deployment .')
  .requiredOption('--project <project>', 'Project')
  .requiredOption('--target-deployment-id <targetDeploymentId>', 'Target Deployment Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VercelRuntime', 'rollback', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

vercelRuntimeCommand
  .command('destroy')
  .description('Project and all deployments deleted .')
  .requiredOption('--project <project>', 'Project')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/VercelRuntime', 'destroy', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const vercelRuntimeCommandTree = {
  group: 'vercel-runtime',
  description: 'Manage Vercel project deployments . Owns project configurations , deployment URLs , edge regions , and serverless function settings',
  commands: [{ action: 'provision', command: 'provision' }, { action: 'deploy', command: 'deploy' }, { action: 'setTrafficWeight', command: 'set-traffic-weight' }, { action: 'rollback', command: 'rollback' }, { action: 'destroy', command: 'destroy' }],
};
