// Auto-generated by Clef Clef Bind — mcp target
// Concept: Projection
// Do not edit manually; regenerate with: clef interface generate

export const projectionTools = [
  {
    "type": "tool",
    "name": "projection_project",
    "description": "Project projection — Parse interface annotations . Merge with ConceptManifest . \n Compute resource mappings from state relations and action \n signatures . Bind traits to actions . Resolve cross concept \n type references within the suite . Enrichment data from \n workflows , annotations , and target configs is serialized \n as opaque JSON into the content field .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "manifest": {
          "type": "string"
        },
        "annotations": {
          "type": "string"
        }
      },
      "required": [
        "manifest",
        "annotations"
      ]
    }
  },
  {
    "type": "tool",
    "name": "projection_validate",
    "description": "Validate projection — All annotations resolve . Resource mappings are consistent . \n No breaking changes from previous generation ( if history exists ) .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "projection": {
          "type": "string"
        }
      },
      "required": [
        "projection"
      ]
    }
  },
  {
    "type": "tool",
    "name": "projection_diff",
    "description": "Diff projection — Compare two projections . Used for breaking change detection \n and changelog generation .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "projection": {
          "type": "string"
        },
        "previous": {
          "type": "string"
        }
      },
      "required": [
        "projection",
        "previous"
      ]
    }
  },
  {
    "type": "tool",
    "name": "projection_infer_resources",
    "description": "Infer resources projection — Auto derive REST resource mappings from state relations \n and action signatures . Actions named create add produce POST , \n delete remove produce DELETE , list find produce GET , \n update edit produce PUT . Non CRUD actions produce POST \n to resource { id } action name .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "projection": {
          "type": "string"
        }
      },
      "required": [
        "projection"
      ]
    }
  }
];
