// ============================================================
// TestGenSwift Provider — Functional Style
//
// Renders a language-neutral TestPlan into Swift test code using
// SwiftCheck for PBT and XCTest for conformance tests.
//
// See Architecture doc Sections 7.1, 7.2
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, put, find, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import type { TestPlan, TestPlanAction } from './test-gen.handler.ts';

const RESULTS = 'test-gen-swift-results';

type Result = { variant: string; [key: string]: unknown };

let idCounter = 0;
function nextId(): string {
  return `tgsw-${++idCounter}`;
}

export function resetTestGenSwiftCounter(): void {
  idCounter = 0;
}

function toPascal(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function toCamel(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function defaultInput(params: Array<{ name: string; type: string }>): string {
  return params.map(p => {
    const t = p.type.toLowerCase();
    if (t === 'string') return `${toCamel(p.name)}: "test_${toCamel(p.name)}"`;
    if (t === 'int' || t === 'number') return `${toCamel(p.name)}: 1`;
    if (t === 'bool' || t === 'boolean') return `${toCamel(p.name)}: true`;
    return `${toCamel(p.name)}: "test"`;
  }).join(', ');
}

function renderSwiftTests(plan: TestPlan): string {
  const className = `${toPascal(plan.conceptName)}ConformanceTests`;
  const lines: string[] = [];

  lines.push('// Auto-generated by TestGenSwift from concept spec invariants.');
  lines.push('');
  lines.push('import XCTest');
  lines.push('import SwiftCheck');
  lines.push(`@testable import ${toPascal(plan.conceptName)}`);
  lines.push('');
  lines.push(`final class ${className}: XCTestCase {`);
  lines.push('');

  // Structural tests per action
  for (const action of plan.actions) {
    renderSwiftActionTests(lines, plan.conceptName, action);
  }

  // Example conformance tests
  for (const example of plan.examples) {
    const fnName = toCamel(example.name.replace(/[^a-zA-Z0-9]/g, '_'));
    lines.push(`    func testExample_${fnName}() {`);
    for (const step of example.steps) {
      const input = Object.entries(step.input)
        .map(([k, v]) => `${toCamel(k)}: "${v}"`)
        .join(', ');
      lines.push(`        let result = ${toCamel(plan.conceptName)}.${toCamel(step.action)}(${input})`);
      if (step.expectedVariant) {
        lines.push(`        XCTAssertEqual(result.variant, "${step.expectedVariant}")`);
      }
    }
    lines.push('    }');
    lines.push('');
  }

  // Forall properties via SwiftCheck
  for (const prop of plan.properties) {
    const fnName = toCamel(prop.name.replace(/[^a-zA-Z0-9]/g, '_'));
    lines.push(`    func testForall_${fnName}() {`);
    lines.push(`        property("${prop.name}") <- forAll { (input: String) in`);
    for (const step of prop.steps) {
      lines.push(`            let result = ${toCamel(plan.conceptName)}.${toCamel(step.action)}(input)`);
      lines.push('            return !result.variant.isEmpty');
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('');
  }

  // State invariant tests
  for (const inv of plan.stateInvariants) {
    const fnName = toCamel(inv.name.replace(/[^a-zA-Z0-9]/g, '_'));
    lines.push(`    func test${toPascal(inv.kind)}_${fnName}() {`);
    if (plan.actions.length > 0) {
      const action = plan.actions[0];
      const input = defaultInput(action.params);
      lines.push(`        let result = ${toCamel(plan.conceptName)}.${toCamel(action.name)}(${input})`);
      lines.push('        XCTAssertFalse(result.variant.isEmpty)');
    }
    lines.push(`        // ${inv.kind}: ${inv.name}`);
    lines.push('    }');
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function renderSwiftActionTests(lines: string[], conceptName: string, action: TestPlanAction): void {
  const input = defaultInput(action.params);

  lines.push(`    func test${toPascal(action.name)}_returnsValidVariant() {`);
  lines.push(`        let result = ${toCamel(conceptName)}.${toCamel(action.name)}(${input})`);
  lines.push('        XCTAssertFalse(result.variant.isEmpty)');
  const validVariants = action.variants.map(v => `"${v}"`).join(', ');
  lines.push(`        XCTAssertTrue([${validVariants}].contains(result.variant))`);
  lines.push('    }');
  lines.push('');
}

export const testGenSwiftHandler: FunctionalConceptHandler = {

  render(input: Record<string, unknown>) {
    const testPlanJson = input.test_plan as string;
    const outputPath = input.output_path as string;

    if (!testPlanJson || !outputPath) {
      return complete(createProgram(), 'invalid', { message: 'test_plan and output_path are required' }) as StorageProgram<Result>;
    }

    let plan: TestPlan;
    try { plan = JSON.parse(testPlanJson); } catch {
      return complete(createProgram(), 'invalid', { message: 'Failed to parse test_plan JSON' }) as StorageProgram<Result>;
    }

    if (!plan.conceptName || !plan.actions) {
      return complete(createProgram(), 'invalid', { message: 'TestPlan missing required fields' }) as StorageProgram<Result>;
    }

    const renderedCode = renderSwiftTests(plan);
    const testCount = (renderedCode.match(/func test/g) || []).length;
    const id = nextId();

    let p = createProgram();
    p = put(p, RESULTS, id, {
      id, test_plan: testPlanJson, rendered_code: renderedCode,
      file_path: outputPath, rendered_at: new Date().toISOString(), test_count: testCount,
    });

    return complete(p, 'ok', {
      result: id, rendered_code: renderedCode, file_path: outputPath, test_count: testCount,
    }) as StorageProgram<Result>;
  },

  renderBatch(input: Record<string, unknown>) {
    const plansJson = input.test_plans as string;
    if (!plansJson) return complete(createProgram(), 'error', { message: 'test_plans required' }) as StorageProgram<Result>;

    let items: Array<{ test_plan: string; output_path: string }>;
    try { items = JSON.parse(plansJson); } catch {
      return complete(createProgram(), 'error', { message: 'Invalid JSON' }) as StorageProgram<Result>;
    }

    let p = createProgram();
    let totalTests = 0;
    const results: Array<{ file_path: string; test_count: number }> = [];
    for (const item of items) {
      let plan: TestPlan;
      try { plan = JSON.parse(item.test_plan); } catch { continue; }
      if (!plan.conceptName || !plan.actions) continue;
      const code = renderSwiftTests(plan);
      const tc = (code.match(/func test/g) || []).length;
      const id = nextId();
      p = put(p, RESULTS, id, { id, rendered_code: code, file_path: item.output_path, test_count: tc });
      results.push({ file_path: item.output_path, test_count: tc });
      totalTests += tc;
    }
    return complete(p, 'ok', { results: JSON.stringify(results), total_files: results.length, total_tests: totalTests }) as StorageProgram<Result>;
  },

  listRendered(input: Record<string, unknown>) {
    void input;
    let p = createProgram();
    p = find(p, RESULTS, {}, 'allResults');
    return complete(p, 'ok', { results: '[]' }) as StorageProgram<Result>;
  },
};
