// @clef-handler style=imperative
// ============================================================
// TestGenRust Provider — Functional Style
//
// Renders a language-neutral TestPlan into Rust test code using
// proptest for PBT and cargo-fuzz for fuzz harnesses.
//
// See Architecture doc Sections 7.1, 7.2
// ============================================================

import type { FunctionalConceptHandler } from '../../../../runtime/functional-handler.ts';
import {
  createProgram, put, find, complete,
  type StorageProgram,
} from '../../../../runtime/storage-program.ts';
import type { TestPlan, TestPlanAction } from './test-gen.handler.ts';

const RESULTS = 'test-gen-rust-results';

type Result = { variant: string; [key: string]: unknown };

let idCounter = 0;
function nextId(): string {
  return `tgrs-${++idCounter}`;
}

export function resetTestGenRustCounter(): void {
  idCounter = 0;
}

function toSnake(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[\s-]+/g, '_')
    .toLowerCase();
}

function defaultInput(params: Array<{ name: string; type: string }>): string {
  return params.map(p => {
    const t = p.type.toLowerCase();
    if (t === 'string') return `${toSnake(p.name)}: "test_${toSnake(p.name)}".to_string()`;
    if (t === 'int' || t === 'number') return `${toSnake(p.name)}: 1`;
    if (t === 'bool' || t === 'boolean') return `${toSnake(p.name)}: true`;
    return `${toSnake(p.name)}: "test".to_string()`;
  }).join(', ');
}

function fixtureInputRust(input: Record<string, unknown>): string {
  return Object.entries(input)
    .map(([k, v]) => {
      if (typeof v === 'string') return `${toSnake(k)}: "${v}".to_string()`;
      if (typeof v === 'boolean') return `${toSnake(k)}: ${v}`;
      if (typeof v === 'number') return `${toSnake(k)}: ${v}`;
      return `${toSnake(k)}: serde_json::json!(${JSON.stringify(v)}).to_string()`;
    }).join(', ');
}

function bestInput(action: TestPlanAction): string {
  const okFixture = action.fixtures?.find(f => f.expectedVariant === 'ok');
  if (okFixture) return fixtureInputRust(okFixture.input);
  return defaultInput(action.params);
}

function renderRustTests(plan: TestPlan): string {
  const modName = toSnake(plan.conceptName);
  const lines: string[] = [];

  lines.push('// Auto-generated by TestGenRust from concept spec invariants.');
  lines.push('');
  lines.push('use proptest::prelude::*;');
  lines.push(`use crate::${modName}::*;`);
  lines.push('');

  // Structural tests per action
  for (const action of plan.actions) {
    renderRustActionTests(lines, modName, action);
  }

  // Example conformance tests
  for (const example of plan.examples) {
    const fnName = toSnake(example.name).replace(/[^a-z0-9_]/g, '_');
    lines.push('#[test]');
    lines.push(`fn test_example_${fnName}() {`);
    lines.push(`    // Example: ${example.name}`);
    for (const step of example.steps) {
      const input = Object.entries(step.input)
        .map(([k, v]) => `${toSnake(k)}: "${v}".to_string()`)
        .join(', ');
      lines.push(`    let result = ${toSnake(step.action)}(${input});`);
      if (step.expectedVariant) {
        lines.push(`    assert_eq!(result.variant, "${step.expectedVariant}");`);
      }
    }
    lines.push('}');
    lines.push('');
  }

  // Forall properties via proptest with typed strategies
  for (const prop of plan.properties) {
    const fnName = toSnake(prop.name).replace(/[^a-z0-9_]/g, '_');
    lines.push('proptest! {');
    lines.push('    #[test]');

    // Build typed strategy from quantifiers
    const stratParts: string[] = [];
    const varParts: string[] = [];
    for (const q of prop.quantifiers) {
      if (q.domainType === 'set_literal' && q.values) {
        const vals = q.values.map(v => `Just("${v}".to_string())`).join(', ');
        stratParts.push(`${q.variable} in prop_oneof![${vals}]`);
      } else {
        stratParts.push(`${q.variable} in "[a-z]{1,20}"`);
      }
      varParts.push(q.variable);
    }
    if (stratParts.length === 0) {
      stratParts.push('input in "[a-z]{1,20}"');
      varParts.push('input');
    }
    lines.push(`    fn prop_${fnName}(${stratParts.join(', ')}) {`);
    lines.push(`        // Property: ${prop.name}`);
    for (const step of prop.steps) {
      const args = varParts.map(v => `${v}.clone()`).join(', ');
      lines.push(`        let result = ${toSnake(step.action)}(${args});`);
      lines.push('        prop_assert!(result.variant.len() > 0);');
      if (step.expectedVariant) {
        lines.push(`        prop_assert_eq!(result.variant, "${step.expectedVariant}");`);
      }
    }
    lines.push('    }');
    lines.push('}');
    lines.push('');
  }

  // Fuzz harness via cargo-fuzz / libfuzzer
  if (plan.actions.length > 0) {
    lines.push('// ── cargo-fuzz harness ──────────────────────────────────');
    lines.push('// Place in fuzz/fuzz_targets/ and run with: cargo fuzz run');
    lines.push('');
    lines.push('#[cfg(fuzzing)]');
    lines.push('use libfuzzer_sys::fuzz_target;');
    lines.push('');
    lines.push('#[cfg(fuzzing)]');
    lines.push(`use arbitrary::Arbitrary;`);
    lines.push('');
    lines.push('#[cfg(fuzzing)]');
    lines.push('#[derive(Arbitrary, Debug)]');
    lines.push(`enum ${plan.conceptName}Action {`);
    for (const action of plan.actions) {
      const fields = action.params.map(p => {
        const t = p.type.toLowerCase();
        if (t === 'int' || t === 'number') return `${toSnake(p.name)}: i64`;
        if (t === 'bool' || t === 'boolean') return `${toSnake(p.name)}: bool`;
        return `${toSnake(p.name)}: String`;
      }).join(', ');
      const pascalName = action.name.charAt(0).toUpperCase() + action.name.slice(1);
      lines.push(`    ${pascalName} { ${fields} },`);
    }
    lines.push('}');
    lines.push('');
    lines.push('#[cfg(fuzzing)]');
    lines.push('fuzz_target!(|actions: Vec<' + plan.conceptName + 'Action>| {');
    lines.push('    let mut state = State::new();');
    lines.push('    for action in actions {');
    lines.push('        match action {');
    for (const action of plan.actions) {
      const pascalName = action.name.charAt(0).toUpperCase() + action.name.slice(1);
      const paramNames = action.params.map(p => toSnake(p.name)).join(', ');
      lines.push(`            ${plan.conceptName}Action::${pascalName} { ${paramNames} } => {`);
      lines.push(`                let _ = ${toSnake(action.name)}(${paramNames});`);
      lines.push('            }');
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('});');
    lines.push('');
  }

  // Register conformance test
  lines.push('#[test]');
  lines.push(`fn test_register_declares_concept_name() {`);
  lines.push(`    let result = register();`);
  lines.push(`    assert_eq!(result.variant, "ok");`);
  lines.push(`    assert_eq!(result.name, "${plan.conceptName}");`);
  lines.push('}');
  lines.push('');

  // State invariant tests
  for (const inv of plan.stateInvariants) {
    const fnName = toSnake(inv.name).replace(/[^a-z0-9_]/g, '_');
    lines.push('#[test]');
    lines.push(`fn test_${inv.kind}_${fnName}() {`);
    if (inv.kind === 'always') {
      lines.push(`    // State predicate must hold: ${inv.name}`);
    } else {
      lines.push(`    // Bad state must never be reachable: ${inv.name}`);
    }
    if (plan.actions.length > 0) {
      const action = plan.actions[0];
      const input = bestInput(action);
      lines.push(`    let result = ${toSnake(action.name)}(${input});`);
      lines.push('    assert!(result.variant.len() > 0);');
    }
    lines.push('}');
    lines.push('');
  }

  // Contract tests
  for (const contract of plan.contracts) {
    for (const pre of contract.preconditions) {
      const fnName = toSnake(`${contract.targetAction}_requires_${pre.assertion}`).replace(/[^a-z0-9_]/g, '_');
      lines.push('#[test]');
      lines.push(`fn test_contract_${fnName}() {`);
      lines.push(`    // Precondition: ${pre.assertion}`);
      lines.push(`    let result = ${toSnake(contract.targetAction)}();`);
      lines.push('    assert!(result.variant == "error" || result.variant == "invalid");');
      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function renderRustActionTests(lines: string[], _modName: string, action: TestPlanAction): void {
  const fnBase = toSnake(action.name);
  const input = bestInput(action);

  lines.push('#[test]');
  lines.push(`fn test_${fnBase}_returns_valid_variant() {`);
  lines.push(`    let result = ${fnBase}(${input});`);
  lines.push('    assert!(result.variant.len() > 0);');
  const validVariants = action.variants.map(v => `"${v}"`).join(', ');
  lines.push(`    assert!([${validVariants}].contains(&result.variant.as_str()));`);
  lines.push('}');
  lines.push('');

  for (const fixture of (action.fixtures || [])) {
    const fInput = fixtureInputRust(fixture.input);
    lines.push('#[test]');
    lines.push(`fn test_${fnBase}_fixture_${toSnake(fixture.name)}() {`);
    lines.push(`    let result = ${fnBase}(${fInput});`);
    lines.push(`    assert_eq!(result.variant, "${fixture.expectedVariant}");`);
    lines.push('}');
    lines.push('');
  }
}

export const testGenRustHandler: FunctionalConceptHandler = {

  render(input: Record<string, unknown>) {
    const testPlanJson = input.test_plan as string;
    const outputPath = input.output_path as string;

    if (!testPlanJson || !outputPath) {
      return complete(createProgram(), 'invalid', {
        message: 'test_plan and output_path are required',
      }) as StorageProgram<Result>;
    }

    let plan: TestPlan;
    try {
      plan = JSON.parse(testPlanJson) as TestPlan;
    } catch {
      return complete(createProgram(), 'invalid', {
        message: 'Failed to parse test_plan JSON',
      }) as StorageProgram<Result>;
    }

    if (!plan.conceptName || !plan.actions) {
      return complete(createProgram(), 'invalid', {
        message: 'TestPlan missing required fields: conceptName, actions',
      }) as StorageProgram<Result>;
    }

    const renderedCode = renderRustTests(plan);
    const testCount = (renderedCode.match(/#\[test\]/g) || []).length;
    const id = nextId();

    let p = createProgram();
    p = put(p, RESULTS, id, {
      id, test_plan: testPlanJson, rendered_code: renderedCode,
      file_path: outputPath, rendered_at: new Date().toISOString(),
      test_count: testCount,
    });

    return complete(p, 'ok', {
      result: id, rendered_code: renderedCode,
      file_path: outputPath, test_count: testCount,
    }) as StorageProgram<Result>;
  },

  renderBatch(input: Record<string, unknown>) {
    const plansJson = input.test_plans as string;
    if (!plansJson) {
      return complete(createProgram(), 'error', { message: 'test_plans is required' }) as StorageProgram<Result>;
    }

    let items: Array<{ test_plan: string; output_path: string }>;
    try { items = JSON.parse(plansJson); } catch {
      return complete(createProgram(), 'error', { message: 'Invalid JSON' }) as StorageProgram<Result>;
    }

    let p = createProgram();
    let totalTests = 0;
    const results: Array<{ file_path: string; test_count: number }> = [];
    for (const item of items) {
      let plan: TestPlan;
      try { plan = JSON.parse(item.test_plan); } catch { continue; }
      if (!plan.conceptName || !plan.actions) continue;
      const code = renderRustTests(plan);
      const tc = (code.match(/#\[test\]/g) || []).length;
      const id = nextId();
      p = put(p, RESULTS, id, { id, rendered_code: code, file_path: item.output_path, test_count: tc });
      results.push({ file_path: item.output_path, test_count: tc });
      totalTests += tc;
    }
    return complete(p, 'ok', { results: JSON.stringify(results), total_files: results.length, total_tests: totalTests }) as StorageProgram<Result>;
  },

  listRendered(input: Record<string, unknown>) {
    if (!input.concept_ref || (typeof input.concept_ref === 'string' && (input.concept_ref as string).trim() === '')) {
      return complete(createProgram(), 'error', { message: 'concept_ref is required' }) as StorageProgram<Result>;
    }
    void input;
    let p = createProgram();
    p = find(p, RESULTS, {}, 'allResults');
    return complete(p, 'ok', { results: '[]' }) as StorageProgram<Result>;
  },
};
