// Auto-generated by Clef Clef Bind — mcp target
// Concept: AnatomyPartEntity
// Do not edit manually; regenerate with: clef interface generate

export const anatomyPartEntityTools = [
  {
    "type": "tool",
    "name": "anatomy_part_entity_register",
    "description": "Register anatomypartentity — Register an anatomy part extracted from a widget spec . \n Role is one of : container , action , text , overlay , widget .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "widget": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "role": {
          "type": "string"
        },
        "required": {
          "type": "string"
        }
      },
      "required": [
        "widget",
        "name",
        "role",
        "required"
      ]
    }
  },
  {
    "type": "resource",
    "name": "anatomy_part_entity_find_by_role",
    "uri": "urn:clef://anatomy-part-entitys/{role}",
    "description": "Find by role anatomypartentity — Return all anatomy parts with the given semantic role \n across all widgets . Results as serialized JSON array ."
  },
  {
    "type": "resource",
    "name": "anatomy_part_entity_find_bound_to_field",
    "uri": "urn:clef://anatomy-part-entitys/{field}",
    "description": "Find bound to field anatomypartentity — Return all anatomy parts that present the given concept \n state field . Results as serialized JSON array ."
  },
  {
    "type": "resource",
    "name": "anatomy_part_entity_find_bound_to_action",
    "uri": "urn:clef://anatomy-part-entitys/{action}",
    "description": "Find bound to action anatomypartentity — Return all anatomy parts that trigger the given concept \n action . Results as serialized JSON array ."
  },
  {
    "type": "resource",
    "name": "anatomy_part_entity_get",
    "uri": "urn:clef://anatomy-part-entitys/{part}",
    "description": "Get anatomypartentity — Retrieve anatomy part metadata ."
  }
];
