// Auto-generated by Clef Clef Bind — mcp target
// Concept: Attribution
// Do not edit manually; regenerate with: clef interface generate

export const attributionTools = [
  {
    "type": "tool",
    "name": "attribution_attribute",
    "description": "Attribute attribution — Attribution record created binding agent to content region .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "contentRef": {
          "type": "string"
        },
        "region": {
          "type": "string"
        },
        "agent": {
          "type": "string"
        },
        "changeRef": {
          "type": "string"
        }
      },
      "required": [
        "contentRef",
        "region",
        "agent",
        "changeRef"
      ]
    }
  },
  {
    "type": "tool",
    "name": "attribution_blame",
    "description": "Blame attribution — Returns full blame map each region mapped to its most recent author .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "contentRef": {
          "type": "string"
        }
      },
      "required": [
        "contentRef"
      ]
    }
  },
  {
    "type": "tool",
    "name": "attribution_history",
    "description": "History attribution — Full attribution chain for a specific region in chronological order .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "contentRef": {
          "type": "string"
        },
        "region": {
          "type": "string"
        }
      },
      "required": [
        "contentRef",
        "region"
      ]
    }
  },
  {
    "type": "tool",
    "name": "attribution_set_ownership",
    "description": "Set ownership attribution — CODEOWNERS style ownership rule set for path pattern .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "pattern": {
          "type": "string"
        },
        "owners": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "pattern",
        "owners"
      ]
    }
  },
  {
    "type": "tool",
    "name": "attribution_query_owners",
    "description": "Query owners attribution — Returns owners matching the path against ownership patterns .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        }
      },
      "required": [
        "path"
      ]
    }
  }
];
