// Auto-generated by Clef Clef Bind — cli target
// Concept: SuiteManager
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const suiteManagerCommand = new Command('suite-manager')
  .description('Manage suites scaffold new suites , validate suite manifests and cross suite references , run suite tests , list active suites , and check app overrides');

suiteManagerCommand
  .command('init')
  .description('Scaffold a new suite directory with suite . yaml , concept and sync subdirectories , and example files .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManager', 'init', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManagerCommand
  .command('validate')
  .description('Validate a suite manifest , its concept specs , sync definitions , and cross suite concept references .')
  .requiredOption('--path <path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManager', 'validate', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManagerCommand
  .command('test')
  .description('Run conformance and integration tests for a suite . Tests invariants from concept specs and validates sync compilation .')
  .requiredOption('--path <path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManager', 'test', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManagerCommand
  .command('list')
  .description('List all suites used by the current application , including their versions and concept counts .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManager', 'list', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

suiteManagerCommand
  .command('check-overrides')
  .description('Verify that application sync overrides reference valid syncs in the target suite .')
  .requiredOption('--path <path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SuiteManager', 'checkOverrides', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const suiteManagerCommandTree = {
  group: 'suite-manager',
  description: 'Manage suites scaffold new suites , validate suite manifests and cross suite references , run suite tests , list active suites , and check app overrides',
  commands: [{ action: 'init', command: 'init' }, { action: 'validate', command: 'validate' }, { action: 'test', command: 'test' }, { action: 'list', command: 'list' }, { action: 'checkOverrides', command: 'check-overrides' }],
};
