// Auto-generated by Clef Clef Bind — cli target
// Concept: WidgetEntity
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const widgetEntityCommand = new Command('widget-entity')
  .description('Queryable representation of a parsed widget spec the Clef Surface counterpart to ConceptEntity . Links anatomy , state machines , props , slots , accessibility contracts , affordance declarations , and composition references as a traversable structure');

widgetEntityCommand
  .command('register')
  .description('Register a parsed widget spec as a semantic entity . Extracts anatomy , states , props , slots , accessibility , affordances , and composition from the AST .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--ast <ast>', 'Ast')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

widgetEntityCommand
  .command('get')
  .description('Retrieve a widget entity by name .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

widgetEntityCommand
  .command('find-by-affordance')
  .description('Return all widgets that declare affordance for the given interactor type . Results as serialized JSON array .')
  .requiredOption('--interactor <interactor>', 'Interactor')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'findByAffordance', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

widgetEntityCommand
  .command('find-composing')
  .description('Return all widgets that compose this widget . Results as serialized JSON array .')
  .requiredOption('--widget <widget>', 'Widget')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'findComposing', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

widgetEntityCommand
  .command('find-composed-by')
  .description('Return all widgets this widget composes . Results as serialized JSON array .')
  .requiredOption('--widget <widget>', 'Widget')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'findComposedBy', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

widgetEntityCommand
  .command('generated-components')
  .description('Return all generated framework components for this widget . Results as serialized JSON array of { framework , file } .')
  .requiredOption('--widget <widget>', 'Widget')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'generatedComponents', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

widgetEntityCommand
  .command('accessibility-audit')
  .description('Audit accessibility completeness : role , keyboard bindings , ARIA attributes , focus management . Report as serialized JSON .')
  .requiredOption('--widget <widget>', 'Widget')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'accessibilityAudit', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

widgetEntityCommand
  .command('trace-to-concept')
  .description('Trace which Clef concepts this widget can render , via affordance matching and connect bindings . Results as serialized JSON array of { concept , via } .')
  .requiredOption('--widget <widget>', 'Widget')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/WidgetEntity', 'traceToConcept', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const widgetEntityCommandTree = {
  group: 'widget-entity',
  description: 'Queryable representation of a parsed widget spec the Clef Surface counterpart to ConceptEntity . Links anatomy , state machines , props , slots , accessibility contracts , affordance declarations , and composition references as a traversable structure',
  commands: [{ action: 'register', command: 'register' }, { action: 'get', command: 'get' }, { action: 'findByAffordance', command: 'find-by-affordance' }, { action: 'findComposing', command: 'find-composing' }, { action: 'findComposedBy', command: 'find-composed-by' }, { action: 'generatedComponents', command: 'generated-components' }, { action: 'accessibilityAudit', command: 'accessibility-audit' }, { action: 'traceToConcept', command: 'trace-to-concept' }],
};
