// Auto-generated by Clef Clef Bind — mcp target
// Concept: Diff
// Do not edit manually; regenerate with: clef interface generate

export const diffTools = [
  {
    "type": "tool",
    "name": "diff_register_provider",
    "description": "Register provider diff — Registers a new diff algorithm provider for the given content types .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "contentTypes": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "contentTypes"
      ]
    }
  },
  {
    "type": "tool",
    "name": "diff_diff",
    "description": "Diff diff — Contents are byte identical . No edit script needed .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "contentA": {
          "type": "string"
        },
        "contentB": {
          "type": "string"
        },
        "algorithm": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "contentA",
        "contentB",
        "algorithm"
      ]
    }
  },
  {
    "type": "tool",
    "name": "diff_patch",
    "description": "Patch diff — Applies edit script to content , producing transformed result .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "editScript": {
          "type": "string"
        }
      },
      "required": [
        "content",
        "editScript"
      ]
    }
  }
];
