// Auto-generated entrypoint for kit "copf-devtools", target "claude-skills"
import { SpecParserModule } from './SpecParser/SpecParser.module';
import { SchemaGenModule } from './SchemaGen/SchemaGen.module';
import { SyncParserModule } from './SyncParser/SyncParser.module';
import { SyncCompilerModule } from './SyncCompiler/SyncCompiler.module';
import { FlowTraceModule } from './FlowTrace/FlowTrace.module';
import { DeploymentValidatorModule } from './DeploymentValidator/DeploymentValidator.module';
import { ProjectScaffoldModule } from './ProjectScaffold/ProjectScaffold.module';
import { DevServerModule } from './DevServer/DevServer.module';
import { KitManagerModule } from './KitManager/KitManager.module';
import { EmitterModule } from './Emitter/Emitter.module';
import { BuildCacheModule } from './BuildCache/BuildCache.module';
import { ResourceModule } from './Resource/Resource.module';
import { KindSystemModule } from './KindSystem/KindSystem.module';
import { GenerationPlanModule } from './GenerationPlan/GenerationPlan.module';
import { BuilderModule } from './Builder/Builder.module';
import { ToolchainModule } from './Toolchain/Toolchain.module';
import { KitScaffoldGenModule } from './KitScaffoldGen/KitScaffoldGen.module';
import { DeployScaffoldGenModule } from './DeployScaffoldGen/DeployScaffoldGen.module';
import { InterfaceScaffoldGenModule } from './InterfaceScaffoldGen/InterfaceScaffoldGen.module';
import { ConceptScaffoldGenModule } from './ConceptScaffoldGen/ConceptScaffoldGen.module';
import { SyncScaffoldGenModule } from './SyncScaffoldGen/SyncScaffoldGen.module';
import { HandlerScaffoldGenModule } from './HandlerScaffoldGen/HandlerScaffoldGen.module';
import { StorageAdapterScaffoldGenModule } from './StorageAdapterScaffoldGen/StorageAdapterScaffoldGen.module';
import { TransportAdapterScaffoldGenModule } from './TransportAdapterScaffoldGen/TransportAdapterScaffoldGen.module';
import { CoifComponentScaffoldGenModule } from './CoifComponentScaffoldGen/CoifComponentScaffoldGen.module';
import { CoifThemeScaffoldGenModule } from './CoifThemeScaffoldGen/CoifThemeScaffoldGen.module';
import { GeneratorModule } from './Generator/Generator.module';
import { ProjectionModule } from './Projection/Projection.module';
import { ApiSurfaceModule } from './ApiSurface/ApiSurface.module';
import { ConformanceModule } from './Conformance/Conformance.module';
import { TestSelectionModule } from './TestSelection/TestSelection.module';
import { FlakyTestModule } from './FlakyTest/FlakyTest.module';
import { ContractTestModule } from './ContractTest/ContractTest.module';
import { SnapshotModule } from './Snapshot/Snapshot.module';

export const modules = [SpecParserModule, SchemaGenModule, SyncParserModule, SyncCompilerModule, FlowTraceModule, DeploymentValidatorModule, ProjectScaffoldModule, DevServerModule, KitManagerModule, EmitterModule, BuildCacheModule, ResourceModule, KindSystemModule, GenerationPlanModule, BuilderModule, ToolchainModule, KitScaffoldGenModule, DeployScaffoldGenModule, InterfaceScaffoldGenModule, ConceptScaffoldGenModule, SyncScaffoldGenModule, HandlerScaffoldGenModule, StorageAdapterScaffoldGenModule, TransportAdapterScaffoldGenModule, CoifComponentScaffoldGenModule, CoifThemeScaffoldGenModule, GeneratorModule, ProjectionModule, ApiSurfaceModule, ConformanceModule, TestSelectionModule, FlakyTestModule, ContractTestModule, SnapshotModule];
