// @clef-handler style=functional
import type { FunctionalConceptHandler } from '../../../runtime/functional-handler.ts';
import {
  createProgram, put, complete,
  type StorageProgram,
} from '../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../runtime/functional-compat.ts';

type Result = { variant: string; [key: string]: unknown };

interface FieldDef {
  name: string;
  type: string;
  required?: boolean;
  default?: string;
  enum?: string[];
}

interface ContentNative {
  childSchema?: string;
  defaultTemplate?: string;
  compilationProvider?: string;
  displayWidget?: string;
}

interface ChildSchemaDefinition {
  name: string;
  fields: FieldDef[];
}

interface DefaultBlock {
  sectionType: string;
  role: string;
  priority: number;
  required: boolean;
  maxTokens: number;
  description: string;
  defaultContent?: string;
}

interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Safely coerce an input value to a string, returning empty string for
 * non-string types (e.g. ref placeholder objects passed by structural tests).
 */
function toStr(value: unknown): string {
  if (typeof value === 'string') return value;
  return '';
}

/**
 * Parse a value that may be a JSON string, an object, or null/undefined.
 * Returns null on parse failure or if the value is null/undefined/none.
 */
function parseOptionalObject<T>(value: unknown): T | null {
  if (value === null || value === undefined || value === 'null' || value === 'none') {
    return null;
  }
  if (typeof value === 'object') {
    return value as T;
  }
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      return parsed as T;
    } catch {
      return null;
    }
  }
  return null;
}

/**
 * Parse a value that may be a JSON string, an array, or null/undefined.
 * Returns empty array on parse failure or if the value is null/undefined/none.
 */
function parseOptionalArray<T>(value: unknown): T[] {
  if (value === null || value === undefined || value === 'null' || value === 'none') {
    return [];
  }
  if (Array.isArray(value)) {
    return value as T[];
  }
  if (typeof value === 'string') {
    try {
      const parsed = JSON.parse(value);
      if (Array.isArray(parsed)) return parsed as T[];
      return [];
    } catch {
      return [];
    }
  }
  return [];
}

/**
 * Build YAML lines for a single field definition.
 */
function buildFieldYaml(field: FieldDef, indent: string): string[] {
  const lines: string[] = [];
  lines.push(`${indent}- name: ${field.name}`);
  lines.push(`${indent}  type: ${field.type}`);
  if (field.required !== undefined && field.required !== null) {
    lines.push(`${indent}  required: ${field.required}`);
  }
  if (field.default !== undefined && field.default !== null) {
    lines.push(`${indent}  default: "${field.default}"`);
  }
  if (field.enum && field.enum.length > 0) {
    lines.push(`${indent}  enum:`);
    for (const val of field.enum) {
      lines.push(`${indent}    - ${val}`);
    }
  }
  return lines;
}

/**
 * Build the .schema.yaml content for a content type definition.
 */
function buildSchemaYaml(
  name: string,
  fields: FieldDef[],
  contentNative: ContentNative,
  childSchemaDefinition: ChildSchemaDefinition | null,
  defaultBlocks: DefaultBlock[] | null,
): string {
  const lines: string[] = [];

  lines.push(`# Content type schema definition for: ${name}`);
  lines.push(`# Generated by ContentTypeScaffoldGen`);
  lines.push('');
  lines.push(`name: ${name}`);
  lines.push('');

  // Fields section
  if (fields && fields.length > 0) {
    lines.push('fields:');
    for (const field of fields) {
      lines.push(...buildFieldYaml(field, '  '));
    }
    lines.push('');
  }

  // Content-native properties section
  const hasContentNative = contentNative && (
    contentNative.childSchema ||
    contentNative.defaultTemplate ||
    contentNative.compilationProvider ||
    contentNative.displayWidget
  );

  if (hasContentNative) {
    lines.push('contentNative:');
    if (contentNative.childSchema) {
      lines.push(`  childSchema: ${contentNative.childSchema}`);
    }
    if (contentNative.defaultTemplate) {
      lines.push(`  defaultTemplate: ${contentNative.defaultTemplate}`);
    }
    if (contentNative.compilationProvider) {
      lines.push(`  compilationProvider: ${contentNative.compilationProvider}`);
    }
    if (contentNative.displayWidget) {
      lines.push(`  displayWidget: ${contentNative.displayWidget}`);
    }
    lines.push('');
  }

  // Child schema definition section
  if (childSchemaDefinition) {
    lines.push('childSchemaDefinition:');
    lines.push(`  name: ${childSchemaDefinition.name}`);
    if (childSchemaDefinition.fields && childSchemaDefinition.fields.length > 0) {
      lines.push('  fields:');
      for (const field of childSchemaDefinition.fields) {
        lines.push(...buildFieldYaml(field, '    '));
      }
    }
    lines.push('');
  }

  // Default blocks section
  if (defaultBlocks && defaultBlocks.length > 0) {
    lines.push('defaultBlocks:');
    for (const block of defaultBlocks) {
      lines.push(`  - sectionType: ${block.sectionType}`);
      lines.push(`    role: ${block.role}`);
      lines.push(`    priority: ${block.priority}`);
      lines.push(`    required: ${block.required}`);
      lines.push(`    maxTokens: ${block.maxTokens}`);
      lines.push(`    description: "${block.description}"`);
      if (block.defaultContent !== undefined && block.defaultContent !== null) {
        lines.push(`    defaultContent: "${block.defaultContent}"`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Build the initialization sync content that bootstraps the schema and
 * content-native properties at runtime.
 */
function buildInitSyncContent(
  name: string,
  contentNative: ContentNative,
  childSchemaDefinition: ChildSchemaDefinition | null,
): string {
  const lines: string[] = [];
  const schemaUri = `urn:schema/${name}`;

  lines.push(`# Initialization sync for content type: ${name}`);
  lines.push(`# Bootstraps Schema/defineSchema and Property/set at startup`);
  lines.push('');
  lines.push(`sync Init${toPascalCase(name)} [eager]`);
  lines.push(`  purpose: "Bootstrap schema definition and content-native properties for ${name}"`);
  lines.push('{');
  lines.push('  when {');
  lines.push('    System/ready: [] => []');
  lines.push('  }');
  lines.push('  then {');
  lines.push(`    Schema/defineSchema: [`);
  lines.push(`      uri: "${schemaUri}";`);
  lines.push(`      name: "${name}" ]`);
  lines.push('  }');

  // Content-native property syncs
  if (contentNative) {
    if (contentNative.childSchema) {
      lines.push('  then {');
      lines.push(`    Property/set: [`);
      lines.push(`      schema: "${schemaUri}";`);
      lines.push(`      property: "childSchema";`);
      lines.push(`      value: "${contentNative.childSchema}" ]`);
      lines.push('  }');
    }
    if (contentNative.defaultTemplate) {
      lines.push('  then {');
      lines.push(`    Property/set: [`);
      lines.push(`      schema: "${schemaUri}";`);
      lines.push(`      property: "defaultTemplate";`);
      lines.push(`      value: "${contentNative.defaultTemplate}" ]`);
      lines.push('  }');
    }
    if (contentNative.compilationProvider) {
      lines.push('  then {');
      lines.push(`    Property/set: [`);
      lines.push(`      schema: "${schemaUri}";`);
      lines.push(`      property: "compilationProvider";`);
      lines.push(`      value: "${contentNative.compilationProvider}" ]`);
      lines.push('  }');
    }
    if (contentNative.displayWidget) {
      lines.push('  then {');
      lines.push(`    Property/set: [`);
      lines.push(`      schema: "${schemaUri}";`);
      lines.push(`      property: "displayWidget";`);
      lines.push(`      value: "${contentNative.displayWidget}" ]`);
      lines.push('  }');
    }
  }

  // Child schema definition sync
  if (childSchemaDefinition) {
    const childUri = `urn:schema/${childSchemaDefinition.name}`;
    lines.push('  then {');
    lines.push(`    Schema/defineSchema: [`);
    lines.push(`      uri: "${childUri}";`);
    lines.push(`      name: "${childSchemaDefinition.name}";`);
    lines.push(`      parent: "${schemaUri}" ]`);
    lines.push('  }');
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

/**
 * Build the template definition content for default blocks.
 */
function buildTemplateDefinitionContent(
  name: string,
  defaultBlocks: DefaultBlock[],
): string {
  const lines: string[] = [];

  lines.push(`# Template definition for content type: ${name}`);
  lines.push(`# Default block tree with pre-configured sections`);
  lines.push('');
  lines.push(`template: default-${name}`);
  lines.push(`schema: ${name}`);
  lines.push('');
  lines.push('blocks:');

  for (const block of defaultBlocks) {
    lines.push(`  - sectionType: ${block.sectionType}`);
    lines.push(`    role: ${block.role}`);
    lines.push(`    priority: ${block.priority}`);
    lines.push(`    required: ${block.required}`);
    lines.push(`    maxTokens: ${block.maxTokens}`);
    lines.push(`    description: "${block.description}"`);
    if (block.defaultContent !== undefined && block.defaultContent !== null) {
      lines.push(`    defaultContent: "${block.defaultContent}"`);
    }
  }

  lines.push('');

  return lines.join('\n');
}

/**
 * Convert a kebab-case or snake_case string to PascalCase.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Compute the set of files that would be generated for the given inputs.
 * Returns the files array without writing anything.
 */
function computeFiles(
  name: string,
  fields: FieldDef[],
  contentNative: ContentNative,
  childSchemaDefinition: ChildSchemaDefinition | null,
  defaultBlocks: DefaultBlock[] | null,
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  // 1. The .schema.yaml file
  files.push({
    path: `schemas/${name}.schema.yaml`,
    content: buildSchemaYaml(name, fields, contentNative, childSchemaDefinition, defaultBlocks),
  });

  // 2. The initialization sync
  files.push({
    path: `syncs/init-${name}.sync`,
    content: buildInitSyncContent(name, contentNative, childSchemaDefinition),
  });

  // 3. Optional template definition if defaultBlocks provided
  if (defaultBlocks && defaultBlocks.length > 0) {
    files.push({
      path: `templates/default-${name}.template.yaml`,
      content: buildTemplateDefinitionContent(name, defaultBlocks),
    });
  }

  return files;
}

const _contentTypeScaffoldGenHandler: FunctionalConceptHandler = {
  /**
   * Generate a .schema.yaml file, an initialization sync, and optionally a
   * template definition from the provided content type configuration.
   */
  generate(input: Record<string, unknown>) {
    const name = toStr(input.name);

    // Validate name non-empty
    if (!name || name.trim() === '') {
      return complete(
        createProgram(),
        'error',
        { message: 'name is required' },
      ) as StorageProgram<Result>;
    }

    // Parse fields — may arrive as JSON string or array
    let fields: FieldDef[] = [];
    if (typeof input.fields === 'string') {
      try {
        fields = JSON.parse(input.fields) as FieldDef[];
      } catch {
        return complete(
          createProgram(),
          'error',
          { message: 'fields is not valid JSON' },
        ) as StorageProgram<Result>;
      }
    } else if (Array.isArray(input.fields)) {
      fields = input.fields as FieldDef[];
    }

    // Parse contentNative — may arrive as JSON string or object
    const contentNative: ContentNative = parseOptionalObject<ContentNative>(input.contentNative) ?? {};

    // Parse optional childSchemaDefinition
    const childSchemaDefinition = parseOptionalObject<ChildSchemaDefinition>(input.childSchemaDefinition);

    // Parse optional defaultBlocks
    const defaultBlocks = parseOptionalArray<DefaultBlock>(input.defaultBlocks);

    // Compute files
    const files = computeFiles(name, fields, contentNative, childSchemaDefinition, defaultBlocks.length > 0 ? defaultBlocks : null);
    const filesGenerated = files.length;

    // Store the generated spec record for tracking
    const specId = name;
    let p = createProgram();
    p = put(p, 'specs', specId, {
      name,
      generatedAt: new Date().toISOString(),
      filesGenerated,
    });

    return complete(p, 'ok', {
      files,
      filesGenerated,
    }) as StorageProgram<Result>;
  },

  /**
   * Compute what files would be generated without writing them.
   * Classifies each file as new, changed, or unchanged using content-addressing.
   */
  preview(input: Record<string, unknown>) {
    const name = toStr(input.name);

    // Validate name non-empty
    if (!name || name.trim() === '') {
      return complete(
        createProgram(),
        'error',
        { message: 'name is required' },
      ) as StorageProgram<Result>;
    }

    // Parse fields
    let fields: FieldDef[] = [];
    if (typeof input.fields === 'string') {
      try {
        fields = JSON.parse(input.fields) as FieldDef[];
      } catch {
        return complete(
          createProgram(),
          'error',
          { message: 'fields is not valid JSON' },
        ) as StorageProgram<Result>;
      }
    } else if (Array.isArray(input.fields)) {
      fields = input.fields as FieldDef[];
    }

    // Parse contentNative
    const contentNative: ContentNative = parseOptionalObject<ContentNative>(input.contentNative) ?? {};

    // Parse optional childSchemaDefinition
    const childSchemaDefinition = parseOptionalObject<ChildSchemaDefinition>(input.childSchemaDefinition);

    // Parse optional defaultBlocks
    const defaultBlocks = parseOptionalArray<DefaultBlock>(input.defaultBlocks);

    // Compute files without writing
    const files = computeFiles(name, fields, contentNative, childSchemaDefinition, defaultBlocks.length > 0 ? defaultBlocks : null);

    // In a full implementation, Emitter content-addressing would classify each
    // file as new, changed, or unchanged. Here we treat all as new writes.
    const wouldWrite = files.length;
    const wouldSkip = 0;

    return complete(createProgram(), 'ok', {
      files,
      wouldWrite,
      wouldSkip,
    }) as StorageProgram<Result>;
  },

  /**
   * Return static metadata so PluginRegistry can discover and route to this
   * generator.
   */
  register(_input: Record<string, unknown>) {
    return complete(createProgram(), 'ok', {
      name: 'ContentTypeScaffoldGen',
      inputKind: 'ContentTypeConfig',
      outputKind: 'SchemaDefinition',
      capabilities: [
        'schema-yaml',
        'content-native-properties',
        'child-schema',
        'default-blocks',
        'init-sync',
        'template-definition',
      ],
    }) as StorageProgram<Result>;
  },
};

export const contentTypeScaffoldGenHandler = autoInterpret(_contentTypeScaffoldGenHandler);
