// @migrated dsl-constructs 2026-03-18
// UILibraryTarget Concept Implementation
// Generates docs/reference/ui-library.md from typed manifests.
// Uses filesystem imports — functional style wraps the single storage.put at the end.
import type { FunctionalConceptHandler } from '../../../runtime/functional-handler.ts';
import type { WidgetManifest, ThemeManifest } from '../../../runtime/types.js';
import { parseWidgetFile } from '../framework/widget-spec-parser.js';
import { parseThemeFile } from '../framework/theme-spec-parser.js';
import { readFileSync, readdirSync, existsSync, statSync } from 'fs';
import { join, basename, relative, dirname } from 'path';
import { createProgram, put, complete, type StorageProgram } from '../../../runtime/storage-program.ts';
import { autoInterpret } from '../../../runtime/functional-compat.ts';

const SKIP_DIRS = new Set(['node_modules','.git','.claude','dist','build','out','.next','.turbo','coverage','__pycache__']);
function globRecursive(dir: string, ext: string): string[] {
  const results: string[] = []; if (!existsSync(dir)) return results;
  for (const entry of readdirSync(dir)) { if (SKIP_DIRS.has(entry)) continue; const full = join(dir, entry);
    try { const stat = statSync(full); if (stat.isDirectory()) results.push(...globRecursive(full, ext)); else if (entry.endsWith(ext)) results.push(full); } catch { /* skip */ } }
  return results;
}
interface SuiteLite { name: string; dir: string; relPath: string; }
function parseSuiteName(source: string, dirName: string): string { const m = source.match(/name:\s*(.+)/); return m ? m[1].trim() : dirName; }
function findNearestSuiteDir(filePath: string, suitesByDir: Map<string, SuiteLite>): SuiteLite | null {
  let dir = dirname(filePath); const seen = new Set<string>();
  while (dir && !seen.has(dir)) { seen.add(dir); if (suitesByDir.has(dir)) return suitesByDir.get(dir)!; const parent = dirname(dir); if (parent === dir) break; dir = parent; }
  return null;
}

const _uiLibraryTargetHandler: FunctionalConceptHandler = {
  generate(input: Record<string, unknown>) {
    const config = JSON.parse((input.config as string) || '{}');
    const outputPath = (config.outputPath as string) || 'docs/reference/ui-library.md';
    const projectRoot = (config.projectRoot as string) || process.cwd();

    const suiteYamlFiles = globRecursive(projectRoot, 'suite.yaml');
    const suitesByDir = new Map<string, SuiteLite>();
    for (const f of suiteYamlFiles) { try { const dir = dirname(f); const relPath = relative(projectRoot, dir).replace(/\\/g, '/'); const name = parseSuiteName(readFileSync(f, 'utf-8'), basename(dir)); suitesByDir.set(dir, { name, dir, relPath }); } catch { /* skip */ } }

    const themeFiles = globRecursive(projectRoot, '.theme');
    const themes: ThemeManifest[] = [];
    for (const f of themeFiles) { try { themes.push(parseThemeFile(readFileSync(f, 'utf-8'))); } catch { /* skip */ } }

    const widgetFiles = globRecursive(projectRoot, '.widget');
    const widgetsByGroup = new Map<string, { label: string; relPath: string; widgets: WidgetManifest[] }>();
    for (const f of widgetFiles) {
      let groupKey: string; let label: string; let relPath: string;
      const suite = findNearestSuiteDir(f, suitesByDir);
      if (suite) { groupKey = suite.dir; label = suite.name; relPath = suite.relPath; }
      else { const fileRelDir = relative(projectRoot, dirname(f)).replace(/\\/g, '/'); const parts = fileRelDir.split('/');
        if (parts.length >= 2) { groupKey = parts.slice(0, 2).join('/'); label = parts.slice(0, 2).join('/'); } else { groupKey = fileRelDir; label = fileRelDir; } relPath = fileRelDir; }
      if (!widgetsByGroup.has(groupKey)) widgetsByGroup.set(groupKey, { label, relPath, widgets: [] });
      try { widgetsByGroup.get(groupKey)!.widgets.push(parseWidgetFile(readFileSync(f, 'utf-8'))); } catch { /* skip */ }
    }

    const sortedGroups = [...widgetsByGroup.entries()].filter(([, g]) => g.widgets.length > 0).sort((a, b) => a[1].label.localeCompare(b[1].label));
    const totalWidgets = sortedGroups.reduce((n, [, g]) => n + g.widgets.length, 0);
    const content = `# UI Library Reference\n\n> Auto-generated by UILibraryTarget — ${totalWidgets} widgets, ${themes.length} themes across ${sortedGroups.length} groups\n`;
    const docId = `ui-library-${Date.now()}`;

    let p = createProgram();
    p = put(p, 'document', docId, { docId, outputPath, themeCount: themes.length, widgetCount: totalWidgets, groupCount: sortedGroups.length, content, generatedAt: new Date().toISOString() });
    return complete(p, 'ok', { document: docId, files: [outputPath] }) as StorageProgram<{ variant: string; [key: string]: unknown }>;
  },
};

export const uiLibraryTargetHandler = autoInterpret(_uiLibraryTargetHandler);

