// ReputationProviders.swift — Governance Reputation providers: SimpleAccumulator, EloRating, PeerAllocation, PageRankReputation, GlickoRating

import Foundation

// MARK: - SimpleAccumulator Types

public struct SimpleAccumulatorConfigureInput: Codable { public let decayRate: Double?; public let cap: Double?; public init(decayRate: Double? = nil, cap: Double? = nil) { self.decayRate = decayRate; self.cap = cap } }
public enum SimpleAccumulatorConfigureOutput: Codable { case configured(config: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, config, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "configured": self = .configured(config: try c.decode(String.self, forKey: .config)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .configured(let config): try c.encode("configured", forKey: .variant); try c.encode(config, forKey: .config); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct SimpleAccumulatorAddInput: Codable { public let config: String; public let participant: String; public let amount: Double; public init(config: String, participant: String, amount: Double) { self.config = config; self.participant = participant; self.amount = amount } }
public enum SimpleAccumulatorAddOutput: Codable { case added(participant: String, newScore: Double); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, newScore, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "added": self = .added(participant: try c.decode(String.self, forKey: .participant), newScore: try c.decode(Double.self, forKey: .newScore)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .added(let participant, let newScore): try c.encode("added", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(newScore, forKey: .newScore); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct SimpleAccumulatorDecayInput: Codable { public let config: String; public let participant: String; public init(config: String, participant: String) { self.config = config; self.participant = participant } }
public enum SimpleAccumulatorDecayOutput: Codable { case decayed(participant: String, newScore: Double, previousScore: Double); case noDecay(participant: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, newScore, previousScore, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "decayed": self = .decayed(participant: try c.decode(String.self, forKey: .participant), newScore: try c.decode(Double.self, forKey: .newScore), previousScore: try c.decode(Double.self, forKey: .previousScore)); case "no_decay": self = .noDecay(participant: try c.decode(String.self, forKey: .participant)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .decayed(let participant, let newScore, let previousScore): try c.encode("decayed", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(newScore, forKey: .newScore); try c.encode(previousScore, forKey: .previousScore); case .noDecay(let participant): try c.encode("no_decay", forKey: .variant); try c.encode(participant, forKey: .participant); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct SimpleAccumulatorGetScoreInput: Codable { public let config: String; public let participant: String; public init(config: String, participant: String) { self.config = config; self.participant = participant } }
public enum SimpleAccumulatorGetScoreOutput: Codable { case score(participant: String, score: Double); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, score, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "score": self = .score(participant: try c.decode(String.self, forKey: .participant), score: try c.decode(Double.self, forKey: .score)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .score(let participant, let score): try c.encode("score", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(score, forKey: .score); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

// MARK: - EloRating Types

public struct EloRatingConfigureInput: Codable { public let kFactor: Double?; public let initialRating: Double?; public let kFactorDecay: Double?; public init(kFactor: Double? = nil, initialRating: Double? = nil, kFactorDecay: Double? = nil) { self.kFactor = kFactor; self.initialRating = initialRating; self.kFactorDecay = kFactorDecay } }
public enum EloRatingConfigureOutput: Codable { case configured(config: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, config, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "configured": self = .configured(config: try c.decode(String.self, forKey: .config)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .configured(let config): try c.encode("configured", forKey: .variant); try c.encode(config, forKey: .config); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct EloRatingRecordOutcomeInput: Codable { public let config: String; public let winner: String; public let loser: String; public init(config: String, winner: String, loser: String) { self.config = config; self.winner = winner; self.loser = loser } }
public enum EloRatingRecordOutcomeOutput: Codable { case updated(winnerNewRating: Double, loserNewRating: Double, winnerDelta: Double, loserDelta: Double); case error(message: String); enum CodingKeys: String, CodingKey { case variant, winnerNewRating, loserNewRating, winnerDelta, loserDelta, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "updated": self = .updated(winnerNewRating: try c.decode(Double.self, forKey: .winnerNewRating), loserNewRating: try c.decode(Double.self, forKey: .loserNewRating), winnerDelta: try c.decode(Double.self, forKey: .winnerDelta), loserDelta: try c.decode(Double.self, forKey: .loserDelta)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .updated(let winnerNewRating, let loserNewRating, let winnerDelta, let loserDelta): try c.encode("updated", forKey: .variant); try c.encode(winnerNewRating, forKey: .winnerNewRating); try c.encode(loserNewRating, forKey: .loserNewRating); try c.encode(winnerDelta, forKey: .winnerDelta); try c.encode(loserDelta, forKey: .loserDelta); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct EloRatingRecordDrawInput: Codable { public let config: String; public let participantA: String; public let participantB: String; public init(config: String, participantA: String, participantB: String) { self.config = config; self.participantA = participantA; self.participantB = participantB } }
public enum EloRatingRecordDrawOutput: Codable { case updated(aNewRating: Double, bNewRating: Double); case error(message: String); enum CodingKeys: String, CodingKey { case variant, aNewRating, bNewRating, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "updated": self = .updated(aNewRating: try c.decode(Double.self, forKey: .aNewRating), bNewRating: try c.decode(Double.self, forKey: .bNewRating)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .updated(let aNewRating, let bNewRating): try c.encode("updated", forKey: .variant); try c.encode(aNewRating, forKey: .aNewRating); try c.encode(bNewRating, forKey: .bNewRating); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct EloRatingGetRatingInput: Codable { public let config: String; public let participant: String; public init(config: String, participant: String) { self.config = config; self.participant = participant } }
public enum EloRatingGetRatingOutput: Codable { case rating(participant: String, value: Double, gamesPlayed: Int); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, value, gamesPlayed, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "rating": self = .rating(participant: try c.decode(String.self, forKey: .participant), value: try c.decode(Double.self, forKey: .value), gamesPlayed: try c.decode(Int.self, forKey: .gamesPlayed)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .rating(let participant, let value, let gamesPlayed): try c.encode("rating", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(value, forKey: .value); try c.encode(gamesPlayed, forKey: .gamesPlayed); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

// MARK: - PeerAllocation Types

public struct PeerAllocationOpenRoundInput: Codable { public let budget: Double; public let deadlineDays: Int; public init(budget: Double, deadlineDays: Int) { self.budget = budget; self.deadlineDays = deadlineDays } }
public enum PeerAllocationOpenRoundOutput: Codable { case opened(round: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, round, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "opened": self = .opened(round: try c.decode(String.self, forKey: .round)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .opened(let round): try c.encode("opened", forKey: .variant); try c.encode(round, forKey: .round); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct PeerAllocationAllocateInput: Codable { public let round: String; public let allocator: String; public let recipient: String; public let amount: Double; public let note: String?; public init(round: String, allocator: String, recipient: String, amount: Double, note: String? = nil) { self.round = round; self.allocator = allocator; self.recipient = recipient; self.amount = amount; self.note = note } }
public enum PeerAllocationAllocateOutput: Codable { case allocated(round: String, totalAllocated: Double, budget: Double); case selfAllocation(allocator: String); case roundClosed(round: String); case notFound(round: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, round, totalAllocated, budget, allocator, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "allocated": self = .allocated(round: try c.decode(String.self, forKey: .round), totalAllocated: try c.decode(Double.self, forKey: .totalAllocated), budget: try c.decode(Double.self, forKey: .budget)); case "self_allocation": self = .selfAllocation(allocator: try c.decode(String.self, forKey: .allocator)); case "round_closed": self = .roundClosed(round: try c.decode(String.self, forKey: .round)); case "not_found": self = .notFound(round: try c.decode(String.self, forKey: .round)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .allocated(let round, let totalAllocated, let budget): try c.encode("allocated", forKey: .variant); try c.encode(round, forKey: .round); try c.encode(totalAllocated, forKey: .totalAllocated); try c.encode(budget, forKey: .budget); case .selfAllocation(let allocator): try c.encode("self_allocation", forKey: .variant); try c.encode(allocator, forKey: .allocator); case .roundClosed(let round): try c.encode("round_closed", forKey: .variant); try c.encode(round, forKey: .round); case .notFound(let round): try c.encode("not_found", forKey: .variant); try c.encode(round, forKey: .round); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct PeerAllocationFinalizeInput: Codable { public let round: String; public init(round: String) { self.round = round } }
public enum PeerAllocationFinalizeOutput: Codable { case finalized(round: String, results: String); case notFound(round: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, round, results, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "finalized": self = .finalized(round: try c.decode(String.self, forKey: .round), results: try c.decode(String.self, forKey: .results)); case "not_found": self = .notFound(round: try c.decode(String.self, forKey: .round)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .finalized(let round, let results): try c.encode("finalized", forKey: .variant); try c.encode(round, forKey: .round); try c.encode(results, forKey: .results); case .notFound(let round): try c.encode("not_found", forKey: .variant); try c.encode(round, forKey: .round); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

// MARK: - PageRankReputation Types

public struct PageRankConfigureInput: Codable { public let dampingFactor: Double?; public let iterations: Int?; public init(dampingFactor: Double? = nil, iterations: Int? = nil) { self.dampingFactor = dampingFactor; self.iterations = iterations } }
public enum PageRankConfigureOutput: Codable { case configured(config: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, config, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "configured": self = .configured(config: try c.decode(String.self, forKey: .config)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .configured(let config): try c.encode("configured", forKey: .variant); try c.encode(config, forKey: .config); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct PageRankAddContributionInput: Codable { public let config: String; public let from: String; public let to: String; public let weight: Double?; public init(config: String, from: String, to: String, weight: Double? = nil) { self.config = config; self.from = from; self.to = to; self.weight = weight } }
public enum PageRankAddContributionOutput: Codable { case added(edge: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, edge, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "added": self = .added(edge: try c.decode(String.self, forKey: .edge)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .added(let edge): try c.encode("added", forKey: .variant); try c.encode(edge, forKey: .edge); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct PageRankComputeInput: Codable { public let config: String; public init(config: String) { self.config = config } }
public enum PageRankComputeOutput: Codable { case computed(config: String, scores: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, config, scores, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "computed": self = .computed(config: try c.decode(String.self, forKey: .config), scores: try c.decode(String.self, forKey: .scores)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .computed(let config, let scores): try c.encode("computed", forKey: .variant); try c.encode(config, forKey: .config); try c.encode(scores, forKey: .scores); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct PageRankGetScoreInput: Codable { public let config: String; public let participant: String; public init(config: String, participant: String) { self.config = config; self.participant = participant } }
public enum PageRankGetScoreOutput: Codable { case score(participant: String, pageRank: Double); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, pageRank, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "score": self = .score(participant: try c.decode(String.self, forKey: .participant), pageRank: try c.decode(Double.self, forKey: .pageRank)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .score(let participant, let pageRank): try c.encode("score", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(pageRank, forKey: .pageRank); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

// MARK: - GlickoRating Types

public struct GlickoRatingConfigureInput: Codable { public let initialRating: Double?; public let initialDeviation: Double?; public let initialVolatility: Double?; public let inactivityGrowthRate: Double?; public init(initialRating: Double? = nil, initialDeviation: Double? = nil, initialVolatility: Double? = nil, inactivityGrowthRate: Double? = nil) { self.initialRating = initialRating; self.initialDeviation = initialDeviation; self.initialVolatility = initialVolatility; self.inactivityGrowthRate = inactivityGrowthRate } }
public enum GlickoRatingConfigureOutput: Codable { case configured(config: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, config, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "configured": self = .configured(config: try c.decode(String.self, forKey: .config)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .configured(let config): try c.encode("configured", forKey: .variant); try c.encode(config, forKey: .config); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct GlickoRecordOutcomeInput: Codable { public let config: String; public let participant: String; public let opponent: String; public let outcome: Double; public init(config: String, participant: String, opponent: String, outcome: Double) { self.config = config; self.participant = participant; self.opponent = opponent; self.outcome = outcome } }
public enum GlickoRecordOutcomeOutput: Codable { case updated(participant: String, newRating: Double, newDeviation: Double); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, newRating, newDeviation, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "updated": self = .updated(participant: try c.decode(String.self, forKey: .participant), newRating: try c.decode(Double.self, forKey: .newRating), newDeviation: try c.decode(Double.self, forKey: .newDeviation)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .updated(let participant, let newRating, let newDeviation): try c.encode("updated", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(newRating, forKey: .newRating); try c.encode(newDeviation, forKey: .newDeviation); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct GlickoInactivityDecayInput: Codable { public let config: String; public let participant: String; public let daysSinceActive: Int; public init(config: String, participant: String, daysSinceActive: Int) { self.config = config; self.participant = participant; self.daysSinceActive = daysSinceActive } }
public enum GlickoInactivityDecayOutput: Codable { case decayed(participant: String, newDeviation: Double); case notFound(participant: String); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, newDeviation, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "decayed": self = .decayed(participant: try c.decode(String.self, forKey: .participant), newDeviation: try c.decode(Double.self, forKey: .newDeviation)); case "not_found": self = .notFound(participant: try c.decode(String.self, forKey: .participant)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .decayed(let participant, let newDeviation): try c.encode("decayed", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(newDeviation, forKey: .newDeviation); case .notFound(let participant): try c.encode("not_found", forKey: .variant); try c.encode(participant, forKey: .participant); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

public struct GlickoGetReliableWeightInput: Codable { public let config: String; public let participant: String; public init(config: String, participant: String) { self.config = config; self.participant = participant } }
public enum GlickoGetReliableWeightOutput: Codable { case weight(participant: String, rating: Double, deviation: Double, reliability: Double); case error(message: String); enum CodingKeys: String, CodingKey { case variant, participant, rating, deviation, reliability, message }; public init(from decoder: Decoder) throws { let c = try decoder.container(keyedBy: CodingKeys.self); let v = try c.decode(String.self, forKey: .variant); switch v { case "weight": self = .weight(participant: try c.decode(String.self, forKey: .participant), rating: try c.decode(Double.self, forKey: .rating), deviation: try c.decode(Double.self, forKey: .deviation), reliability: try c.decode(Double.self, forKey: .reliability)); case "error": self = .error(message: try c.decode(String.self, forKey: .message)); default: throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Unknown variant: \(v)")) } }; public func encode(to encoder: Encoder) throws { var c = encoder.container(keyedBy: CodingKeys.self); switch self { case .weight(let participant, let rating, let deviation, let reliability): try c.encode("weight", forKey: .variant); try c.encode(participant, forKey: .participant); try c.encode(rating, forKey: .rating); try c.encode(deviation, forKey: .deviation); try c.encode(reliability, forKey: .reliability); case .error(let message): try c.encode("error", forKey: .variant); try c.encode(message, forKey: .message) } } }

// MARK: - Handler Protocols

public protocol SimpleAccumulatorHandler { func configure(input: SimpleAccumulatorConfigureInput, storage: ConceptStorage) async throws -> SimpleAccumulatorConfigureOutput; func add(input: SimpleAccumulatorAddInput, storage: ConceptStorage) async throws -> SimpleAccumulatorAddOutput; func applyDecay(input: SimpleAccumulatorDecayInput, storage: ConceptStorage) async throws -> SimpleAccumulatorDecayOutput; func getScore(input: SimpleAccumulatorGetScoreInput, storage: ConceptStorage) async throws -> SimpleAccumulatorGetScoreOutput }
public protocol EloRatingHandler { func configure(input: EloRatingConfigureInput, storage: ConceptStorage) async throws -> EloRatingConfigureOutput; func recordOutcome(input: EloRatingRecordOutcomeInput, storage: ConceptStorage) async throws -> EloRatingRecordOutcomeOutput; func recordDraw(input: EloRatingRecordDrawInput, storage: ConceptStorage) async throws -> EloRatingRecordDrawOutput; func getRating(input: EloRatingGetRatingInput, storage: ConceptStorage) async throws -> EloRatingGetRatingOutput }
public protocol PeerAllocationHandler { func openRound(input: PeerAllocationOpenRoundInput, storage: ConceptStorage) async throws -> PeerAllocationOpenRoundOutput; func allocate(input: PeerAllocationAllocateInput, storage: ConceptStorage) async throws -> PeerAllocationAllocateOutput; func finalize(input: PeerAllocationFinalizeInput, storage: ConceptStorage) async throws -> PeerAllocationFinalizeOutput }
public protocol PageRankReputationHandler { func configure(input: PageRankConfigureInput, storage: ConceptStorage) async throws -> PageRankConfigureOutput; func addContribution(input: PageRankAddContributionInput, storage: ConceptStorage) async throws -> PageRankAddContributionOutput; func compute(input: PageRankComputeInput, storage: ConceptStorage) async throws -> PageRankComputeOutput; func getScore(input: PageRankGetScoreInput, storage: ConceptStorage) async throws -> PageRankGetScoreOutput }
public protocol GlickoRatingHandler { func configure(input: GlickoRatingConfigureInput, storage: ConceptStorage) async throws -> GlickoRatingConfigureOutput; func recordOutcome(input: GlickoRecordOutcomeInput, storage: ConceptStorage) async throws -> GlickoRecordOutcomeOutput; func applyInactivityDecay(input: GlickoInactivityDecayInput, storage: ConceptStorage) async throws -> GlickoInactivityDecayOutput; func getReliableWeight(input: GlickoGetReliableWeightInput, storage: ConceptStorage) async throws -> GlickoGetReliableWeightOutput }

// MARK: - Glicko-2 Helpers

private let glickoTau = 0.5
private let glickoConvergenceTol = 0.000001
private func glickoG(_ phi: Double) -> Double { 1.0 / sqrt(1.0 + 3.0 * phi * phi / (Double.pi * Double.pi)) }
private func glickoE(_ mu: Double, _ muJ: Double, _ phiJ: Double) -> Double { 1.0 / (1.0 + exp(-glickoG(phiJ) * (mu - muJ))) }

// MARK: - Handler Implementations

public struct SimpleAccumulatorHandlerImpl: SimpleAccumulatorHandler {
    public init() {}
    public func configure(input: SimpleAccumulatorConfigureInput, storage: ConceptStorage) async throws -> SimpleAccumulatorConfigureOutput { let id = "acc-\(Int(Date().timeIntervalSince1970 * 1000))"; try await storage.put(relation: "accumulator", key: id, value: ["id": id, "decayRate": input.decayRate as Any, "cap": input.cap as Any]); try await storage.put(relation: "plugin-registry", key: "reputation-algorithm:\(id)", value: ["id": "reputation-algorithm:\(id)", "pluginKind": "reputation-algorithm", "provider": "SimpleAccumulator", "instanceId": id]); return .configured(config: id) }
    public func add(input: SimpleAccumulatorAddInput, storage: ConceptStorage) async throws -> SimpleAccumulatorAddOutput { let cfg = try await storage.get(relation: "accumulator", key: input.config); let cap = cfg?["cap"] as? Double; let key = "\(input.config):\(input.participant)"; let existing = try await storage.get(relation: "acc_score", key: key); let current = (existing?["score"] as? Double) ?? 0; var newScore = current + input.amount; if let cap = cap { newScore = min(newScore, cap) }; try await storage.put(relation: "acc_score", key: key, value: ["config": input.config, "participant": input.participant, "score": newScore, "updatedAt": ISO8601DateFormatter().string(from: Date())]); return .added(participant: input.participant, newScore: newScore) }
    public func applyDecay(input: SimpleAccumulatorDecayInput, storage: ConceptStorage) async throws -> SimpleAccumulatorDecayOutput { let cfg = try await storage.get(relation: "accumulator", key: input.config); guard let decayRate = cfg?["decayRate"] as? Double else { return .noDecay(participant: input.participant) }; let key = "\(input.config):\(input.participant)"; let existing = try await storage.get(relation: "acc_score", key: key); let current = (existing?["score"] as? Double) ?? 0; let newScore = current * (1 - decayRate); try await storage.put(relation: "acc_score", key: key, value: ["config": input.config, "participant": input.participant, "score": newScore, "updatedAt": ISO8601DateFormatter().string(from: Date())]); return .decayed(participant: input.participant, newScore: newScore, previousScore: current) }
    public func getScore(input: SimpleAccumulatorGetScoreInput, storage: ConceptStorage) async throws -> SimpleAccumulatorGetScoreOutput { let key = "\(input.config):\(input.participant)"; let existing = try await storage.get(relation: "acc_score", key: key); return .score(participant: input.participant, score: (existing?["score"] as? Double) ?? 0) }
}

public struct EloRatingHandlerImpl: EloRatingHandler {
    public init() {}
    public func configure(input: EloRatingConfigureInput, storage: ConceptStorage) async throws -> EloRatingConfigureOutput { let id = "elo-\(Int(Date().timeIntervalSince1970 * 1000))"; try await storage.put(relation: "elo_cfg", key: id, value: ["id": id, "kFactor": input.kFactor ?? 32, "initialRating": input.initialRating ?? 1500, "kFactorDecay": input.kFactorDecay as Any]); try await storage.put(relation: "plugin-registry", key: "reputation-algorithm:\(id)", value: ["id": "reputation-algorithm:\(id)", "pluginKind": "reputation-algorithm", "provider": "EloRating", "instanceId": id]); return .configured(config: id) }

    public func recordOutcome(input: EloRatingRecordOutcomeInput, storage: ConceptStorage) async throws -> EloRatingRecordOutcomeOutput {
        let cfg = try await storage.get(relation: "elo_cfg", key: input.config)
        let K = (cfg?["kFactor"] as? Double) ?? 32; let initial = (cfg?["initialRating"] as? Double) ?? 1500
        let wKey = "\(input.config):\(input.winner)"; let lKey = "\(input.config):\(input.loser)"
        let wRec = try await storage.get(relation: "elo_rating", key: wKey); let lRec = try await storage.get(relation: "elo_rating", key: lKey)
        let Rw = (wRec?["rating"] as? Double) ?? initial; let Rl = (lRec?["rating"] as? Double) ?? initial
        let wGames = (wRec?["gamesPlayed"] as? Int) ?? 0; let lGames = (lRec?["gamesPlayed"] as? Int) ?? 0
        let Ew = 1.0 / (1.0 + pow(10.0, (Rl - Rw) / 400.0)); let El = 1.0 / (1.0 + pow(10.0, (Rw - Rl) / 400.0))
        let winnerDelta = K * (1.0 - Ew); let loserDelta = K * (0.0 - El)
        let winnerNew = Rw + winnerDelta; let loserNew = Rl + loserDelta
        try await storage.put(relation: "elo_rating", key: wKey, value: ["config": input.config, "participant": input.winner, "rating": winnerNew, "gamesPlayed": wGames + 1])
        try await storage.put(relation: "elo_rating", key: lKey, value: ["config": input.config, "participant": input.loser, "rating": loserNew, "gamesPlayed": lGames + 1])
        return .updated(winnerNewRating: winnerNew, loserNewRating: loserNew, winnerDelta: winnerDelta, loserDelta: loserDelta)
    }

    public func recordDraw(input: EloRatingRecordDrawInput, storage: ConceptStorage) async throws -> EloRatingRecordDrawOutput {
        let cfg = try await storage.get(relation: "elo_cfg", key: input.config)
        let K = (cfg?["kFactor"] as? Double) ?? 32; let initial = (cfg?["initialRating"] as? Double) ?? 1500
        let keyA = "\(input.config):\(input.participantA)"; let keyB = "\(input.config):\(input.participantB)"
        let recA = try await storage.get(relation: "elo_rating", key: keyA); let recB = try await storage.get(relation: "elo_rating", key: keyB)
        let Ra = (recA?["rating"] as? Double) ?? initial; let Rb = (recB?["rating"] as? Double) ?? initial
        let gA = (recA?["gamesPlayed"] as? Int) ?? 0; let gB = (recB?["gamesPlayed"] as? Int) ?? 0
        let Ea = 1.0 / (1.0 + pow(10.0, (Rb - Ra) / 400.0)); let Eb = 1.0 / (1.0 + pow(10.0, (Ra - Rb) / 400.0))
        let aNew = Ra + K * (0.5 - Ea); let bNew = Rb + K * (0.5 - Eb)
        try await storage.put(relation: "elo_rating", key: keyA, value: ["config": input.config, "participant": input.participantA, "rating": aNew, "gamesPlayed": gA + 1])
        try await storage.put(relation: "elo_rating", key: keyB, value: ["config": input.config, "participant": input.participantB, "rating": bNew, "gamesPlayed": gB + 1])
        return .updated(aNewRating: aNew, bNewRating: bNew)
    }

    public func getRating(input: EloRatingGetRatingInput, storage: ConceptStorage) async throws -> EloRatingGetRatingOutput {
        let cfg = try await storage.get(relation: "elo_cfg", key: input.config); let initial = (cfg?["initialRating"] as? Double) ?? 1500
        let key = "\(input.config):\(input.participant)"; let rec = try await storage.get(relation: "elo_rating", key: key)
        return .rating(participant: input.participant, value: (rec?["rating"] as? Double) ?? initial, gamesPlayed: (rec?["gamesPlayed"] as? Int) ?? 0)
    }
}

public struct PeerAllocationHandlerImpl: PeerAllocationHandler {
    public init() {}
    public func openRound(input: PeerAllocationOpenRoundInput, storage: ConceptStorage) async throws -> PeerAllocationOpenRoundOutput { let id = "peer-alloc-\(Int(Date().timeIntervalSince1970 * 1000))"; let deadline = ISO8601DateFormatter().string(from: Date().addingTimeInterval(Double(input.deadlineDays) * 86400)); try await storage.put(relation: "peer_alloc", key: id, value: ["id": id, "budget": input.budget, "deadline": deadline, "status": "Open"]); try await storage.put(relation: "plugin-registry", key: "reputation-algorithm:\(id)", value: ["id": "reputation-algorithm:\(id)", "pluginKind": "reputation-algorithm", "provider": "PeerAllocation", "instanceId": id]); return .opened(round: id) }

    public func allocate(input: PeerAllocationAllocateInput, storage: ConceptStorage) async throws -> PeerAllocationAllocateOutput {
        guard let record = try await storage.get(relation: "peer_alloc", key: input.round) else { return .notFound(round: input.round) }
        guard (record["status"] as? String) == "Open" else { return .roundClosed(round: input.round) }
        if input.allocator == input.recipient { return .selfAllocation(allocator: input.allocator) }
        let key = "\(input.round):\(input.allocator):\(input.recipient)"
        try await storage.put(relation: "peer_alloc_entry", key: key, value: ["round": input.round, "allocator": input.allocator, "recipient": input.recipient, "amount": input.amount, "note": input.note as Any, "allocatedAt": ISO8601DateFormatter().string(from: Date())])
        let allByAllocator = try await storage.find(relation: "peer_alloc_entry", criteria: ["round": input.round, "allocator": input.allocator])
        let totalAllocated = allByAllocator.reduce(0.0) { $0 + (($1["amount"] as? Double) ?? 0) }
        return .allocated(round: input.round, totalAllocated: totalAllocated, budget: (record["budget"] as? Double) ?? 0)
    }

    public func finalize(input: PeerAllocationFinalizeInput, storage: ConceptStorage) async throws -> PeerAllocationFinalizeOutput {
        guard let record = try await storage.get(relation: "peer_alloc", key: input.round) else { return .notFound(round: input.round) }
        let allEntries = try await storage.find(relation: "peer_alloc_entry", criteria: ["round": input.round])
        var totals: [String: Double] = [:]
        for entry in allEntries { let r = (entry["recipient"] as? String) ?? ""; totals[r, default: 0] += (entry["amount"] as? Double) ?? 0 }
        let grandTotal = totals.values.reduce(0, +); let budget = (record["budget"] as? Double) ?? 0
        var normalized: [String: Double] = [:]
        for (recipient, total) in totals { normalized[recipient] = grandTotal > 0 ? (total / grandTotal) * budget : 0 }
        var updated = record; updated["status"] = "Finalized"; updated["finalizedAt"] = ISO8601DateFormatter().string(from: Date())
        try await storage.put(relation: "peer_alloc", key: input.round, value: updated)
        let encoder = JSONEncoder(); let resultsJson = String(data: try encoder.encode(normalized), encoding: .utf8) ?? "{}"
        return .finalized(round: input.round, results: resultsJson)
    }
}

public struct PageRankReputationHandlerImpl: PageRankReputationHandler {
    public init() {}
    public func configure(input: PageRankConfigureInput, storage: ConceptStorage) async throws -> PageRankConfigureOutput { let id = "pr-\(Int(Date().timeIntervalSince1970 * 1000))"; try await storage.put(relation: "pagerank", key: id, value: ["id": id, "dampingFactor": input.dampingFactor ?? 0.85, "iterations": input.iterations ?? 20]); try await storage.put(relation: "plugin-registry", key: "reputation-algorithm:\(id)", value: ["id": "reputation-algorithm:\(id)", "pluginKind": "reputation-algorithm", "provider": "PageRankReputation", "instanceId": id]); return .configured(config: id) }

    public func addContribution(input: PageRankAddContributionInput, storage: ConceptStorage) async throws -> PageRankAddContributionOutput {
        let edgeKey = "\(input.config):\(input.from):\(input.to)"
        try await storage.put(relation: "pr_edge", key: edgeKey, value: ["config": input.config, "from": input.from, "to": input.to, "weight": input.weight ?? 1.0])
        return .added(edge: "\(input.from):\(input.to)")
    }

    public func compute(input: PageRankComputeInput, storage: ConceptStorage) async throws -> PageRankComputeOutput {
        let cfg = try await storage.get(relation: "pagerank", key: input.config)
        let d = (cfg?["dampingFactor"] as? Double) ?? 0.85; let iterations = (cfg?["iterations"] as? Int) ?? 20
        let edges = try await storage.find(relation: "pr_edge", criteria: ["config": input.config])
        var nodeSet = Set<String>(); var outgoing: [String: [(to: String, weight: Double)]] = [:]
        for edge in edges { let from = (edge["from"] as? String) ?? ""; let to = (edge["to"] as? String) ?? ""; let w = (edge["weight"] as? Double) ?? 1.0; nodeSet.insert(from); nodeSet.insert(to); outgoing[from, default: []].append((to: to, weight: w)) }
        let nodes = Array(nodeSet); let N = Double(nodes.count)
        guard N > 0 else { return .computed(config: input.config, scores: "{}") }
        var scores: [String: Double] = [:]; for node in nodes { scores[node] = 1.0 / N }
        for _ in 0..<iterations { var newScores: [String: Double] = [:]; for node in nodes { newScores[node] = (1.0 - d) / N }; for node in nodes { let outs = outgoing[node] ?? []; let totalOut = outs.reduce(0.0) { $0 + $1.weight }; if totalOut == 0 { continue }; let nodeScore = scores[node]!; for edge in outs { let share = (edge.weight / totalOut) * nodeScore * d; newScores[edge.to]! += share } }; scores = newScores }
        for (node, score) in scores { try await storage.put(relation: "pr_score", key: "\(input.config):\(node)", value: ["config": input.config, "participant": node, "pageRank": score]) }
        let encoder = JSONEncoder(); let scoresJson = String(data: try encoder.encode(scores), encoding: .utf8) ?? "{}"
        return .computed(config: input.config, scores: scoresJson)
    }

    public func getScore(input: PageRankGetScoreInput, storage: ConceptStorage) async throws -> PageRankGetScoreOutput {
        let key = "\(input.config):\(input.participant)"; let record = try await storage.get(relation: "pr_score", key: key)
        return .score(participant: input.participant, pageRank: (record?["pageRank"] as? Double) ?? 0)
    }
}

public struct GlickoRatingHandlerImpl: GlickoRatingHandler {
    public init() {}
    public func configure(input: GlickoRatingConfigureInput, storage: ConceptStorage) async throws -> GlickoRatingConfigureOutput { let id = "glicko-\(Int(Date().timeIntervalSince1970 * 1000))"; try await storage.put(relation: "glicko_cfg", key: id, value: ["id": id, "initialRating": input.initialRating ?? 1500, "initialDeviation": input.initialDeviation ?? 350, "initialVolatility": input.initialVolatility ?? 0.06, "inactivityGrowthRate": input.inactivityGrowthRate ?? 30]); try await storage.put(relation: "plugin-registry", key: "reputation-algorithm:\(id)", value: ["id": "reputation-algorithm:\(id)", "pluginKind": "reputation-algorithm", "provider": "GlickoRating", "instanceId": id]); return .configured(config: id) }

    public func recordOutcome(input: GlickoRecordOutcomeInput, storage: ConceptStorage) async throws -> GlickoRecordOutcomeOutput {
        let cfg = try await storage.get(relation: "glicko_cfg", key: input.config)
        let initialRating = (cfg?["initialRating"] as? Double) ?? 1500; let initialDev = (cfg?["initialDeviation"] as? Double) ?? 350; let initialVol = (cfg?["initialVolatility"] as? Double) ?? 0.06
        let pKey = "\(input.config):\(input.participant)"; let oKey = "\(input.config):\(input.opponent)"
        let pRec = try await storage.get(relation: "glicko_rating", key: pKey); let oRec = try await storage.get(relation: "glicko_rating", key: oKey)
        let r = (pRec?["rating"] as? Double) ?? initialRating; let RD = (pRec?["deviation"] as? Double) ?? initialDev; let sigma = (pRec?["volatility"] as? Double) ?? initialVol
        let rj = (oRec?["rating"] as? Double) ?? initialRating; let RDj = (oRec?["deviation"] as? Double) ?? initialDev
        let mu = (r - 1500.0) / 173.7178; let phi = RD / 173.7178; let muJ = (rj - 1500.0) / 173.7178; let phiJ = RDj / 173.7178
        let s = input.outcome; let gPhiJ = glickoG(phiJ); let e = glickoE(mu, muJ, phiJ)
        let v = 1.0 / (gPhiJ * gPhiJ * e * (1.0 - e)); let delta = v * gPhiJ * (s - e)
        let a = log(sigma * sigma); let deltaSquared = delta * delta; let phiSquared = phi * phi
        func f(_ x: Double) -> Double { let ex = exp(x); let d = phiSquared + v + ex; return (ex * (deltaSquared - phiSquared - v - ex)) / (2.0 * d * d) - (x - a) / (glickoTau * glickoTau) }
        var A = a; var B: Double
        if deltaSquared > phiSquared + v { B = log(deltaSquared - phiSquared - v) } else { var k = 1.0; while f(a - k * glickoTau) < 0 { k += 1 }; B = a - k * glickoTau }
        var fA = f(A); var fB = f(B)
        for _ in 0..<100 { if abs(B - A) < glickoConvergenceTol { break }; let C = A + (A - B) * fA / (fB - fA); let fC = f(C); if fC * fB <= 0 { A = B; fA = fB } else { fA = fA / 2.0 }; B = C; fB = fC }
        let newSigma = exp(B / 2.0); let phiStar = sqrt(phiSquared + newSigma * newSigma); let newPhi = 1.0 / sqrt(1.0 / (phiStar * phiStar) + 1.0 / v); let newMu = mu + newPhi * newPhi * gPhiJ * (s - e)
        let newRating = 173.7178 * newMu + 1500.0; let newDeviation = 173.7178 * newPhi
        let games = ((pRec?["gamesPlayed"] as? Int) ?? 0) + 1
        try await storage.put(relation: "glicko_rating", key: pKey, value: ["config": input.config, "participant": input.participant, "rating": newRating, "deviation": newDeviation, "volatility": newSigma, "gamesPlayed": games])
        return .updated(participant: input.participant, newRating: newRating, newDeviation: newDeviation)
    }

    public func applyInactivityDecay(input: GlickoInactivityDecayInput, storage: ConceptStorage) async throws -> GlickoInactivityDecayOutput {
        let cfg = try await storage.get(relation: "glicko_cfg", key: input.config)
        let initialDev = (cfg?["initialDeviation"] as? Double) ?? 350; let growthRate = (cfg?["inactivityGrowthRate"] as? Double) ?? 30
        let key = "\(input.config):\(input.participant)"; guard let rec = try await storage.get(relation: "glicko_rating", key: key) else { return .notFound(participant: input.participant) }
        let phi = ((rec["deviation"] as? Double) ?? initialDev) / 173.7178; let sigma = (rec["volatility"] as? Double) ?? 0.06
        let periods = Int(Double(input.daysSinceActive) / growthRate)
        var phiNew = phi; for _ in 0..<periods { phiNew = sqrt(phiNew * phiNew + sigma * sigma) }
        let newDeviation = min(173.7178 * phiNew, initialDev)
        var updated = rec; updated["deviation"] = newDeviation
        try await storage.put(relation: "glicko_rating", key: key, value: updated)
        return .decayed(participant: input.participant, newDeviation: newDeviation)
    }

    public func getReliableWeight(input: GlickoGetReliableWeightInput, storage: ConceptStorage) async throws -> GlickoGetReliableWeightOutput {
        let cfg = try await storage.get(relation: "glicko_cfg", key: input.config)
        let initialRating = (cfg?["initialRating"] as? Double) ?? 1500; let initialDev = (cfg?["initialDeviation"] as? Double) ?? 350
        let key = "\(input.config):\(input.participant)"; let rec = try await storage.get(relation: "glicko_rating", key: key)
        let rating = (rec?["rating"] as? Double) ?? initialRating; let deviation = (rec?["deviation"] as? Double) ?? initialDev
        let reliability = max(0, 1.0 - deviation / initialDev)
        return .weight(participant: input.participant, rating: rating, deviation: deviation, reliability: reliability)
    }
}
