// Auto-generated by Clef Clef Bind — claude-skills target
// Concept: EnvironmentEntity
// Do not edit manually; regenerate with: clef interface generate

export async function handleEnvironmentEntitySkill(
  command: string,
  args: Record<string, any>,
  kernel: { handleRequest: (input: Record<string, unknown>) => Promise<any> },
): Promise<string> {
  const result = await kernel.handleRequest({ method: command, ...args });
  if (result.error) return `Error: ${result.error}`;
  return JSON.stringify(result.body, null, 2);
}

export const environmentEntitySkillCommands = ['register', 'get', 'findByEnvironment', 'findByConcept', 'findByRuntime', 'diffEnvironments', 'secretsAudit', 'featureFlags'];
