// Auto-generated by Clef Clef Bind — cli target
// Concept: SymbolRelationship
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const symbolRelationshipCommand = new Command('symbol-relationship')
  .description('Typed semantic relationships between Symbols beyond simple 
 reference implements , extends , overrides , generates , 
 configures , tests , documents . Extends the Linking Suite s 
 Reference Relation vocabulary with program analysis specific 
 edge types .');

symbolRelationshipCommand
  .command('add')
  .description('Create a typed relationship between two symbols . 
 Kind is one of : implements , extends , overrides , aliases , 
 generates , configures , tests , documents .')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--target <target>', 'Target')
  .requiredOption('--kind <kind>', 'Kind')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'add', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

symbolRelationshipCommand
  .command('find-from')
  .description('Find all relationships from a source symbol , optionally 
 filtered by kind . Results as serialized JSON array .')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--kind <kind>', 'Kind')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findFrom', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

symbolRelationshipCommand
  .command('find-to')
  .description('Find all relationships targeting a symbol , optionally 
 filtered by kind . Results as serialized JSON array .')
  .requiredOption('--target <target>', 'Target')
  .requiredOption('--kind <kind>', 'Kind')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'findTo', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

symbolRelationshipCommand
  .command('transitive-closure')
  .description('Follow relationships of a given kind transitively from 
 a starting symbol . Direction is forward or backward . 
 Returns reachable symbols and paths as serialized JSON .')
  .requiredOption('--start <start>', 'Start')
  .requiredOption('--kind <kind>', 'Kind')
  .requiredOption('--direction <direction>', 'Direction')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'transitiveClosure', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

symbolRelationshipCommand
  .command('get')
  .description('Retrieve relationship metadata .')
  .requiredOption('--relationship <relationship>', 'Relationship')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'get', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const symbolRelationshipCommandTree = {
  group: 'symbol-relationship',
  description: 'Typed semantic relationships between Symbols beyond simple 
 reference implements , extends , overrides , generates , 
 configures , tests , documents . Extends the Linking Suite s 
 Reference Relation vocabulary with program analysis specific 
 edge types .',
  commands: [{ action: 'add', command: 'add' }, { action: 'findFrom', command: 'find-from' }, { action: 'findTo', command: 'find-to' }, { action: 'transitiveClosure', command: 'transitive-closure' }, { action: 'get', command: 'get' }],
};
