// Auto-generated by Clef Clef Bind — cli target
// Concept: RuntimeCoverage
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const runtimeCoverageCommand = new Command('runtime-coverage')
  .description('Tracks which static entities have been exercised at runtime 
 the bridge between declared structure and observed behavior . 
 Answers which declared syncs/variants/widget states have
    actually fired in production? Combined with static dead variant 
 analysis , gives the complete picture : statically dead vs 
 dynamically dead .');

runtimeCoverageCommand
  .command('record')
  .description('Record that a static entity was exercised . Kind is one of : 
 action , variant , sync , state field , widget state , transition , 
 widget mount , widget unmount , widget render , 
 widget prop change , slot fill , slot clear , affordance match , 
 widget unnecessary render .')
  .requiredOption('--symbol <symbol>', 'Symbol')
  .requiredOption('--kind <kind>', 'Kind')
  .requiredOption('--flow-id <flowId>', 'Flow Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'record', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('coverage-report')
  .description('Coverage report for the given entity kind . Report as 
 serialized JSON : { totalEntities , exercised , 
 unexercised , coveragePct } .')
  .requiredOption('--kind <kind>', 'Kind')
  .requiredOption('--since <since>', 'Since')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'coverageReport', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('variant-coverage')
  .description('Variant coverage for a specific concept . Report as 
 serialized JSON array of { action , variant , exercised , 
 count , lastSeen } .')
  .requiredOption('--concept <concept>', 'Concept')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'variantCoverage', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('sync-coverage')
  .description('Sync coverage report . Results as serialized JSON array 
 of { sync , tier , exercised , count , avgDurationMs } .')
  .requiredOption('--since <since>', 'Since')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'syncCoverage', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('widget-state-coverage')
  .description('FSM state and transition coverage for a widget . 
 Results as serialized JSON array of { state , entered , 
 count , transitionsExercised , transitionsUnexercised } .')
  .requiredOption('--widget <widget>', 'Widget')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'widgetStateCoverage', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('widget-lifecycle-report')
  .description('Full widget lifecycle report : mount unmount counts , 
 active instances , render counts , unnecessary render 
 percentage , prop change sources , slot activity . 
 Report as serialized JSON .')
  .requiredOption('--widget <widget>', 'Widget')
  .requiredOption('--since <since>', 'Since')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'widgetLifecycleReport', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('widget-render-trace')
  .description('Per instance render trace : every render with timestamp , 
 duration , trigger ( signal field ) , props changed , and 
 whether the render was necessary . Results as serialized 
 JSON array .')
  .requiredOption('--widget-instance <widgetInstance>', 'Widget Instance')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'widgetRenderTrace', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('widget-comparison')
  .description('Rank all widgets by render performance . Results as 
 serialized JSON array of { widget , mountCount , 
 totalRenders , unnecessaryRenderPct , avgRenderMs , 
 p90RenderMs } .')
  .requiredOption('--since <since>', 'Since')
  .requiredOption('--top-n <topN>', 'Top N')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'widgetComparison', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

runtimeCoverageCommand
  .command('dead-at-runtime')
  .description('Return all static entities of the given kind that 
 have never been exercised at runtime . 
 Results as serialized JSON array of symbol strings .')
  .requiredOption('--kind <kind>', 'Kind')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'deadAtRuntime', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const runtimeCoverageCommandTree = {
  group: 'runtime-coverage',
  description: 'Tracks which static entities have been exercised at runtime 
 the bridge between declared structure and observed behavior . 
 Answers which declared syncs/variants/widget states have
    actually fired in production? Combined with static dead variant 
 analysis , gives the complete picture : statically dead vs 
 dynamically dead .',
  commands: [{ action: 'record', command: 'record' }, { action: 'coverageReport', command: 'coverage-report' }, { action: 'variantCoverage', command: 'variant-coverage' }, { action: 'syncCoverage', command: 'sync-coverage' }, { action: 'widgetStateCoverage', command: 'widget-state-coverage' }, { action: 'widgetLifecycleReport', command: 'widget-lifecycle-report' }, { action: 'widgetRenderTrace', command: 'widget-render-trace' }, { action: 'widgetComparison', command: 'widget-comparison' }, { action: 'deadAtRuntime', command: 'dead-at-runtime' }],
};
