// Auto-generated by Clef Clef Bind — mcp target
// Concept: Patch
// Do not edit manually; regenerate with: clef interface generate

export const patchTools = [
  {
    "type": "tool",
    "name": "patch_create",
    "description": "Create patch — Patch object created from base and target content hashes \n with the given edit script .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "base": {
          "type": "string"
        },
        "target": {
          "type": "string"
        },
        "effect": {
          "type": "string"
        }
      },
      "required": [
        "base",
        "target",
        "effect"
      ]
    }
  },
  {
    "type": "tool",
    "name": "patch_apply",
    "description": "Apply patch — Edit script applied to content . Returns transformed result .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "patchId": {
          "type": "string"
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "patchId",
        "content"
      ]
    }
  },
  {
    "type": "tool",
    "name": "patch_invert",
    "description": "Invert patch — Returns a new patch that undoes this patch . \n Base and target are swapped .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "patchId": {
          "type": "string"
        }
      },
      "required": [
        "patchId"
      ]
    }
  },
  {
    "type": "tool",
    "name": "patch_compose",
    "description": "Compose patch — Returns a new patch equivalent to applying first then second .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "first": {
          "type": "string"
        },
        "second": {
          "type": "string"
        }
      },
      "required": [
        "first",
        "second"
      ]
    }
  },
  {
    "type": "tool",
    "name": "patch_commute",
    "description": "Commute patch — Returns reordered patches such that applying p2Prime then \n p1Prime produces the same result as applying p1 then p2 .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "p1": {
          "type": "string"
        },
        "p2": {
          "type": "string"
        }
      },
      "required": [
        "p1",
        "p2"
      ]
    }
  },
  {
    "type": "tool",
    "name": "patch_apply_inverse",
    "description": "Apply inverse patch — Invert the patch to obtain its inverse edit script , then apply \n the inverse to content , effectively undoing the patch . Returns \n the transformed result that existed before the original patch \n was applied .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "patchId": {
          "type": "string"
        },
        "content": {
          "type": "string"
        }
      },
      "required": [
        "patchId",
        "content"
      ]
    }
  }
];
