// Auto-generated by Clef Clef Bind — cli target
// Concept: DAGHistory
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const dAGHistoryCommand = new Command('daghistory')
  .description('Organize versions into a directed acyclic graph supporting branching , 
 merging , and topological traversal . Nodes reference content by hash 
 and track parent relationships for full history reconstruction .');

dAGHistoryCommand
  .command('append')
  .description('New node appended to DAG with given parents . 
 Node becomes a root if parents set is empty .')
  .requiredOption('--parents <parents>', 'Parents')
  .requiredOption('--content-ref <contentRef>', 'Content Ref')
  .requiredOption('--metadata <metadata>', 'Metadata')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'append', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dAGHistoryCommand
  .command('ancestors')
  .description('Topologically ordered list of all ancestor nodes .')
  .requiredOption('--node-id <nodeId>', 'Node Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'ancestors', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dAGHistoryCommand
  .command('common-ancestor')
  .description('Nearest common ancestor of nodes a and b .')
  .requiredOption('--a <a>', 'A')
  .requiredOption('--b <b>', 'B')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'commonAncestor', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dAGHistoryCommand
  .command('descendants')
  .description('All descendant nodes in topological order .')
  .requiredOption('--node-id <nodeId>', 'Node Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'descendants', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dAGHistoryCommand
  .command('between')
  .description('Nodes on the path from ancestor to descendant , inclusive .')
  .requiredOption('--from <from>', 'From')
  .requiredOption('--to <to>', 'To')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'between', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dAGHistoryCommand
  .command('get-node')
  .description('Returns the full data for the given node .')
  .requiredOption('--node-id <nodeId>', 'Node Id')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'getNode', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const dAGHistoryCommandTree = {
  group: 'daghistory',
  description: 'Organize versions into a directed acyclic graph supporting branching , 
 merging , and topological traversal . Nodes reference content by hash 
 and track parent relationships for full history reconstruction .',
  commands: [{ action: 'append', command: 'append' }, { action: 'ancestors', command: 'ancestors' }, { action: 'commonAncestor', command: 'common-ancestor' }, { action: 'descendants', command: 'descendants' }, { action: 'between', command: 'between' }, { action: 'getNode', command: 'get-node' }],
};
