import React, { useState, useCallback, useMemo } from 'react';
import { View, Text, TextInput, Pressable, ScrollView, StyleSheet, type ViewStyle } from 'react-native';
export interface OptionItem { value: string; label: string; }
export interface ComboboxMultiProps { values?: string[]; defaultValues?: string[]; options: OptionItem[]; placeholder?: string; label: string; disabled?: boolean; maxSelections?: number; onChange?: (values: string[]) => void; onInputChange?: (v: string) => void; size?: 'sm'|'md'|'lg'; style?: ViewStyle; }
export const ComboboxMulti: React.FC<ComboboxMultiProps> = ({ values: vp, defaultValues = [], options, placeholder = 'Search...', label, disabled = false, maxSelections, onChange, onInputChange, style }) => {
  const [int, setInt] = useState(defaultValues); const vals = vp ?? int;
  const setV = useCallback((v: string[]) => { setInt(v); onChange?.(v); }, [onChange]);
  const [li, setLi] = useState(''); const [open, setOpen] = useState(false);
  const fil = useMemo(() => options.filter((o) => o.label.toLowerCase().includes(li.toLowerCase())), [options, li]);
  const toggle = useCallback((ov: string) => { if (vals.includes(ov)) setV(vals.filter((v) => v !== ov)); else { if (maxSelections !== undefined && vals.length >= maxSelections) return; setV([...vals, ov]); } setLi(''); onInputChange?.(''); }, [vals, maxSelections, setV, onInputChange]);
  const gl = useCallback((v: string) => options.find((o) => o.value === v)?.label ?? v, [options]);
  return (<View style={[s.root, style]}><Text style={s.lbl}>{label}</Text><View style={[s.wrap, disabled && s.dis]}>{vals.length > 0 && <View style={s.cl}>{vals.map((v) => (<View key={v} style={s.ch}><Text style={s.ct}>{gl(v)}</Text><Pressable onPress={() => setV(vals.filter((x) => x !== v))} hitSlop={4}><Text style={s.cd}>×</Text></Pressable></View>))}</View>}<TextInput value={li} placeholder={vals.length === 0 ? placeholder : ''} placeholderTextColor="#94a3b8" editable={!disabled} onChangeText={(t) => { setLi(t); onInputChange?.(t); setOpen(true); }} onFocus={() => setOpen(true)} onBlur={() => setTimeout(() => setOpen(false), 200)} accessibilityLabel={label} style={s.inp} /></View>{open && <ScrollView style={s.cnt} nestedScrollEnabled keyboardShouldPersistTaps="handled">{fil.length > 0 ? fil.map((o) => { const sel = vals.includes(o.value); return <Pressable key={o.value} onPress={() => toggle(o.value)} style={[s.it, sel && s.itS]}><Text style={s.itL}>{sel ? '✓ ' : ''}{o.label}</Text></Pressable>; }) : <View style={s.it}><Text style={s.em}>No results</Text></View>}</ScrollView>}</View>);
};
const s = StyleSheet.create({ root: { zIndex: 10 }, lbl: { fontSize: 14, fontWeight: '500', color: '#1e293b', marginBottom: 4 }, wrap: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 6, padding: 6, backgroundColor: '#fff', minHeight: 40 }, dis: { backgroundColor: '#f1f5f9', opacity: 0.6 }, cl: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 }, ch: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#e2e8f0', borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3 }, ct: { fontSize: 13, color: '#334155' }, cd: { fontSize: 16, color: '#64748b', marginLeft: 4 }, inp: { flex: 1, minWidth: 80, fontSize: 15, color: '#1e293b', paddingVertical: 4 }, cnt: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 6, backgroundColor: '#fff', maxHeight: 200, marginTop: 2 }, it: { paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#f8fafc' }, itS: { backgroundColor: '#eff6ff' }, itL: { fontSize: 14, color: '#334155' }, em: { fontSize: 14, color: '#94a3b8' } });
ComboboxMulti.displayName = 'ComboboxMulti'; export default ComboboxMulti;