import React, { useState, useCallback } from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet, type ViewStyle } from 'react-native';
export interface OptionItem { value: string; label: string; disabled?: boolean; }
export interface MultiSelectProps { values?: string[]; defaultValues?: string[]; options: OptionItem[]; placeholder?: string; label: string; disabled?: boolean; maxSelections?: number; onChange?: (values: string[]) => void; size?: 'sm'|'md'|'lg'; style?: ViewStyle; }
export const MultiSelect: React.FC<MultiSelectProps> = ({ values: vp, defaultValues = [], options, placeholder = 'Select...', label, disabled = false, maxSelections, onChange, style }) => {
  const [int, setInt] = useState(defaultValues); const vals = vp ?? int;
  const sv = useCallback((v: string[]) => { setInt(v); onChange?.(v); }, [onChange]);
  const [open, setOpen] = useState(false);
  const toggle = useCallback((v: string) => { if (vals.includes(v)) sv(vals.filter((x) => x !== v)); else { if (maxSelections !== undefined && vals.length >= maxSelections) return; sv([...vals, v]); } }, [vals, maxSelections, sv]);
  const gl = useCallback((v: string) => options.find((o) => o.value === v)?.label ?? v, [options]);
  return (<View style={[styles.root, style]}><Text style={styles.lbl}>{label}</Text><Pressable onPress={() => !disabled && setOpen(!open)} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ expanded: open, disabled }} style={[styles.trg, disabled && styles.dis]}>{vals.length > 0 ? <View style={styles.cl}>{vals.map((v) => (<View key={v} style={styles.ch}><Text style={styles.ct}>{gl(v)}</Text><Pressable onPress={() => sv(vals.filter((x) => x !== v))} hitSlop={4}><Text style={styles.cd}>\u00D7</Text></Pressable></View>))}</View> : <Text style={styles.ph}>{placeholder}</Text>}</Pressable>{open && <ScrollView style={styles.cnt} nestedScrollEnabled keyboardShouldPersistTaps="handled">{options.map((o) => { const sel = vals.includes(o.value); return <Pressable key={o.value} onPress={() => !o.disabled && toggle(o.value)} disabled={o.disabled} style={[styles.it, sel && styles.itS, o.disabled && styles.itD]}><Text style={styles.itL}>{sel ? '\u2713 ' : ''}{o.label}</Text></Pressable>; })}</ScrollView>}</View>);
};
const styles = StyleSheet.create({ root: { zIndex: 10 }, lbl: { fontSize: 14, fontWeight: '500', color: '#1e293b', marginBottom: 4 }, trg: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 6, backgroundColor: '#fff', padding: 8, minHeight: 40, justifyContent: 'center' }, dis: { backgroundColor: '#f1f5f9', opacity: 0.6 }, ph: { fontSize: 15, color: '#94a3b8' }, cl: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 }, ch: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#e2e8f0', borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3 }, ct: { fontSize: 13, color: '#334155' }, cd: { fontSize: 16, color: '#64748b', marginLeft: 4 }, cnt: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 6, backgroundColor: '#fff', maxHeight: 200, marginTop: 2 }, it: { paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#f8fafc' }, itS: { backgroundColor: '#eff6ff' }, itD: { opacity: 0.5 }, itL: { fontSize: 14, color: '#334155' } });
MultiSelect.displayName = 'MultiSelect'; export default MultiSelect;
