import React, { useState, useCallback } from 'react';
import { View, Text, TextInput, Pressable, StyleSheet, type ViewStyle } from 'react-native';
export interface NumberInputProps { value?: number; defaultValue?: number; min?: number; max?: number; step?: number; precision?: number; label: string; description?: string; error?: string; placeholder?: string; disabled?: boolean; readOnly?: boolean; onChange?: (value: number | undefined) => void; size?: 'sm'|'md'|'lg'; style?: ViewStyle; }
export const NumberInput: React.FC<NumberInputProps> = ({ value: vp, defaultValue, min, max, step = 1, precision, label, description, error, placeholder = '', disabled = false, readOnly = false, onChange, style }) => {
  const [int, setInt] = useState<number | undefined>(defaultValue); const value = vp ?? int;
  const sv = useCallback((v: number | undefined) => { setInt(v); onChange?.(v); }, [onChange]);
  const clamp = useCallback((v: number) => { let c = v; if (min !== undefined) c = Math.max(min, c); if (max !== undefined) c = Math.min(max, c); return c; }, [min, max]);
  const fmt = useCallback((v: number | undefined) => { if (v === undefined) return ''; if (precision !== undefined) return v.toFixed(precision); return String(v); }, [precision]);
  const inc = useCallback(() => { if (disabled || readOnly) return; sv(clamp((value ?? min ?? 0) + step)); }, [value, min, step, disabled, readOnly, clamp, sv]);
  const dec = useCallback(() => { if (disabled || readOnly) return; sv(clamp((value ?? min ?? 0) - step)); }, [value, min, step, disabled, readOnly, clamp, sv]);
  const atMin = min !== undefined && value !== undefined && value <= min; const atMax = max !== undefined && value !== undefined && value >= max;
  return (<View style={[styles.root, style]}><Text style={styles.lbl}>{label}</Text><View style={[styles.row, !!error && styles.rowE]}><Pressable onPress={dec} disabled={disabled || atMin} accessibilityLabel="Decrease" style={[styles.btn, (disabled || atMin) && styles.btnD]}><Text style={styles.btnT}>\u2212</Text></Pressable><TextInput value={fmt(value)} placeholder={placeholder} placeholderTextColor="#94a3b8" editable={!disabled && !readOnly} keyboardType="decimal-pad" onChangeText={(t) => { if (t === '') { sv(undefined); return; } const n = parseFloat(t); if (!isNaN(n)) sv(clamp(n)); }} accessibilityRole="adjustable" accessibilityLabel={label} style={styles.inp} /><Pressable onPress={inc} disabled={disabled || atMax} accessibilityLabel="Increase" style={[styles.btn, (disabled || atMax) && styles.btnD]}><Text style={styles.btnT}>+</Text></Pressable></View>{description && !error && <Text style={styles.desc}>{description}</Text>}{error && <Text style={styles.err} accessibilityRole="alert">{error}</Text>}</View>);
};
const styles = StyleSheet.create({ root: {}, lbl: { fontSize: 14, fontWeight: '500', color: '#1e293b', marginBottom: 4 }, row: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 6, backgroundColor: '#fff' }, rowE: { borderColor: '#ef4444' }, btn: { padding: 10, alignItems: 'center', justifyContent: 'center' }, btnD: { opacity: 0.3 }, btnT: { fontSize: 18, color: '#3b82f6', fontWeight: '600' }, inp: { flex: 1, fontSize: 15, color: '#1e293b', textAlign: 'center', paddingVertical: 8 }, desc: { marginTop: 4, fontSize: 12, color: '#64748b' }, err: { marginTop: 4, fontSize: 12, color: '#ef4444' } });
NumberInput.displayName = 'NumberInput'; export default NumberInput;
