import React, { useState, useCallback } from 'react';
import { View, Text, Pressable, ScrollView, StyleSheet, type ViewStyle } from 'react-native';
export interface OptionItem { value: string; label: string; disabled?: boolean; }
export interface SelectProps { value?: string; defaultValue?: string; options: OptionItem[]; placeholder?: string; label: string; disabled?: boolean; onChange?: (value: string) => void; size?: 'sm'|'md'|'lg'; style?: ViewStyle; }
export const Select: React.FC<SelectProps> = ({ value: vp, defaultValue = '', options, placeholder = 'Select...', label, disabled = false, onChange, style }) => {
  const [int, setInt] = useState(defaultValue); const value = vp ?? int;
  const sv = useCallback((v: string) => { setInt(v); onChange?.(v); }, [onChange]);
  const [open, setOpen] = useState(false); const selLabel = options.find((o) => o.value === value)?.label;
  return (<View style={[styles.root, style]}><Text style={styles.lbl}>{label}</Text><Pressable onPress={() => !disabled && setOpen(!open)} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ expanded: open, disabled }} style={[styles.trg, disabled && styles.trgD]}><Text style={[styles.trgT, !value && styles.ph]}>{selLabel ?? placeholder}</Text><Text style={styles.ind}>{open ? '\u25B2' : '\u25BC'}</Text></Pressable>{open && <ScrollView style={styles.cnt} nestedScrollEnabled keyboardShouldPersistTaps="handled">{options.map((o) => { const sel = o.value === value; return <Pressable key={o.value} onPress={() => { if (!o.disabled) { sv(o.value); setOpen(false); } }} disabled={o.disabled} style={[styles.it, sel && styles.itS, o.disabled && styles.itD]}><Text style={[styles.itL, sel && styles.itLS]}>{o.label}</Text>{sel && <Text style={styles.chk}>\u2713</Text>}</Pressable>; })}</ScrollView>}</View>);
};
const styles = StyleSheet.create({ root: { zIndex: 10 }, lbl: { fontSize: 14, fontWeight: '500', color: '#1e293b', marginBottom: 4 }, trg: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 6, backgroundColor: '#fff', paddingHorizontal: 12, paddingVertical: 10 }, trgD: { backgroundColor: '#f1f5f9', opacity: 0.6 }, trgT: { fontSize: 15, color: '#1e293b', flex: 1 }, ph: { color: '#94a3b8' }, ind: { fontSize: 10, color: '#64748b', marginLeft: 8 }, cnt: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 6, backgroundColor: '#fff', maxHeight: 200, marginTop: 2 }, it: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#f8fafc' }, itS: { backgroundColor: '#eff6ff' }, itD: { opacity: 0.5 }, itL: { fontSize: 14, color: '#334155', flex: 1 }, itLS: { color: '#1d4ed8', fontWeight: '500' }, chk: { color: '#3b82f6', fontSize: 14 } });
Select.displayName = 'Select'; export default Select;
