// Auto-generated by Clef Clef Bind — cli target
// Concept: DataFlowPath
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const dataFlowPathCommand = new Command('data-flow-path')
  .description('Traced flow of data from source to sink through the program . 
 Enables taint tracking , config value propagation tracing , 
 and data provenance analysis .');

dataFlowPathCommand
  .command('trace')
  .description('Find all data flow paths between a source and sink 
 symbol . Results as serialized JSON array of paths .')
  .requiredOption('--source <source>', 'Source')
  .requiredOption('--sink <sink>', 'Sink')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'trace', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dataFlowPathCommand
  .command('trace-from-config')
  .description('Trace all places a config value flows to . Results as 
 serialized JSON array of paths .')
  .requiredOption('--config-key <configKey>', 'Config Key')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'traceFromConfig', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dataFlowPathCommand
  .command('trace-to-output')
  .description('Trace all data sources that contribute to a generated 
 output file . Results as serialized JSON array of paths .')
  .requiredOption('--output <output>', 'Output')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'traceToOutput', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

dataFlowPathCommand
  .command('get')
  .description('Retrieve data flow path metadata .')
  .requiredOption('--path <path>', 'Path')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    const result = await globalThis.kernel.handleRequest({ method: 'get', ...opts });
    console.log(opts.json ? JSON.stringify(result) : result);
  });

export const dataFlowPathCommandTree = {
  group: 'data-flow-path',
  description: 'Traced flow of data from source to sink through the program . 
 Enables taint tracking , config value propagation tracing , 
 and data provenance analysis .',
  commands: [{ action: 'trace', command: 'trace' }, { action: 'traceFromConfig', command: 'trace-from-config' }, { action: 'traceToOutput', command: 'trace-to-output' }, { action: 'get', command: 'get' }],
};
