// Auto-generated by Clef Clef Bind — cli target
// Concept: Diff
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const diffCommand = new Command('diff')
  .description('Compute the minimal representation of differences between two content states , using a pluggable algorithm selected by content type and context');

diffCommand
  .command('register-provider')
  .description('Registers a new diff algorithm provider for the given content types .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--content-types <contentTypes>', 'Content Types')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Diff', 'registerProvider', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

diffCommand
  .command('diff')
  .description('Contents are byte identical . No edit script needed .')
  .requiredOption('--content-a <contentA>', 'Content A')
  .requiredOption('--content-b <contentB>', 'Content B')
  .requiredOption('--algorithm <algorithm>', 'Algorithm')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Diff', 'diff', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

diffCommand
  .command('patch')
  .description('Applies edit script to content , producing transformed result .')
  .requiredOption('--content <content>', 'Content')
  .requiredOption('--edit-script <editScript>', 'Edit Script')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Diff', 'patch', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const diffCommandTree = {
  group: 'diff',
  description: 'Compute the minimal representation of differences between two content states , using a pluggable algorithm selected by content type and context',
  commands: [{ action: 'registerProvider', command: 'register-provider' }, { action: 'diff', command: 'diff' }, { action: 'patch', command: 'patch' }],
};
