// Auto-generated by Clef Clef Bind — mcp target
// Concept: FilterRepresentation
// Do not edit manually; regenerate with: clef interface generate

export const filterRepresentationTools = [
  {
    "type": "tool",
    "name": "filter_representation_register_kind",
    "description": "Register kind filterrepresentation — Register a representation kind provider so that parse and print \n dispatches can route to it . Called by provider registration syncs \n to declare that a handler exists for this kind ( toggle group , \n text dsl , url params , visual builder , odata ) .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "kind"
      ]
    }
  },
  {
    "type": "tool",
    "name": "filter_representation_register",
    "description": "Register filterrepresentation — Register a named representation provider of a given kind . The name \n identifies the provider and must be unique across all registered \n representations .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "kind"
      ]
    }
  },
  {
    "type": "tool",
    "name": "filter_representation_parse",
    "description": "Parse filterrepresentation — Forward direction : convert a representation string authored in the \n given kind s format into a canonical FilterNode IR JSON string . \n Dispatches to the appropriate kind provider through sync wiring .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "repr": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "repr",
        "kind"
      ]
    }
  },
  {
    "type": "tool",
    "name": "filter_representation_print",
    "description": "Print filterrepresentation — Reverse direction : convert a canonical FilterNode IR JSON string into \n the authoring representation string for the given kind . The produced \n repr can be fed back into parse to recover the original tree \n ( GetPut round trip law ) .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "tree": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "tree",
        "kind"
      ]
    }
  },
  {
    "type": "tool",
    "name": "filter_representation_can_print",
    "description": "Can print filterrepresentation — Check whether the kind provider can faithfully represent the given \n FilterNode tree without loss . Returns true when the round trip \n parse ( print ( tree , kind ) , kind ) would recover the original tree ; false when the kind s format is not expressive enough .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "tree": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "tree",
        "kind"
      ]
    }
  },
  {
    "type": "resource-template",
    "name": "filter_representation_list",
    "uriTemplate": "urn:clef://filter-representations",
    "description": "List filterrepresentation — Return all registered representations as a JSON array , each entry \n containing the representation s name and kind ."
  }
];
