// Auto-generated by Clef Clef Bind — cli target
// Concept: Symbol
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const symbolCommand = new Command('symbol')
  .description('Globally unique , cross file identifier for any named entity in the project . Provides hierarchical symbol strings ( e . g . clef/concept/Article , ts/function/src/handlers/article.ts/createArticle ) that unify identity across languages , file formats , and project layers');

symbolCommand
  .command('register')
  .description('Create a new symbol with a globally unique symbol string . Kind is one of : function , class , type , variable , concept , action , variant , state field , sync , config key .')
  .requiredOption('--symbol-string <symbolString>', 'Symbol String')
  .requiredOption('--kind <kind>', 'Kind')
  .requiredOption('--display-name <displayName>', 'Display Name')
  .requiredOption('--defining-file <definingFile>', 'Defining File')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Symbol', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

symbolCommand
  .command('resolve')
  .description('Resolve a symbol string to its registered symbol .')
  .requiredOption('--symbol-string <symbolString>', 'Symbol String')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Symbol', 'resolve', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

symbolCommand
  .command('find-by-kind')
  .description('Return all symbols of the given kind , optionally filtered by namespace . Results as serialized JSON array .')
  .requiredOption('--kind <kind>', 'Kind')
  .requiredOption('--namespace <namespace>', 'Namespace')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Symbol', 'findByKind', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

symbolCommand
  .command('find-by-file')
  .description('Return all symbols defined in the given file . Results as serialized JSON array .')
  .requiredOption('--file <file>', 'File')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Symbol', 'findByFile', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

symbolCommand
  .command('rename')
  .description('Rename a symbol and update all tracked occurrences .')
  .requiredOption('--symbol <symbol>', 'Symbol')
  .requiredOption('--new-name <newName>', 'New Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Symbol', 'rename', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

symbolCommand
  .command('get')
  .description('Retrieve a symbol s metadata .')
  .requiredOption('--symbol <symbol>', 'Symbol')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/Symbol', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const symbolCommandTree = {
  group: 'symbol',
  description: 'Globally unique , cross file identifier for any named entity in the project . Provides hierarchical symbol strings ( e . g . clef/concept/Article , ts/function/src/handlers/article.ts/createArticle ) that unify identity across languages , file formats , and project layers',
  commands: [{ action: 'register', command: 'register' }, { action: 'resolve', command: 'resolve' }, { action: 'findByKind', command: 'find-by-kind' }, { action: 'findByFile', command: 'find-by-file' }, { action: 'rename', command: 'rename' }, { action: 'get', command: 'get' }],
};
