// Auto-generated by Clef Clef Bind — mcp target
// Concept: SymbolRelationship
// Do not edit manually; regenerate with: clef interface generate

export const symbolRelationshipTools = [
  {
    "type": "tool",
    "name": "symbol_relationship_add",
    "description": "Add symbolrelationship — Create a typed relationship between two symbols . \n Kind is one of : implements , extends , overrides , aliases , \n generates , configures , tests , documents .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "source": {
          "type": "string"
        },
        "target": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        }
      },
      "required": [
        "source",
        "target",
        "kind"
      ]
    }
  },
  {
    "type": "resource",
    "name": "symbol_relationship_find_from",
    "uri": "urn:clef://symbol-relationships/{source}",
    "description": "Find from symbolrelationship — Find all relationships from a source symbol , optionally \n filtered by kind . Results as serialized JSON array ."
  },
  {
    "type": "resource",
    "name": "symbol_relationship_find_to",
    "uri": "urn:clef://symbol-relationships/{target}",
    "description": "Find to symbolrelationship — Find all relationships targeting a symbol , optionally \n filtered by kind . Results as serialized JSON array ."
  },
  {
    "type": "tool",
    "name": "symbol_relationship_transitive_closure",
    "description": "Transitive closure symbolrelationship — Follow relationships of a given kind transitively from \n a starting symbol . Direction is forward or backward . \n Returns reachable symbols and paths as serialized JSON .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "start": {
          "type": "string"
        },
        "kind": {
          "type": "string"
        },
        "direction": {
          "type": "string"
        }
      },
      "required": [
        "start",
        "kind",
        "direction"
      ]
    }
  },
  {
    "type": "resource",
    "name": "symbol_relationship_get",
    "uri": "urn:clef://symbol-relationships/{relationship}",
    "description": "Get symbolrelationship — Retrieve relationship metadata ."
  }
];
