/**
 * Vitest Setup — Auto-wrap FunctionalConceptHandler calls
 *
 * When a test calls `handler.action(input, storage)` on a
 * FunctionalConceptHandler, the action returns a StorageProgram
 * instead of a result. This setup patches the global test
 * environment so that if a handler action returns a StorageProgram
 * (object with `instructions` array), it's automatically
 * interpreted before returning to the test.
 *
 * This is a transitional compatibility layer during the migration
 * from imperative to functional handlers.
 */

// This file is intentionally left as a documentation marker.
// The actual compatibility is handled by the test helpers in
// tests/helpers/invoke-handler.ts and will be integrated into
// the test generation pipeline.
//
// Tests that use their own `run()` helper (10 files) already
// call handler.action(input) and interpret the StorageProgram.
//
// Tests that call handler.action(input, storage) directly (132
// files) will be regenerated by the updated typescript-gen to
// use the interpret() pattern.
