// Auto-generated entrypoint for suite "clef-devtools", target "mcp"
import { pathToFileURL } from 'url';
import { bootMcpServer } from '../../handlers/ts/framework/mcp-server.handler';
import { specParserTools } from './spec-parser/spec-parser.tools';
import { schemaGenTools } from './schema-gen/schema-gen.tools';
import { syncParserTools } from './sync-parser/sync-parser.tools';
import { syncCompilerTools } from './sync-compiler/sync-compiler.tools';
import { flowTraceTools } from './flow-trace/flow-trace.tools';
import { deploymentValidatorTools } from './deployment-validator/deployment-validator.tools';
import { projectScaffoldTools } from './project-scaffold/project-scaffold.tools';
import { devServerTools } from './dev-server/dev-server.tools';
import { suiteManagerTools } from './suite-manager/suite-manager.tools';
import { kernelBootTools } from './kernel-boot/kernel-boot.tools';
import { deployPlanTools } from './deploy-plan/deploy-plan.tools';
import { vercelRuntimeTools } from './vercel-runtime/vercel-runtime.tools';
import { deployOrchestratorTools } from './deploy-orchestrator/deploy-orchestrator.tools';
import { suiteScaffoldGenTools } from './suite-scaffold-gen/suite-scaffold-gen.tools';
import { deployScaffoldGenTools } from './deploy-scaffold-gen/deploy-scaffold-gen.tools';
import { interfaceScaffoldGenTools } from './interface-scaffold-gen/interface-scaffold-gen.tools';
import { conceptScaffoldGenTools } from './concept-scaffold-gen/concept-scaffold-gen.tools';
import { syncScaffoldGenTools } from './sync-scaffold-gen/sync-scaffold-gen.tools';
import { handlerScaffoldGenTools } from './handler-scaffold-gen/handler-scaffold-gen.tools';
import { storageAdapterScaffoldGenTools } from './storage-adapter-scaffold-gen/storage-adapter-scaffold-gen.tools';
import { transportAdapterScaffoldGenTools } from './transport-adapter-scaffold-gen/transport-adapter-scaffold-gen.tools';
import { surfaceComponentScaffoldGenTools } from './surface-component-scaffold-gen/surface-component-scaffold-gen.tools';
import { surfaceThemeScaffoldGenTools } from './surface-theme-scaffold-gen/surface-theme-scaffold-gen.tools';
import { derivedScaffoldGenTools } from './derived-scaffold-gen/derived-scaffold-gen.tools';
import { generatorTools } from './generator/generator.tools';
import { projectionTools } from './projection/projection.tools';
import { apiSurfaceTools } from './api-surface/api-surface.tools';
import { symbolTools } from './symbol/symbol.tools';
import { symbolOccurrenceTools } from './symbol-occurrence/symbol-occurrence.tools';
import { scopeGraphTools } from './scope-graph/scope-graph.tools';
import { symbolRelationshipTools } from './symbol-relationship/symbol-relationship.tools';
import { conceptEntityTools } from './concept-entity/concept-entity.tools';
import { actionEntityTools } from './action-entity/action-entity.tools';
import { variantEntityTools } from './variant-entity/variant-entity.tools';
import { stateFieldTools } from './state-field/state-field.tools';
import { syncEntityTools } from './sync-entity/sync-entity.tools';
import { widgetEntityTools } from './widget-entity/widget-entity.tools';
import { anatomyPartEntityTools } from './anatomy-part-entity/anatomy-part-entity.tools';
import { widgetStateEntityTools } from './widget-state-entity/widget-state-entity.tools';
import { widgetPropEntityTools } from './widget-prop-entity/widget-prop-entity.tools';
import { themeEntityTools } from './theme-entity/theme-entity.tools';
import { interactorEntityTools } from './interactor-entity/interactor-entity.tools';
import { runtimeFlowTools } from './runtime-flow/runtime-flow.tools';
import { runtimeCoverageTools } from './runtime-coverage/runtime-coverage.tools';
import { performanceProfileTools } from './performance-profile/performance-profile.tools';
import { errorCorrelationTools } from './error-correlation/error-correlation.tools';
import { derivedEntityTools } from './derived-entity/derived-entity.tools';
import { handlerEntityTools } from './handler-entity/handler-entity.tools';
import { widgetImplementationEntityTools } from './widget-implementation-entity/widget-implementation-entity.tools';
import { themeImplementationEntityTools } from './theme-implementation-entity/theme-implementation-entity.tools';
import { deploymentEntityTools } from './deployment-entity/deployment-entity.tools';
import { suiteManifestEntityTools } from './suite-manifest-entity/suite-manifest-entity.tools';
import { interfaceEntityTools } from './interface-entity/interface-entity.tools';
import { deploymentHealthTools } from './deployment-health/deployment-health.tools';
import { infrastructureEntityTools } from './infrastructure-entity/infrastructure-entity.tools';
import { generationProvenanceTools } from './generation-provenance/generation-provenance.tools';
import { testEntityTools } from './test-entity/test-entity.tools';
import { environmentEntityTools } from './environment-entity/environment-entity.tools';
import { dependenceGraphTools } from './dependence-graph/dependence-graph.tools';
import { dataFlowPathTools } from './data-flow-path/data-flow-path.tools';
import { programSliceTools } from './program-slice/program-slice.tools';
import { analysisRuleTools } from './analysis-rule/analysis-rule.tools';
import { semanticEmbeddingTools } from './semantic-embedding/semantic-embedding.tools';
import { scoreApiTools } from './score-api/score-api.tools';
import { scoreIndexTools } from './score-index/score-index.tools';
import { branchTools } from './branch/branch.tools';
import { changeStreamTools } from './change-stream/change-stream.tools';
import { contentHashTools } from './content-hash/content-hash.tools';
import { dAGHistoryTools } from './daghistory/daghistory.tools';
import { diffTools } from './diff/diff.tools';
import { mergeTools } from './merge/merge.tools';
import { patchTools } from './patch/patch.tools';
import { refTools } from './ref/ref.tools';
import { retentionPolicyTools } from './retention-policy/retention-policy.tools';
import { schemaEvolutionTools } from './schema-evolution/schema-evolution.tools';
import { temporalVersionTools } from './temporal-version/temporal-version.tools';
import { attributionTools } from './attribution/attribution.tools';
import { causalClockTools } from './causal-clock/causal-clock.tools';
import { conflictResolutionTools } from './conflict-resolution/conflict-resolution.tools';
import { inlineAnnotationTools } from './inline-annotation/inline-annotation.tools';
import { pessimisticLockTools } from './pessimistic-lock/pessimistic-lock.tools';
import { replicaTools } from './replica/replica.tools';
import { signatureTools } from './signature/signature.tools';
import { actionGuideTools } from './action-guide/action-guide.tools';
import { enrichmentRendererTools } from './enrichment-renderer/enrichment-renderer.tools';
import { storageProgramTools } from './storage-program/storage-program.tools';
import { functionalHandlerTools } from './functional-handler/functional-handler.tools';
import { programInterpreterTools } from './program-interpreter/program-interpreter.tools';
import { programAnalysisTools } from './program-analysis/program-analysis.tools';
import { programCacheTools } from './program-cache/program-cache.tools';
import { lensTools } from './lens/lens.tools';
import { effectHandlerTools } from './effect-handler/effect-handler.tools';
import { completionCoverageTools } from './completion-coverage/completion-coverage.tools';
import { readWriteSetProviderTools } from './read-write-set-provider/read-write-set-provider.tools';
import { commutativityProviderTools } from './commutativity-provider/commutativity-provider.tools';
import { parallelismProviderTools } from './parallelism-provider/parallelism-provider.tools';
import { deadBranchProviderTools } from './dead-branch-provider/dead-branch-provider.tools';
import { invariantExtractionProviderTools } from './invariant-extraction-provider/invariant-extraction-provider.tools';
import { lensExtractionProviderTools } from './lens-extraction-provider/lens-extraction-provider.tools';
import { variantExtractionProviderTools } from './variant-extraction-provider/variant-extraction-provider.tools';
import { transportEffectProviderTools } from './transport-effect-provider/transport-effect-provider.tools';
import { renderTransformTools } from './render-transform/render-transform.tools';
import { tokenRemapProviderTools } from './token-remap-provider/token-remap-provider.tools';
import { a11yAdaptProviderTools } from './a11y-adapt-provider/a11y-adapt-provider.tools';
import { bindRewriteProviderTools } from './bind-rewrite-provider/bind-rewrite-provider.tools';
import { customTransformProviderTools } from './custom-transform-provider/custom-transform-provider.tools';
import { transformExtractionProviderTools } from './transform-extraction-provider/transform-extraction-provider.tools';

export const tools = [...specParserTools, ...schemaGenTools, ...syncParserTools, ...syncCompilerTools, ...flowTraceTools, ...deploymentValidatorTools, ...projectScaffoldTools, ...devServerTools, ...suiteManagerTools, ...kernelBootTools, ...deployPlanTools, ...vercelRuntimeTools, ...deployOrchestratorTools, ...suiteScaffoldGenTools, ...deployScaffoldGenTools, ...interfaceScaffoldGenTools, ...conceptScaffoldGenTools, ...syncScaffoldGenTools, ...handlerScaffoldGenTools, ...storageAdapterScaffoldGenTools, ...transportAdapterScaffoldGenTools, ...surfaceComponentScaffoldGenTools, ...surfaceThemeScaffoldGenTools, ...derivedScaffoldGenTools, ...generatorTools, ...projectionTools, ...apiSurfaceTools, ...symbolTools, ...symbolOccurrenceTools, ...scopeGraphTools, ...symbolRelationshipTools, ...conceptEntityTools, ...actionEntityTools, ...variantEntityTools, ...stateFieldTools, ...syncEntityTools, ...widgetEntityTools, ...anatomyPartEntityTools, ...widgetStateEntityTools, ...widgetPropEntityTools, ...themeEntityTools, ...interactorEntityTools, ...runtimeFlowTools, ...runtimeCoverageTools, ...performanceProfileTools, ...errorCorrelationTools, ...derivedEntityTools, ...handlerEntityTools, ...widgetImplementationEntityTools, ...themeImplementationEntityTools, ...deploymentEntityTools, ...suiteManifestEntityTools, ...interfaceEntityTools, ...deploymentHealthTools, ...infrastructureEntityTools, ...generationProvenanceTools, ...testEntityTools, ...environmentEntityTools, ...dependenceGraphTools, ...dataFlowPathTools, ...programSliceTools, ...analysisRuleTools, ...semanticEmbeddingTools, ...scoreApiTools, ...scoreIndexTools, ...branchTools, ...changeStreamTools, ...contentHashTools, ...dAGHistoryTools, ...diffTools, ...mergeTools, ...patchTools, ...refTools, ...retentionPolicyTools, ...schemaEvolutionTools, ...temporalVersionTools, ...attributionTools, ...causalClockTools, ...conflictResolutionTools, ...inlineAnnotationTools, ...pessimisticLockTools, ...replicaTools, ...signatureTools, ...actionGuideTools, ...enrichmentRendererTools, ...storageProgramTools, ...functionalHandlerTools, ...programInterpreterTools, ...programAnalysisTools, ...programCacheTools, ...lensTools, ...effectHandlerTools, ...completionCoverageTools, ...readWriteSetProviderTools, ...commutativityProviderTools, ...parallelismProviderTools, ...deadBranchProviderTools, ...invariantExtractionProviderTools, ...lensExtractionProviderTools, ...variantExtractionProviderTools, ...transportEffectProviderTools, ...renderTransformTools, ...tokenRemapProviderTools, ...a11yAdaptProviderTools, ...bindRewriteProviderTools, ...customTransformProviderTools, ...transformExtractionProviderTools];

const isDirectRun = Boolean(process.argv[1]) && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isDirectRun) {
  const manifestPath = process.argv[2];
  if (!manifestPath) {
    console.error('Usage: npx tsx ./.claude/mcp/index.ts <manifest-path>');
    process.exit(1);
  }
  await bootMcpServer(manifestPath);
}
