// Auto-generated entrypoint for suite "clef-devtools", target "cli"
import { Command } from 'commander';
import { SpecParserCommand } from './SpecParser/SpecParser.command';
import { SchemaGenCommand } from './SchemaGen/SchemaGen.command';
import { SyncParserCommand } from './SyncParser/SyncParser.command';
import { SyncCompilerCommand } from './SyncCompiler/SyncCompiler.command';
import { FlowTraceCommand } from './FlowTrace/FlowTrace.command';
import { DeploymentValidatorCommand } from './DeploymentValidator/DeploymentValidator.command';
import { ProjectScaffoldCommand } from './ProjectScaffold/ProjectScaffold.command';
import { DevServerCommand } from './DevServer/DevServer.command';
import { SuiteManagerCommand } from './SuiteManager/SuiteManager.command';
import { SuiteScaffoldGenCommand } from './SuiteScaffoldGen/SuiteScaffoldGen.command';
import { DeployScaffoldGenCommand } from './DeployScaffoldGen/DeployScaffoldGen.command';
import { InterfaceScaffoldGenCommand } from './InterfaceScaffoldGen/InterfaceScaffoldGen.command';
import { ConceptScaffoldGenCommand } from './ConceptScaffoldGen/ConceptScaffoldGen.command';
import { SyncScaffoldGenCommand } from './SyncScaffoldGen/SyncScaffoldGen.command';
import { HandlerScaffoldGenCommand } from './HandlerScaffoldGen/HandlerScaffoldGen.command';
import { StorageAdapterScaffoldGenCommand } from './StorageAdapterScaffoldGen/StorageAdapterScaffoldGen.command';
import { TransportAdapterScaffoldGenCommand } from './TransportAdapterScaffoldGen/TransportAdapterScaffoldGen.command';
import { SurfaceComponentScaffoldGenCommand } from './SurfaceComponentScaffoldGen/SurfaceComponentScaffoldGen.command';
import { SurfaceThemeScaffoldGenCommand } from './SurfaceThemeScaffoldGen/SurfaceThemeScaffoldGen.command';
import { DerivedScaffoldGenCommand } from './DerivedScaffoldGen/DerivedScaffoldGen.command';
import { GeneratorCommand } from './Generator/Generator.command';
import { ProjectionCommand } from './Projection/Projection.command';
import { ApiSurfaceCommand } from './ApiSurface/ApiSurface.command';
import { SymbolCommand } from './Symbol/Symbol.command';
import { SymbolOccurrenceCommand } from './SymbolOccurrence/SymbolOccurrence.command';
import { ScopeGraphCommand } from './ScopeGraph/ScopeGraph.command';
import { SymbolRelationshipCommand } from './SymbolRelationship/SymbolRelationship.command';
import { ConceptEntityCommand } from './ConceptEntity/ConceptEntity.command';
import { ActionEntityCommand } from './ActionEntity/ActionEntity.command';
import { VariantEntityCommand } from './VariantEntity/VariantEntity.command';
import { StateFieldCommand } from './StateField/StateField.command';
import { SyncEntityCommand } from './SyncEntity/SyncEntity.command';
import { WidgetEntityCommand } from './WidgetEntity/WidgetEntity.command';
import { AnatomyPartEntityCommand } from './AnatomyPartEntity/AnatomyPartEntity.command';
import { WidgetStateEntityCommand } from './WidgetStateEntity/WidgetStateEntity.command';
import { WidgetPropEntityCommand } from './WidgetPropEntity/WidgetPropEntity.command';
import { ThemeEntityCommand } from './ThemeEntity/ThemeEntity.command';
import { InteractorEntityCommand } from './InteractorEntity/InteractorEntity.command';
import { RuntimeFlowCommand } from './RuntimeFlow/RuntimeFlow.command';
import { RuntimeCoverageCommand } from './RuntimeCoverage/RuntimeCoverage.command';
import { PerformanceProfileCommand } from './PerformanceProfile/PerformanceProfile.command';
import { ErrorCorrelationCommand } from './ErrorCorrelation/ErrorCorrelation.command';
import { DerivedEntityCommand } from './DerivedEntity/DerivedEntity.command';
import { HandlerEntityCommand } from './HandlerEntity/HandlerEntity.command';
import { WidgetImplementationEntityCommand } from './WidgetImplementationEntity/WidgetImplementationEntity.command';
import { ThemeImplementationEntityCommand } from './ThemeImplementationEntity/ThemeImplementationEntity.command';
import { DeploymentEntityCommand } from './DeploymentEntity/DeploymentEntity.command';
import { SuiteManifestEntityCommand } from './SuiteManifestEntity/SuiteManifestEntity.command';
import { InterfaceEntityCommand } from './InterfaceEntity/InterfaceEntity.command';
import { DeploymentHealthCommand } from './DeploymentHealth/DeploymentHealth.command';
import { InfrastructureEntityCommand } from './InfrastructureEntity/InfrastructureEntity.command';
import { GenerationProvenanceCommand } from './GenerationProvenance/GenerationProvenance.command';
import { TestEntityCommand } from './TestEntity/TestEntity.command';
import { EnvironmentEntityCommand } from './EnvironmentEntity/EnvironmentEntity.command';
import { DependenceGraphCommand } from './DependenceGraph/DependenceGraph.command';
import { DataFlowPathCommand } from './DataFlowPath/DataFlowPath.command';
import { ProgramSliceCommand } from './ProgramSlice/ProgramSlice.command';
import { AnalysisRuleCommand } from './AnalysisRule/AnalysisRule.command';
import { SemanticEmbeddingCommand } from './SemanticEmbedding/SemanticEmbedding.command';
import { ScoreApiCommand } from './ScoreApi/ScoreApi.command';
import { ScoreIndexCommand } from './ScoreIndex/ScoreIndex.command';
import { BranchCommand } from './Branch/Branch.command';
import { ChangeStreamCommand } from './ChangeStream/ChangeStream.command';
import { ContentHashCommand } from './ContentHash/ContentHash.command';
import { DAGHistoryCommand } from './DAGHistory/DAGHistory.command';
import { DiffCommand } from './Diff/Diff.command';
import { MergeCommand } from './Merge/Merge.command';
import { PatchCommand } from './Patch/Patch.command';
import { RefCommand } from './Ref/Ref.command';
import { RetentionPolicyCommand } from './RetentionPolicy/RetentionPolicy.command';
import { SchemaEvolutionCommand } from './SchemaEvolution/SchemaEvolution.command';
import { TemporalVersionCommand } from './TemporalVersion/TemporalVersion.command';
import { AttributionCommand } from './Attribution/Attribution.command';
import { CausalClockCommand } from './CausalClock/CausalClock.command';
import { ConflictResolutionCommand } from './ConflictResolution/ConflictResolution.command';
import { InlineAnnotationCommand } from './InlineAnnotation/InlineAnnotation.command';
import { PessimisticLockCommand } from './PessimisticLock/PessimisticLock.command';
import { ReplicaCommand } from './Replica/Replica.command';
import { SignatureCommand } from './Signature/Signature.command';
import { ActionGuideCommand } from './ActionGuide/ActionGuide.command';
import { EnrichmentRendererCommand } from './EnrichmentRenderer/EnrichmentRenderer.command';

const program = new Command();

  program.addCommand(SpecParserCommand);
  program.addCommand(SchemaGenCommand);
  program.addCommand(SyncParserCommand);
  program.addCommand(SyncCompilerCommand);
  program.addCommand(FlowTraceCommand);
  program.addCommand(DeploymentValidatorCommand);
  program.addCommand(ProjectScaffoldCommand);
  program.addCommand(DevServerCommand);
  program.addCommand(SuiteManagerCommand);
  program.addCommand(SuiteScaffoldGenCommand);
  program.addCommand(DeployScaffoldGenCommand);
  program.addCommand(InterfaceScaffoldGenCommand);
  program.addCommand(ConceptScaffoldGenCommand);
  program.addCommand(SyncScaffoldGenCommand);
  program.addCommand(HandlerScaffoldGenCommand);
  program.addCommand(StorageAdapterScaffoldGenCommand);
  program.addCommand(TransportAdapterScaffoldGenCommand);
  program.addCommand(SurfaceComponentScaffoldGenCommand);
  program.addCommand(SurfaceThemeScaffoldGenCommand);
  program.addCommand(DerivedScaffoldGenCommand);
  program.addCommand(GeneratorCommand);
  program.addCommand(ProjectionCommand);
  program.addCommand(ApiSurfaceCommand);
  program.addCommand(SymbolCommand);
  program.addCommand(SymbolOccurrenceCommand);
  program.addCommand(ScopeGraphCommand);
  program.addCommand(SymbolRelationshipCommand);
  program.addCommand(ConceptEntityCommand);
  program.addCommand(ActionEntityCommand);
  program.addCommand(VariantEntityCommand);
  program.addCommand(StateFieldCommand);
  program.addCommand(SyncEntityCommand);
  program.addCommand(WidgetEntityCommand);
  program.addCommand(AnatomyPartEntityCommand);
  program.addCommand(WidgetStateEntityCommand);
  program.addCommand(WidgetPropEntityCommand);
  program.addCommand(ThemeEntityCommand);
  program.addCommand(InteractorEntityCommand);
  program.addCommand(RuntimeFlowCommand);
  program.addCommand(RuntimeCoverageCommand);
  program.addCommand(PerformanceProfileCommand);
  program.addCommand(ErrorCorrelationCommand);
  program.addCommand(DerivedEntityCommand);
  program.addCommand(HandlerEntityCommand);
  program.addCommand(WidgetImplementationEntityCommand);
  program.addCommand(ThemeImplementationEntityCommand);
  program.addCommand(DeploymentEntityCommand);
  program.addCommand(SuiteManifestEntityCommand);
  program.addCommand(InterfaceEntityCommand);
  program.addCommand(DeploymentHealthCommand);
  program.addCommand(InfrastructureEntityCommand);
  program.addCommand(GenerationProvenanceCommand);
  program.addCommand(TestEntityCommand);
  program.addCommand(EnvironmentEntityCommand);
  program.addCommand(DependenceGraphCommand);
  program.addCommand(DataFlowPathCommand);
  program.addCommand(ProgramSliceCommand);
  program.addCommand(AnalysisRuleCommand);
  program.addCommand(SemanticEmbeddingCommand);
  program.addCommand(ScoreApiCommand);
  program.addCommand(ScoreIndexCommand);
  program.addCommand(BranchCommand);
  program.addCommand(ChangeStreamCommand);
  program.addCommand(ContentHashCommand);
  program.addCommand(DAGHistoryCommand);
  program.addCommand(DiffCommand);
  program.addCommand(MergeCommand);
  program.addCommand(PatchCommand);
  program.addCommand(RefCommand);
  program.addCommand(RetentionPolicyCommand);
  program.addCommand(SchemaEvolutionCommand);
  program.addCommand(TemporalVersionCommand);
  program.addCommand(AttributionCommand);
  program.addCommand(CausalClockCommand);
  program.addCommand(ConflictResolutionCommand);
  program.addCommand(InlineAnnotationCommand);
  program.addCommand(PessimisticLockCommand);
  program.addCommand(ReplicaCommand);
  program.addCommand(SignatureCommand);
  program.addCommand(ActionGuideCommand);
  program.addCommand(EnrichmentRendererCommand);

export default program;
