// Auto-generated entrypoint for kit "clef-devtools", target "cli"
import { Command } from 'commander';
import { SpecParserCommand } from './SpecParser/SpecParser.command';
import { SchemaGenCommand } from './SchemaGen/SchemaGen.command';
import { SyncParserCommand } from './SyncParser/SyncParser.command';
import { SyncCompilerCommand } from './SyncCompiler/SyncCompiler.command';
import { FlowTraceCommand } from './FlowTrace/FlowTrace.command';
import { DeploymentValidatorCommand } from './DeploymentValidator/DeploymentValidator.command';
import { ProjectScaffoldCommand } from './ProjectScaffold/ProjectScaffold.command';
import { DevServerCommand } from './DevServer/DevServer.command';
import { SuiteManagerCommand } from './SuiteManager/SuiteManager.command';
import { EmitterCommand } from './Emitter/Emitter.command';
import { BuildCacheCommand } from './BuildCache/BuildCache.command';
import { ResourceCommand } from './Resource/Resource.command';
import { KindSystemCommand } from './KindSystem/KindSystem.command';
import { GenerationPlanCommand } from './GenerationPlan/GenerationPlan.command';
import { BuilderCommand } from './Builder/Builder.command';
import { ToolchainCommand } from './Toolchain/Toolchain.command';
import { SuiteScaffoldGenCommand } from './SuiteScaffoldGen/SuiteScaffoldGen.command';
import { DeployScaffoldGenCommand } from './DeployScaffoldGen/DeployScaffoldGen.command';
import { InterfaceScaffoldGenCommand } from './InterfaceScaffoldGen/InterfaceScaffoldGen.command';
import { ConceptScaffoldGenCommand } from './ConceptScaffoldGen/ConceptScaffoldGen.command';
import { SyncScaffoldGenCommand } from './SyncScaffoldGen/SyncScaffoldGen.command';
import { HandlerScaffoldGenCommand } from './HandlerScaffoldGen/HandlerScaffoldGen.command';
import { StorageAdapterScaffoldGenCommand } from './StorageAdapterScaffoldGen/StorageAdapterScaffoldGen.command';
import { TransportAdapterScaffoldGenCommand } from './TransportAdapterScaffoldGen/TransportAdapterScaffoldGen.command';
import { SurfaceComponentScaffoldGenCommand } from './SurfaceComponentScaffoldGen/SurfaceComponentScaffoldGen.command';
import { SurfaceThemeScaffoldGenCommand } from './SurfaceThemeScaffoldGen/SurfaceThemeScaffoldGen.command';
import { GeneratorCommand } from './Generator/Generator.command';
import { ProjectionCommand } from './Projection/Projection.command';
import { ApiSurfaceCommand } from './ApiSurface/ApiSurface.command';
import { ConformanceCommand } from './Conformance/Conformance.command';
import { TestSelectionCommand } from './TestSelection/TestSelection.command';
import { FlakyTestCommand } from './FlakyTest/FlakyTest.command';
import { ContractTestCommand } from './ContractTest/ContractTest.command';
import { SnapshotCommand } from './Snapshot/Snapshot.command';

const program = new Command();

  program.addCommand(SpecParserCommand);
  program.addCommand(SchemaGenCommand);
  program.addCommand(SyncParserCommand);
  program.addCommand(SyncCompilerCommand);
  program.addCommand(FlowTraceCommand);
  program.addCommand(DeploymentValidatorCommand);
  program.addCommand(ProjectScaffoldCommand);
  program.addCommand(DevServerCommand);
  program.addCommand(SuiteManagerCommand);
  program.addCommand(EmitterCommand);
  program.addCommand(BuildCacheCommand);
  program.addCommand(ResourceCommand);
  program.addCommand(KindSystemCommand);
  program.addCommand(GenerationPlanCommand);
  program.addCommand(BuilderCommand);
  program.addCommand(ToolchainCommand);
  program.addCommand(SuiteScaffoldGenCommand);
  program.addCommand(DeployScaffoldGenCommand);
  program.addCommand(InterfaceScaffoldGenCommand);
  program.addCommand(ConceptScaffoldGenCommand);
  program.addCommand(SyncScaffoldGenCommand);
  program.addCommand(HandlerScaffoldGenCommand);
  program.addCommand(StorageAdapterScaffoldGenCommand);
  program.addCommand(TransportAdapterScaffoldGenCommand);
  program.addCommand(SurfaceComponentScaffoldGenCommand);
  program.addCommand(SurfaceThemeScaffoldGenCommand);
  program.addCommand(GeneratorCommand);
  program.addCommand(ProjectionCommand);
  program.addCommand(ApiSurfaceCommand);
  program.addCommand(ConformanceCommand);
  program.addCommand(TestSelectionCommand);
  program.addCommand(FlakyTestCommand);
  program.addCommand(ContractTestCommand);
  program.addCommand(SnapshotCommand);

export default program;
