// Auto-generated entrypoint for suite "clef-devtools", target "cli"
import { Command } from 'commander';
import { specParserCommand } from './spec-parser/spec-parser.command';
import { schemaGenCommand } from './schema-gen/schema-gen.command';
import { syncParserCommand } from './sync-parser/sync-parser.command';
import { syncCompilerCommand } from './sync-compiler/sync-compiler.command';
import { flowTraceCommand } from './flow-trace/flow-trace.command';
import { deploymentValidatorCommand } from './deployment-validator/deployment-validator.command';
import { projectScaffoldCommand } from './project-scaffold/project-scaffold.command';
import { devServerCommand } from './dev-server/dev-server.command';
import { suiteManagerCommand } from './suite-manager/suite-manager.command';
import { kernelBootCommand } from './kernel-boot/kernel-boot.command';
import { deployPlanCommand } from './deploy-plan/deploy-plan.command';
import { vercelRuntimeCommand } from './vercel-runtime/vercel-runtime.command';
import { deployOrchestratorCommand } from './deploy-orchestrator/deploy-orchestrator.command';
import { suiteScaffoldGenCommand } from './suite-scaffold-gen/suite-scaffold-gen.command';
import { deployScaffoldGenCommand } from './deploy-scaffold-gen/deploy-scaffold-gen.command';
import { interfaceScaffoldGenCommand } from './interface-scaffold-gen/interface-scaffold-gen.command';
import { conceptScaffoldGenCommand } from './concept-scaffold-gen/concept-scaffold-gen.command';
import { syncScaffoldGenCommand } from './sync-scaffold-gen/sync-scaffold-gen.command';
import { handlerScaffoldGenCommand } from './handler-scaffold-gen/handler-scaffold-gen.command';
import { storageAdapterScaffoldGenCommand } from './storage-adapter-scaffold-gen/storage-adapter-scaffold-gen.command';
import { transportAdapterScaffoldGenCommand } from './transport-adapter-scaffold-gen/transport-adapter-scaffold-gen.command';
import { surfaceComponentScaffoldGenCommand } from './surface-component-scaffold-gen/surface-component-scaffold-gen.command';
import { surfaceThemeScaffoldGenCommand } from './surface-theme-scaffold-gen/surface-theme-scaffold-gen.command';
import { derivedScaffoldGenCommand } from './derived-scaffold-gen/derived-scaffold-gen.command';
import { generatorCommand } from './generator/generator.command';
import { projectionCommand } from './projection/projection.command';
import { apiSurfaceCommand } from './api-surface/api-surface.command';
import { symbolCommand } from './symbol/symbol.command';
import { symbolOccurrenceCommand } from './symbol-occurrence/symbol-occurrence.command';
import { scopeGraphCommand } from './scope-graph/scope-graph.command';
import { symbolRelationshipCommand } from './symbol-relationship/symbol-relationship.command';
import { conceptEntityCommand } from './concept-entity/concept-entity.command';
import { actionEntityCommand } from './action-entity/action-entity.command';
import { variantEntityCommand } from './variant-entity/variant-entity.command';
import { stateFieldCommand } from './state-field/state-field.command';
import { syncEntityCommand } from './sync-entity/sync-entity.command';
import { widgetEntityCommand } from './widget-entity/widget-entity.command';
import { anatomyPartEntityCommand } from './anatomy-part-entity/anatomy-part-entity.command';
import { widgetStateEntityCommand } from './widget-state-entity/widget-state-entity.command';
import { widgetPropEntityCommand } from './widget-prop-entity/widget-prop-entity.command';
import { themeEntityCommand } from './theme-entity/theme-entity.command';
import { interactorEntityCommand } from './interactor-entity/interactor-entity.command';
import { runtimeFlowCommand } from './runtime-flow/runtime-flow.command';
import { runtimeCoverageCommand } from './runtime-coverage/runtime-coverage.command';
import { performanceProfileCommand } from './performance-profile/performance-profile.command';
import { errorCorrelationCommand } from './error-correlation/error-correlation.command';
import { derivedEntityCommand } from './derived-entity/derived-entity.command';
import { handlerEntityCommand } from './handler-entity/handler-entity.command';
import { widgetImplementationEntityCommand } from './widget-implementation-entity/widget-implementation-entity.command';
import { themeImplementationEntityCommand } from './theme-implementation-entity/theme-implementation-entity.command';
import { deploymentEntityCommand } from './deployment-entity/deployment-entity.command';
import { suiteManifestEntityCommand } from './suite-manifest-entity/suite-manifest-entity.command';
import { interfaceEntityCommand } from './interface-entity/interface-entity.command';
import { deploymentHealthCommand } from './deployment-health/deployment-health.command';
import { infrastructureEntityCommand } from './infrastructure-entity/infrastructure-entity.command';
import { generationProvenanceCommand } from './generation-provenance/generation-provenance.command';
import { testEntityCommand } from './test-entity/test-entity.command';
import { environmentEntityCommand } from './environment-entity/environment-entity.command';
import { dependenceGraphCommand } from './dependence-graph/dependence-graph.command';
import { dataFlowPathCommand } from './data-flow-path/data-flow-path.command';
import { programSliceCommand } from './program-slice/program-slice.command';
import { analysisRuleCommand } from './analysis-rule/analysis-rule.command';
import { semanticEmbeddingCommand } from './semantic-embedding/semantic-embedding.command';
import { scoreApiCommand } from './score-api/score-api.command';
import { scoreIndexCommand } from './score-index/score-index.command';
import { branchCommand } from './branch/branch.command';
import { changeStreamCommand } from './change-stream/change-stream.command';
import { contentHashCommand } from './content-hash/content-hash.command';
import { dAGHistoryCommand } from './daghistory/daghistory.command';
import { diffCommand } from './diff/diff.command';
import { mergeCommand } from './merge/merge.command';
import { patchCommand } from './patch/patch.command';
import { refCommand } from './ref/ref.command';
import { retentionPolicyCommand } from './retention-policy/retention-policy.command';
import { schemaEvolutionCommand } from './schema-evolution/schema-evolution.command';
import { temporalVersionCommand } from './temporal-version/temporal-version.command';
import { attributionCommand } from './attribution/attribution.command';
import { causalClockCommand } from './causal-clock/causal-clock.command';
import { conflictResolutionCommand } from './conflict-resolution/conflict-resolution.command';
import { inlineAnnotationCommand } from './inline-annotation/inline-annotation.command';
import { pessimisticLockCommand } from './pessimistic-lock/pessimistic-lock.command';
import { replicaCommand } from './replica/replica.command';
import { signatureCommand } from './signature/signature.command';
import { actionGuideCommand } from './action-guide/action-guide.command';
import { enrichmentRendererCommand } from './enrichment-renderer/enrichment-renderer.command';

const program = new Command();

  program.addCommand(specParserCommand);
  program.addCommand(schemaGenCommand);
  program.addCommand(syncParserCommand);
  program.addCommand(syncCompilerCommand);
  program.addCommand(flowTraceCommand);
  program.addCommand(deploymentValidatorCommand);
  program.addCommand(projectScaffoldCommand);
  program.addCommand(devServerCommand);
  program.addCommand(suiteManagerCommand);
  program.addCommand(kernelBootCommand);
  program.addCommand(deployPlanCommand);
  program.addCommand(vercelRuntimeCommand);
  program.addCommand(deployOrchestratorCommand);
  program.addCommand(suiteScaffoldGenCommand);
  program.addCommand(deployScaffoldGenCommand);
  program.addCommand(interfaceScaffoldGenCommand);
  program.addCommand(conceptScaffoldGenCommand);
  program.addCommand(syncScaffoldGenCommand);
  program.addCommand(handlerScaffoldGenCommand);
  program.addCommand(storageAdapterScaffoldGenCommand);
  program.addCommand(transportAdapterScaffoldGenCommand);
  program.addCommand(surfaceComponentScaffoldGenCommand);
  program.addCommand(surfaceThemeScaffoldGenCommand);
  program.addCommand(derivedScaffoldGenCommand);
  program.addCommand(generatorCommand);
  program.addCommand(projectionCommand);
  program.addCommand(apiSurfaceCommand);
  program.addCommand(symbolCommand);
  program.addCommand(symbolOccurrenceCommand);
  program.addCommand(scopeGraphCommand);
  program.addCommand(symbolRelationshipCommand);
  program.addCommand(conceptEntityCommand);
  program.addCommand(actionEntityCommand);
  program.addCommand(variantEntityCommand);
  program.addCommand(stateFieldCommand);
  program.addCommand(syncEntityCommand);
  program.addCommand(widgetEntityCommand);
  program.addCommand(anatomyPartEntityCommand);
  program.addCommand(widgetStateEntityCommand);
  program.addCommand(widgetPropEntityCommand);
  program.addCommand(themeEntityCommand);
  program.addCommand(interactorEntityCommand);
  program.addCommand(runtimeFlowCommand);
  program.addCommand(runtimeCoverageCommand);
  program.addCommand(performanceProfileCommand);
  program.addCommand(errorCorrelationCommand);
  program.addCommand(derivedEntityCommand);
  program.addCommand(handlerEntityCommand);
  program.addCommand(widgetImplementationEntityCommand);
  program.addCommand(themeImplementationEntityCommand);
  program.addCommand(deploymentEntityCommand);
  program.addCommand(suiteManifestEntityCommand);
  program.addCommand(interfaceEntityCommand);
  program.addCommand(deploymentHealthCommand);
  program.addCommand(infrastructureEntityCommand);
  program.addCommand(generationProvenanceCommand);
  program.addCommand(testEntityCommand);
  program.addCommand(environmentEntityCommand);
  program.addCommand(dependenceGraphCommand);
  program.addCommand(dataFlowPathCommand);
  program.addCommand(programSliceCommand);
  program.addCommand(analysisRuleCommand);
  program.addCommand(semanticEmbeddingCommand);
  program.addCommand(scoreApiCommand);
  program.addCommand(scoreIndexCommand);
  program.addCommand(branchCommand);
  program.addCommand(changeStreamCommand);
  program.addCommand(contentHashCommand);
  program.addCommand(dAGHistoryCommand);
  program.addCommand(diffCommand);
  program.addCommand(mergeCommand);
  program.addCommand(patchCommand);
  program.addCommand(refCommand);
  program.addCommand(retentionPolicyCommand);
  program.addCommand(schemaEvolutionCommand);
  program.addCommand(temporalVersionCommand);
  program.addCommand(attributionCommand);
  program.addCommand(causalClockCommand);
  program.addCommand(conflictResolutionCommand);
  program.addCommand(inlineAnnotationCommand);
  program.addCommand(pessimisticLockCommand);
  program.addCommand(replicaCommand);
  program.addCommand(signatureCommand);
  program.addCommand(actionGuideCommand);
  program.addCommand(enrichmentRendererCommand);

export default program;
