# Ethereum Mainnet Deploy Template
#
# Single-chain deployment for Ethereum L1.
# ChainMonitor uses 12-confirmation finality.
deploy:
  name: ethereum-mainnet
  description: >
    Ethereum L1 deployment with 12-confirmation finality.
    Suitable for high-value actions where finality guarantees
    are critical (bridges, vaults, governance).

  runtime:
    engine: clef-sync-engine
    transport: http

  concepts:
    ChainMonitor:
      params:
        B: ethereum-block
      config:
        chainId: 1
        finalityType: confirmations
        threshold: 12

    Content:
      params:
        C: ipfs-cid

    Wallet:
      params:
        W: ethereum-address

  infrastructure:
    transports:
      evm:
        type: evm
        config:
          chainId: 1
          rpcUrl: "${ETHEREUM_RPC_URL}"
          wsUrl: "${ETHEREUM_WS_URL}"
          gasStrategy: eip1559
          maxGasPrice: 100
          confirmationTimeout: 300000

    storage:
      ipfs:
        type: ipfs
        config:
          apiUrl: "${IPFS_API_URL}"
          gatewayUrl: "${IPFS_GATEWAY_URL}"
          pinning: pinata
          apiKey: "${PINATA_API_KEY}"

  syncs:
    - finality-gate
    - reorg-compensation
    - content-pinning
