// Auto-generated by Clef Clef Bind — cli target
// Concept: ViewShell
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const viewShellCommand = new Command('view-shell')
  .description('Name and bind the user facing identity of a view by holding references to all subordinate configuration concepts filter , sort , group , projection , presentation , interaction , and data source . ViewShell owns no query or render logic itself ; it is a composition point that lets a view be addressed by a single stable name and resolved into a complete , hydrated ViewConfig at runtime . A nullable legacyConfig field supports migration from monolithic JSON based view records without breaking existing callers');

viewShellCommand
  .command('create')
  .description('Register a new named view shell with the given title , description , and child spec references . The view is immediately addressable by name and ready for resolution into a complete ViewConfig .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--title <title>', 'Title')
  .requiredOption('--description <description>', 'Description')
  .requiredOption('--data-source <dataSource>', 'Data Source')
  .requiredOption('--filter <filter>', 'Filter')
  .requiredOption('--sort <sort>', 'Sort')
  .requiredOption('--group <group>', 'Group')
  .requiredOption('--projection <projection>', 'Projection')
  .requiredOption('--presentation <presentation>', 'Presentation')
  .requiredOption('--interaction <interaction>', 'Interaction')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ViewShell', 'create', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

viewShellCommand
  .command('get')
  .description('Return the view shell s title , description , and all child spec reference names exactly as registered .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ViewShell', 'get', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

viewShellCommand
  .command('update')
  .description('Replace the title , description , and all child spec references for the named view . The view s name remains unchanged ; all other fields are overwritten with the supplied values .')
  .requiredOption('--name <name>', 'Name')
  .requiredOption('--title <title>', 'Title')
  .requiredOption('--description <description>', 'Description')
  .requiredOption('--data-source <dataSource>', 'Data Source')
  .requiredOption('--filter <filter>', 'Filter')
  .requiredOption('--sort <sort>', 'Sort')
  .requiredOption('--group <group>', 'Group')
  .requiredOption('--projection <projection>', 'Projection')
  .requiredOption('--presentation <presentation>', 'Presentation')
  .requiredOption('--interaction <interaction>', 'Interaction')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ViewShell', 'update', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

viewShellCommand
  .command('resolve')
  .description('Hydrate all referenced child specs into a complete ViewConfig JSON string . If the view s legacyConfig is set and all child spec references are empty , the legacyConfig is returned verbatim to preserve backward compatibility during migration . Otherwise the config is assembled from the registered child spec names .')
  .requiredOption('--name <name>', 'Name')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ViewShell', 'resolve', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

viewShellCommand
  .command('list')
  .description('Return all registered view shells as a JSON array , each entry containing the view s name , title , description , and all child spec reference names .')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/ViewShell', 'list', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const viewShellCommandTree = {
  group: 'view-shell',
  description: 'Name and bind the user facing identity of a view by holding references to all subordinate configuration concepts filter , sort , group , projection , presentation , interaction , and data source . ViewShell owns no query or render logic itself ; it is a composition point that lets a view be addressed by a single stable name and resolved into a complete , hydrated ViewConfig at runtime . A nullable legacyConfig field supports migration from monolithic JSON based view records without breaking existing callers',
  commands: [{ action: 'create', command: 'create' }, { action: 'get', command: 'get' }, { action: 'update', command: 'update' }, { action: 'resolve', command: 'resolve' }, { action: 'list', command: 'list' }],
};
