// Auto-generated by Clef Clef Bind — mcp target
// Concept: Ref
// Do not edit manually; regenerate with: clef interface generate

export const refTools = [
  {
    "type": "tool",
    "name": "ref_create",
    "description": "Create ref — Named reference created pointing to the given hash .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "hash": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "hash"
      ]
    }
  },
  {
    "type": "tool",
    "name": "ref_update",
    "description": "Update ref — Reference atomically updated via compare and swap . \n Old value recorded in reflog .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "newHash": {
          "type": "string"
        },
        "expectedOldHash": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "newHash",
        "expectedOldHash"
      ]
    }
  },
  {
    "type": "tool",
    "name": "ref_delete",
    "description": "Delete ref — Reference removed . Reflog entry added .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "type": "tool",
    "name": "ref_resolve",
    "description": "Resolve ref — Returns the current hash target of the named ref .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  },
  {
    "type": "tool",
    "name": "ref_log",
    "description": "Log ref — Returns the mutation history for this ref .",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  }
];
