// Auto-generated by Clef Clef Bind — cli target
// Concept: SurfaceThemeScaffoldGen
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const surfaceThemeScaffoldGenCommand = new Command('scaffold-theme')
  .description('Generate Clef Surface design system theme (.theme) with oklch palette, typography, spacing, motion, elevation, radius.');

surfaceThemeScaffoldGenCommand
  .command('theme')
  .description('Scaffold a .theme file with oklch palette, typography, spacing, motion, elevation, and radius tokens.')
  .requiredOption('-n, --name <name>', 'Theme name (kebab-case)')
  .requiredOption('--primary-color <primaryColor>', 'Primary Color')
  .requiredOption('--font-family <fontFamily>', 'Font Family')
  .requiredOption('--base-size <baseSize>', 'Base Size')
  .option('--scale <scale>', 'Modular ratio for type scale', '1.25')
  .requiredOption('--secondary-color <secondaryColor>', 'Secondary Color')
  .requiredOption('--border-radius <borderRadius>', 'Border Radius')
  .option('-m, --mode <value>', 'Theme mode (light|dark|both)', 'both')
  .option('--extends <extends>', 'Base theme name to extend (for theme variants)')
  .option('--json', 'Output as JSON')
  .addHelpText('after', '\nExamples:')
  .addHelpText('after', '  clef scaffold theme --name ocean  # Generate a theme with defaults')
  .addHelpText('after', '  clef scaffold theme --name brand --primary 220 --font \'Inter, sans-serif\' --base-size 18  # Generate a custom theme')
  .addHelpText('after', '  clef scaffold theme --name print --mode light  # Generate a light-only theme')
  .addHelpText('after', '  clef scaffold theme --name ocean-compact --extends ocean --base-size 14  # Generate a theme variant')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SurfaceThemeScaffoldGen', 'generate', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

surfaceThemeScaffoldGenCommand
  .command('preview')
  .description('Dry-run: compute output files without writing. Uses Emitter content-addressing to show what would change.')
  .requiredOption('-n, --name <name>', 'Theme name (kebab-case)')
  .requiredOption('--primary-color <primaryColor>', 'Primary Color')
  .requiredOption('--font-family <fontFamily>', 'Font Family')
  .requiredOption('--base-size <baseSize>', 'Base Size')
  .requiredOption('--scale <scale>', 'Scale')
  .requiredOption('--secondary-color <secondaryColor>', 'Secondary Color')
  .requiredOption('--border-radius <borderRadius>', 'Border Radius')
  .requiredOption('--mode <mode>', 'Mode')
  .requiredOption('--extends <extends>', 'Extends')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SurfaceThemeScaffoldGen', 'preview', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

surfaceThemeScaffoldGenCommand
  .command('register')
  .description('Return static metadata for PluginRegistry . name : SurfaceThemeScaffoldGen inputKind : ThemeConfig outputKind : SurfaceTheme capabilities : [ palette , typography , spacing , motion , elevation , radius , extends , wcag ]')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/SurfaceThemeScaffoldGen', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const surfaceThemeScaffoldGenCommandTree = {
  group: 'scaffold-theme',
  description: 'Generate Clef Surface design system theme (.theme) with oklch palette, typography, spacing, motion, elevation, radius.',
  commands: [{ action: 'generate', command: 'theme' }, { action: 'preview', command: 'preview' }, { action: 'register', command: 'register' }],
};
