// Auto-generated by Clef Clef Bind — cli target
// Concept: A11yAdaptProvider
// Do not edit manually; regenerate with: clef interface generate

import { Command } from 'commander';

export const a11yAdaptProviderCommand = new Command('a11y-adapt-provider')
  .description('Apply accessibility adaptations to RenderProgram instruction sequences modifying existing ARIA attributes and injecting new keyboard , focus , and ARIA instructions so that a11y variants become composable program transformations');

a11yAdaptProviderCommand
  .command('register')
  .description('Return static metadata for PluginRegistry . name : A11yAdaptProvider kind : a11y-adapt capabilities : [ aria-modification , aria-injection , keyboard-adapt , focus-adapt ]')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/A11yAdaptProvider', 'register', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

a11yAdaptProviderCommand
  .command('apply')
  .description('Apply modifications to matching instructions first , then insert additions before the terminal pure instruction . Modifications match on partial instruction patterns and merge new fields . Additions are complete instructions injected into the sequence . Returns the new serialized program and the updated list of applied transforms .')
  .requiredOption('--program <program>', 'Program')
  .requiredOption('--spec <spec>', 'Spec')
  .option('--json', 'Output as JSON')
  .action(async (opts) => {
    try {
      const result = await globalThis.kernel.invokeConcept('urn:clef/A11yAdaptProvider', 'apply', opts);
      if (result.variant !== 'ok') {
        console.error(opts.json ? JSON.stringify(result) : `Error [${result.variant}]: ${JSON.stringify(result)}`);
        process.exitCode = 1;
      } else {
        console.log(opts.json ? JSON.stringify(result) : result);
      }
    } catch (err) {
      console.error(err instanceof Error ? err.message : err);
      process.exitCode = 1;
    }
  });

export const a11yAdaptProviderCommandTree = {
  group: 'a11y-adapt-provider',
  description: 'Apply accessibility adaptations to RenderProgram instruction sequences modifying existing ARIA attributes and injecting new keyboard , focus , and ARIA instructions so that a11y variants become composable program transformations',
  commands: [{ action: 'register', command: 'register' }, { action: 'apply', command: 'apply' }],
};
